type: object
description: |
  Full network configuration: network identity, chain parameters, plugin settings,
  and fork heights. Combines data from catapult-server config files (network, chain, plugins).
required:
  - network
  - chain
  - plugins
  - forkHeights
properties:
  network:
    $ref: "./NetworkPropertiesDTO.yml"
  chain:
    $ref: "./ChainPropertiesDTO.yml"
  plugins:
    $ref: "./PluginsPropertiesDTO.yml"
  forkHeights:
    $ref: "./ForkHeightsDTO.yml"
  treasuryReissuanceTransactionSignatures:
    type: array
    items:
      type: string
    description: |
      Multisignature approvals authorizing the network treasury reissuance event for the specified fork height.
      More: https://hackmd.io/@syndicate/governance.
    examples:
      -
        - "0BBEADD37539444D75C09A245102D2B883267925398504623835DCD625290DEE4FA2371341050C49C001DEDD1C9FE241EA4A"
        - "89447704270E8B2F8EED19526587DB58870D90A02ACEF8AE2A54311DEB95C227201CD39662A0229D5746FFB84074EA6C7DD9"
  corruptAggregateTransactionHashes:
    type: array
    items:
      type: string
    description: |
      List of aggregate transaction hashes that were known to be invalid due to a bug and must be remapped to corrected hashes.
      More: https://hackmd.io/@syndicate/postmortem-251022.
    examples:
      -
        - "26FF5E7174DEEF3147DB25C37C7AE9905157ACBA2D233D40D1F77A65B60D59BC = 3A2F78C2E7B10FF84EB33BF1DD0FD61951F8E3E"
        - "30FA71E6D1E34DF1E430A07E1B0817BED9A4ED6B0245B7471B0557380A700E1B = AE377EAB7F1970DEC21FF305C39EBDD3ECE413B"
