#pragma once
#include "catapult/model/EntityInfo.h"
#include "catapult/model/EntityRange.h"
#include "catapult/utils/ShortHash.h"
#include <vector>

namespace catapult {
	namespace cache {
		class MemoryUtCache;
		class MemoryUtCacheView;
		class UtCache;
	}
}

namespace catapult { namespace test {

	/// Creates a transaction info composed of a random transaction with the specified \a deadline
	/// and a random hash.
	model::TransactionInfo CreateTransactionInfoWithDeadline(size_t deadline);

	/// Creates \a count transaction infos with deadlines in the range [1, \a count].
	std::vector<model::TransactionInfo> CreateTransactionInfos(size_t count);

	/// Creates \a count transaction infos with deadlines generated by \a deadlineGenerator.
	std::vector<model::TransactionInfo> CreateTransactionInfos(
			size_t count,
			const std::function<Timestamp (size_t)>& deadlineGenerator);

	/// Extracts all entities from \a infos.
	std::vector<const model::VerifiableEntity*> ExtractEntities(const std::vector<model::TransactionInfo>& infos);

	/// Extracts all hashes from \a infos.
	std::vector<Hash256> ExtractHashes(const std::vector<model::TransactionInfo>& infos);

	/// Adds all \a infos to \a cache.
	void AddAll(cache::UtCache& cache, std::vector<model::TransactionInfo>&& infos);

	/// Removes all infos identified by the hashes in \a hashes from \a cache.
	void RemoveAll(cache::UtCache& cache, const std::vector<Hash256>& hashes);

	/// Extracts the deadlines of all transactions stored in \a cache.
	std::vector<Timestamp::ValueType> ExtractRawDeadlines(const cache::MemoryUtCache& cache);

	/// Extracts copies of the first \a count transactions stored in \a cache.
	std::vector<std::unique_ptr<const model::Transaction>> ExtractTransactions(const cache::MemoryUtCache& cache, size_t count);

	/// Extracts pointers to the first \a count transaction infos stored in \a view.
	std::vector<const model::TransactionInfo*> ExtractTransactionInfos(const cache::MemoryUtCacheView& view, size_t count);

	/// Extracts short hashes for all transactions stored in \a cache.
	model::EntityRange<utils::ShortHash> ExtractShortHashes(const cache::MemoryUtCache& cache);

	/// Asserts that the deadlines of all transactions stored in \a cache are equal to \a expectedDeadlines.
	void AssertDeadlines(
			const cache::MemoryUtCache& cache,
			const std::vector<Timestamp::ValueType>& expectedDeadlines);

	/// Asserts that \a cache contains all of the hashes in \a hashes.
	void AssertContainsAll(
			const cache::MemoryUtCache& cache,
			const std::vector<Hash256>& hashes);

	/// Asserts that \a cache contains none of the hashes in \a hashes.
	void AssertContainsNone(
			const cache::MemoryUtCache& cache,
			const std::vector<Hash256>& hashes);

	/// Asserts that \a cache contains all of the infos in \a infos.
	void AssertContainsAll(
			const cache::MemoryUtCache& cache,
			const std::vector<model::TransactionInfo>& infos);

	/// Asserts that \a cache contains none of the infos in \a infos.
	void AssertContainsNone(
			const cache::MemoryUtCache& cache,
			const std::vector<model::TransactionInfo>& infos);

	/// Asserts that \a lhs and \a rhs are equal.
	void AssertEqual(const model::TransactionInfo& lhs, const model::TransactionInfo& rhs);
}}
