# Setting coverage targets per flag
# Each project represent a package which has one flag
coverage:
  status:
    project:
      default:
        target: 90%  # overall project / repo coverage

      catbuffer-parser:
        target: auto
        threshold: 1%
        flags:
          - catbuffer-parser

      client-catapult:
        target: auto
        threshold: 1%
        flags:
          - client-catapult

      client-rest:
        target: auto
        threshold: 1%
        flags:
          - client-rest

      sdk-javascript:
        target: auto
        threshold: 1%
        flags:
          - sdk-javascript

      sdk-python:
        target: auto
        threshold: 1%
        flags:
          - sdk-python

# New root YAML section = `flags:`
# This is where you would define every flag from your
# uploader, and update when new Flags added
# Each flag is used to represent each package in the
# monorepo.  This allows code coverage per package.

flags:
  catbuffer-parser:
    paths:
      - catbuffer/parser
    carryforward: true

  client-catapult:
    paths:
      - client/catapult
    carryforward: true

  client-rest:
    paths:
      - client/rest
    carryforward: true

  sdk-javascript:
    paths:
      - sdk/javascript
    carryforward: true

  sdk-python:
    paths:
      - sdk/python
    carryforward: true
