version: 2
updates:

  - package-ecosystem: cargo
    schedule:
      interval: weekly
      day: sunday
    labels: [dependencies]
    commit-message:
      prefix: '[dependency]'
    target-branch: dev
    directory: /sdk/javascript/wasm
    versioning-strategy: auto
    groups:
      cargo-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    schedule:
      interval: weekly
      day: sunday
    labels: [dependencies]
    commit-message:
      prefix: '[dependency]'
    target-branch: dev
    directory: /
    groups:
      github-actions-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    schedule:
      interval: weekly
      day: sunday
    labels: [dependencies]
    commit-message:
      prefix: '[dependency]'
    target-branch: dev
    versioning-strategy: increase-if-necessary
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    directories:
      - /client/rest
      - /sdk/javascript

  - package-ecosystem: pip
    schedule:
      interval: weekly
      day: sunday
    labels: [dependencies]
    commit-message:
      prefix: '[dependency]'
    target-branch: dev
    versioning-strategy: increase-if-necessary
    groups:
      pip-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    directories:
      - /catbuffer/parser
      - /client/catapult/scripts
      - /jenkins/catapult
      - /linters/cpp
      - /linters/python
      - /sdk/javascript/generator
      - /sdk/python
