// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.sameInstance;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import org.symbol.sdk.CryptoTypes;
import org.symbol.sdk.nem.NemTransactionFactory;
import org.symbol.sdk.nem.Network;
import org.symbol.sdk.nem.models.AccountKeyLinkTransactionV1;
import org.symbol.sdk.nem.models.Amount;
import org.symbol.sdk.nem.models.CosignatureV1;
import org.symbol.sdk.nem.models.Hash256;
import org.symbol.sdk.nem.models.LinkAction;
import org.symbol.sdk.nem.models.MessageType;
import org.symbol.sdk.nem.models.MosaicDefinitionTransactionV1;
import org.symbol.sdk.nem.models.MosaicSupplyChangeAction;
import org.symbol.sdk.nem.models.MosaicSupplyChangeTransactionV1;
import org.symbol.sdk.nem.models.MosaicTransferFeeType;
import org.symbol.sdk.nem.models.MultisigAccountModificationTransactionV1;
import org.symbol.sdk.nem.models.MultisigAccountModificationTransactionV2;
import org.symbol.sdk.nem.models.MultisigAccountModificationType;
import org.symbol.sdk.nem.models.MultisigTransactionV1;
import org.symbol.sdk.nem.models.NamespaceRegistrationTransactionV1;
import org.symbol.sdk.nem.models.NonVerifiableAccountKeyLinkTransactionV1;
import org.symbol.sdk.nem.models.PublicKey;
import org.symbol.sdk.nem.models.TransferTransactionV1;
import org.symbol.sdk.nem.models.TransferTransactionV2;

/**
 * Generated per-descriptor sweep: construction with distinct sample values, exact {@code toMap()} contents, string-form constructor
 * equivalence, every optional fluent setter, and (for transaction descriptors) a factory round-trip verifying each created-model field via
 * {@code getField}.
 */
final class DescriptorsSweepTest {
	private static final CryptoTypes.PublicKey SWEEP_SIGNER_PUBLIC_KEY = new CryptoTypes.PublicKey(
			"364F3694A022DB4DC59558944707C6679F6FD7E1A7B99CDE8F7D16D3FF515D28");

	private static final NemTransactionFactory FACTORY = new NemTransactionFactory(Network.TESTNET);

	/**
	 * Returns the descriptor's map with the sweep signer added. No defensive copy is needed: toMap() returns the live descriptor map, and
	 * the descriptor is a throwaway sweep instance.
	 */
	private static Map<String, Object> sweepCreateMap(final NemTransactionDescriptor descriptor) {
		final Map<String, Object> createMap = descriptor.toMap();
		createMap.put("signerPublicKey", SWEEP_SIGNER_PUBLIC_KEY);
		return createMap;
	}

	/** Constructs a AccountKeyLinkTransactionV1Descriptor with distinct sample required arguments. */
	private static AccountKeyLinkTransactionV1Descriptor sweepNewAccountKeyLinkTransactionV1Descriptor() {
		return new AccountKeyLinkTransactionV1Descriptor(LinkAction.parse("link"),
				new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303"));
	}

	@Test
	void accountKeyLinkTransactionV1Descriptor() {
		// Arrange:
		final AccountKeyLinkTransactionV1Descriptor descriptor = sweepNewAccountKeyLinkTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("account_key_link_transaction_v1"));
		assertThat(built.get("linkAction"), equalTo(LinkAction.parse("link")));
		assertThat(built.get("remotePublicKey"),
				equalTo(new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void accountKeyLinkTransactionV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewAccountKeyLinkTransactionV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new AccountKeyLinkTransactionV1Descriptor("link",
				"0303030303030303030303030303030303030303030303030303030303030303").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("linkAction"), equalTo(built.get("linkAction")));
		assertThat(stringBuilt.get("remotePublicKey"), equalTo(built.get("remotePublicKey")));
	}

	@Test
	void accountKeyLinkTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewAccountKeyLinkTransactionV1Descriptor());

		// Act:
		final AccountKeyLinkTransactionV1 transaction = (AccountKeyLinkTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getLinkAction(), equalTo(LinkAction.parse("link")));
		assertThat(transaction.getRemotePublicKey(), equalTo(
				new PublicKey((new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303")).bytes())));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a NamespaceIdDescriptor with distinct sample required arguments. */
	private static NamespaceIdDescriptor sweepNewNamespaceIdDescriptor() {
		return new NamespaceIdDescriptor();
	}

	@Test
	void namespaceIdDescriptor() {
		// Arrange:
		final NamespaceIdDescriptor descriptor = sweepNewNamespaceIdDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.size(), equalTo(0));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: name
		assertThat(built.containsKey("name"), equalTo(false));
		assertThat(sweepNewNamespaceIdDescriptor().name((byte[]) null).toMap().containsKey("name"), equalTo(false));
		assertThat(sweepNewNamespaceIdDescriptor().name((String) null).toMap().containsKey("name"), equalTo(false));
		final NamespaceIdDescriptor withName = sweepNewNamespaceIdDescriptor();
		assertThat(withName.name("name".getBytes(StandardCharsets.UTF_8)), sameInstance(withName));
		assertThat(withName.toMap().get("name"), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewNamespaceIdDescriptor().name("name").toMap().get("name"), equalTo(withName.toMap().get("name")));
	}

	/** Constructs a MosaicIdDescriptor with distinct sample required arguments. */
	private static MosaicIdDescriptor sweepNewMosaicIdDescriptor() {
		return new MosaicIdDescriptor(sweepNewNamespaceIdDescriptor());
	}

	@Test
	void mosaicIdDescriptor() {
		// Arrange:
		final MosaicIdDescriptor descriptor = sweepNewMosaicIdDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("namespaceId"), equalTo(sweepNewNamespaceIdDescriptor().toMap()));
		assertThat(built.size(), equalTo(1));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: name
		assertThat(built.containsKey("name"), equalTo(false));
		assertThat(sweepNewMosaicIdDescriptor().name((byte[]) null).toMap().containsKey("name"), equalTo(false));
		assertThat(sweepNewMosaicIdDescriptor().name((String) null).toMap().containsKey("name"), equalTo(false));
		final MosaicIdDescriptor withName = sweepNewMosaicIdDescriptor();
		assertThat(withName.name("name".getBytes(StandardCharsets.UTF_8)), sameInstance(withName));
		assertThat(withName.toMap().get("name"), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewMosaicIdDescriptor().name("name").toMap().get("name"), equalTo(withName.toMap().get("name")));
	}

	/** Constructs a MosaicDescriptor with distinct sample required arguments. */
	private static MosaicDescriptor sweepNewMosaicDescriptor() {
		return new MosaicDescriptor(sweepNewMosaicIdDescriptor(), Amount.parse("2"));
	}

	@Test
	void mosaicDescriptor() {
		// Arrange:
		final MosaicDescriptor descriptor = sweepNewMosaicDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("mosaicId"), equalTo(sweepNewMosaicIdDescriptor().toMap()));
		assertThat(built.get("amount"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(2));
	}

	@Test
	void mosaicDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMosaicDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MosaicDescriptor(sweepNewMosaicIdDescriptor(), "2").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("mosaicId"), equalTo(built.get("mosaicId")));
		assertThat(stringBuilt.get("amount"), equalTo(built.get("amount")));
	}

	/** Constructs a SizePrefixedMosaicDescriptor with distinct sample required arguments. */
	private static SizePrefixedMosaicDescriptor sweepNewSizePrefixedMosaicDescriptor() {
		return new SizePrefixedMosaicDescriptor(sweepNewMosaicDescriptor());
	}

	@Test
	void sizePrefixedMosaicDescriptor() {
		// Arrange:
		final SizePrefixedMosaicDescriptor descriptor = sweepNewSizePrefixedMosaicDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("mosaic"), equalTo(sweepNewMosaicDescriptor().toMap()));
		assertThat(built.size(), equalTo(1));
	}

	/** Constructs a MosaicLevyDescriptor with distinct sample required arguments. */
	private static MosaicLevyDescriptor sweepNewMosaicLevyDescriptor() {
		return new MosaicLevyDescriptor(MosaicTransferFeeType.parse("absolute"),
				new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"), sweepNewMosaicIdDescriptor(),
				Amount.parse("4"));
	}

	@Test
	void mosaicLevyDescriptor() {
		// Arrange:
		final MosaicLevyDescriptor descriptor = sweepNewMosaicLevyDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("transferFeeType"), equalTo(MosaicTransferFeeType.parse("absolute")));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.get("mosaicId"), equalTo(sweepNewMosaicIdDescriptor().toMap()));
		assertThat(built.get("fee"), equalTo(Amount.parse("4")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void mosaicLevyDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMosaicLevyDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MosaicLevyDescriptor("absolute", "TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C",
				sweepNewMosaicIdDescriptor(), "4").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("transferFeeType"), equalTo(built.get("transferFeeType")));
		assertThat(stringBuilt.get("recipientAddress"), equalTo(built.get("recipientAddress")));
		assertThat(stringBuilt.get("mosaicId"), equalTo(built.get("mosaicId")));
		assertThat(stringBuilt.get("fee"), equalTo(built.get("fee")));
	}

	/** Constructs a MosaicPropertyDescriptor with distinct sample required arguments. */
	private static MosaicPropertyDescriptor sweepNewMosaicPropertyDescriptor() {
		return new MosaicPropertyDescriptor();
	}

	@Test
	void mosaicPropertyDescriptor() {
		// Arrange:
		final MosaicPropertyDescriptor descriptor = sweepNewMosaicPropertyDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.size(), equalTo(0));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: name
		assertThat(built.containsKey("name"), equalTo(false));
		assertThat(sweepNewMosaicPropertyDescriptor().name((byte[]) null).toMap().containsKey("name"), equalTo(false));
		assertThat(sweepNewMosaicPropertyDescriptor().name((String) null).toMap().containsKey("name"), equalTo(false));
		final MosaicPropertyDescriptor withName = sweepNewMosaicPropertyDescriptor();
		assertThat(withName.name("name".getBytes(StandardCharsets.UTF_8)), sameInstance(withName));
		assertThat(withName.toMap().get("name"), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewMosaicPropertyDescriptor().name("name").toMap().get("name"), equalTo(withName.toMap().get("name")));

		// optional field: value
		assertThat(built.containsKey("value"), equalTo(false));
		assertThat(sweepNewMosaicPropertyDescriptor().value((byte[]) null).toMap().containsKey("value"), equalTo(false));
		assertThat(sweepNewMosaicPropertyDescriptor().value((String) null).toMap().containsKey("value"), equalTo(false));
		final MosaicPropertyDescriptor withValue = sweepNewMosaicPropertyDescriptor();
		assertThat(withValue.value("value".getBytes(StandardCharsets.UTF_8)), sameInstance(withValue));
		assertThat(withValue.toMap().get("value"), equalTo("value".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewMosaicPropertyDescriptor().value("value").toMap().get("value"), equalTo(withValue.toMap().get("value")));
	}

	/** Constructs a SizePrefixedMosaicPropertyDescriptor with distinct sample required arguments. */
	private static SizePrefixedMosaicPropertyDescriptor sweepNewSizePrefixedMosaicPropertyDescriptor() {
		return new SizePrefixedMosaicPropertyDescriptor(sweepNewMosaicPropertyDescriptor());
	}

	@Test
	void sizePrefixedMosaicPropertyDescriptor() {
		// Arrange:
		final SizePrefixedMosaicPropertyDescriptor descriptor = sweepNewSizePrefixedMosaicPropertyDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("property"), equalTo(sweepNewMosaicPropertyDescriptor().toMap()));
		assertThat(built.size(), equalTo(1));
	}

	/** Constructs a MosaicDefinitionDescriptor with distinct sample required arguments. */
	private static MosaicDefinitionDescriptor sweepNewMosaicDefinitionDescriptor() {
		return new MosaicDefinitionDescriptor(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"),
				sweepNewMosaicIdDescriptor());
	}

	@Test
	void mosaicDefinitionDescriptor() {
		// Arrange:
		final MosaicDefinitionDescriptor descriptor = sweepNewMosaicDefinitionDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("ownerPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("id"), equalTo(sweepNewMosaicIdDescriptor().toMap()));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: description
		assertThat(built.containsKey("description"), equalTo(false));
		assertThat(sweepNewMosaicDefinitionDescriptor().description((byte[]) null).toMap().containsKey("description"), equalTo(false));
		assertThat(sweepNewMosaicDefinitionDescriptor().description((String) null).toMap().containsKey("description"), equalTo(false));
		final MosaicDefinitionDescriptor withDescription = sweepNewMosaicDefinitionDescriptor();
		assertThat(withDescription.description("description".getBytes(StandardCharsets.UTF_8)), sameInstance(withDescription));
		assertThat(withDescription.toMap().get("description"), equalTo("description".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewMosaicDefinitionDescriptor().description("description").toMap().get("description"),
				equalTo(withDescription.toMap().get("description")));

		// optional field: properties
		assertThat(built.containsKey("properties"), equalTo(false));
		assertThat(sweepNewMosaicDefinitionDescriptor().properties((List<SizePrefixedMosaicPropertyDescriptor>) null).toMap()
				.containsKey("properties"), equalTo(false));
		final MosaicDefinitionDescriptor withProperties = sweepNewMosaicDefinitionDescriptor();
		assertThat(withProperties.properties(List.of(sweepNewSizePrefixedMosaicPropertyDescriptor())), sameInstance(withProperties));
		assertThat(withProperties.toMap().get("properties"), equalTo(List.of(sweepNewSizePrefixedMosaicPropertyDescriptor().toMap())));
		assertThat(
				sweepNewMosaicDefinitionDescriptor().properties(sweepNewSizePrefixedMosaicPropertyDescriptor()).toMap().get("properties"),
				equalTo(withProperties.toMap().get("properties")));

		// optional field: levy
		assertThat(built.containsKey("levy"), equalTo(false));
		assertThat(sweepNewMosaicDefinitionDescriptor().levy((MosaicLevyDescriptor) null).toMap().containsKey("levy"), equalTo(false));
		final MosaicDefinitionDescriptor withLevy = sweepNewMosaicDefinitionDescriptor();
		assertThat(withLevy.levy(sweepNewMosaicLevyDescriptor()), sameInstance(withLevy));
		assertThat(withLevy.toMap().get("levy"), equalTo(sweepNewMosaicLevyDescriptor().toMap()));
	}

	@Test
	void mosaicDefinitionDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMosaicDefinitionDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MosaicDefinitionDescriptor(
				"0202020202020202020202020202020202020202020202020202020202020202", sweepNewMosaicIdDescriptor()).toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("ownerPublicKey"), equalTo(built.get("ownerPublicKey")));
		assertThat(stringBuilt.get("id"), equalTo(built.get("id")));
	}

	/** Constructs a MosaicDefinitionTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicDefinitionTransactionV1Descriptor sweepNewMosaicDefinitionTransactionV1Descriptor() {
		return new MosaicDefinitionTransactionV1Descriptor(sweepNewMosaicDefinitionDescriptor(),
				new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"), Amount.parse("3"));
	}

	@Test
	void mosaicDefinitionTransactionV1Descriptor() {
		// Arrange:
		final MosaicDefinitionTransactionV1Descriptor descriptor = sweepNewMosaicDefinitionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_definition_transaction_v1"));
		assertThat(built.get("mosaicDefinition"), equalTo(sweepNewMosaicDefinitionDescriptor().toMap()));
		assertThat(built.get("rentalFeeSink"), equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.get("rentalFee"), equalTo(Amount.parse("3")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void mosaicDefinitionTransactionV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMosaicDefinitionTransactionV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MosaicDefinitionTransactionV1Descriptor(sweepNewMosaicDefinitionDescriptor(),
				"TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C", "3").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("mosaicDefinition"), equalTo(built.get("mosaicDefinition")));
		assertThat(stringBuilt.get("rentalFeeSink"), equalTo(built.get("rentalFeeSink")));
		assertThat(stringBuilt.get("rentalFee"), equalTo(built.get("rentalFee")));
	}

	@Test
	void mosaicDefinitionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewMosaicDefinitionTransactionV1Descriptor());

		// Act:
		final MosaicDefinitionTransactionV1 transaction = (MosaicDefinitionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaicDefinition(), notNullValue());
		assertThat(transaction.getRentalFeeSink(), equalTo(new org.symbol.sdk.nem.models.Address(
				(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")).toString().getBytes(StandardCharsets.UTF_8))));
		assertThat(transaction.getRentalFee(), equalTo(Amount.parse("3")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicSupplyChangeTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicSupplyChangeTransactionV1Descriptor sweepNewMosaicSupplyChangeTransactionV1Descriptor() {
		return new MosaicSupplyChangeTransactionV1Descriptor(sweepNewMosaicIdDescriptor(), MosaicSupplyChangeAction.parse("decrease"),
				Amount.parse("3"));
	}

	@Test
	void mosaicSupplyChangeTransactionV1Descriptor() {
		// Arrange:
		final MosaicSupplyChangeTransactionV1Descriptor descriptor = sweepNewMosaicSupplyChangeTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_supply_change_transaction_v1"));
		assertThat(built.get("mosaicId"), equalTo(sweepNewMosaicIdDescriptor().toMap()));
		assertThat(built.get("action"), equalTo(MosaicSupplyChangeAction.parse("decrease")));
		assertThat(built.get("delta"), equalTo(Amount.parse("3")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void mosaicSupplyChangeTransactionV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMosaicSupplyChangeTransactionV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MosaicSupplyChangeTransactionV1Descriptor(sweepNewMosaicIdDescriptor(), "decrease", "3")
				.toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("mosaicId"), equalTo(built.get("mosaicId")));
		assertThat(stringBuilt.get("action"), equalTo(built.get("action")));
		assertThat(stringBuilt.get("delta"), equalTo(built.get("delta")));
	}

	@Test
	void mosaicSupplyChangeTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewMosaicSupplyChangeTransactionV1Descriptor());

		// Act:
		final MosaicSupplyChangeTransactionV1 transaction = (MosaicSupplyChangeTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaicId(), notNullValue());
		assertThat(transaction.getAction(), equalTo(MosaicSupplyChangeAction.parse("decrease")));
		assertThat(transaction.getDelta(), equalTo(Amount.parse("3")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MultisigAccountModificationDescriptor with distinct sample required arguments. */
	private static MultisigAccountModificationDescriptor sweepNewMultisigAccountModificationDescriptor() {
		return new MultisigAccountModificationDescriptor(MultisigAccountModificationType.parse("add_cosignatory"),
				new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303"));
	}

	@Test
	void multisigAccountModificationDescriptor() {
		// Arrange:
		final MultisigAccountModificationDescriptor descriptor = sweepNewMultisigAccountModificationDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("modificationType"), equalTo(MultisigAccountModificationType.parse("add_cosignatory")));
		assertThat(built.get("cosignatoryPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.size(), equalTo(2));
	}

	@Test
	void multisigAccountModificationDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMultisigAccountModificationDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MultisigAccountModificationDescriptor("add_cosignatory",
				"0303030303030303030303030303030303030303030303030303030303030303").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("modificationType"), equalTo(built.get("modificationType")));
		assertThat(stringBuilt.get("cosignatoryPublicKey"), equalTo(built.get("cosignatoryPublicKey")));
	}

	/** Constructs a SizePrefixedMultisigAccountModificationDescriptor with distinct sample required arguments. */
	private static SizePrefixedMultisigAccountModificationDescriptor sweepNewSizePrefixedMultisigAccountModificationDescriptor() {
		return new SizePrefixedMultisigAccountModificationDescriptor(sweepNewMultisigAccountModificationDescriptor());
	}

	@Test
	void sizePrefixedMultisigAccountModificationDescriptor() {
		// Arrange:
		final SizePrefixedMultisigAccountModificationDescriptor descriptor = sweepNewSizePrefixedMultisigAccountModificationDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("modification"), equalTo(sweepNewMultisigAccountModificationDescriptor().toMap()));
		assertThat(built.size(), equalTo(1));
	}

	/** Constructs a MultisigAccountModificationTransactionV1Descriptor with distinct sample required arguments. */
	private static MultisigAccountModificationTransactionV1Descriptor sweepNewMultisigAccountModificationTransactionV1Descriptor() {
		return new MultisigAccountModificationTransactionV1Descriptor();
	}

	@Test
	void multisigAccountModificationTransactionV1Descriptor() {
		// Arrange:
		final MultisigAccountModificationTransactionV1Descriptor descriptor = sweepNewMultisigAccountModificationTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("multisig_account_modification_transaction_v1"));
		assertThat(built.size(), equalTo(1));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: modifications
		assertThat(built.containsKey("modifications"), equalTo(false));
		assertThat(
				sweepNewMultisigAccountModificationTransactionV1Descriptor()
						.modifications((List<SizePrefixedMultisigAccountModificationDescriptor>) null).toMap().containsKey("modifications"),
				equalTo(false));
		final MultisigAccountModificationTransactionV1Descriptor withModifications = sweepNewMultisigAccountModificationTransactionV1Descriptor();
		assertThat(withModifications.modifications(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor())),
				sameInstance(withModifications));
		assertThat(withModifications.toMap().get("modifications"),
				equalTo(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor().toMap())));
		assertThat(
				sweepNewMultisigAccountModificationTransactionV1Descriptor()
						.modifications(sweepNewSizePrefixedMultisigAccountModificationDescriptor()).toMap().get("modifications"),
				equalTo(withModifications.toMap().get("modifications")));
	}

	@Test
	void multisigAccountModificationTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewMultisigAccountModificationTransactionV1Descriptor()
				.modifications(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor())));

		// Act:
		final MultisigAccountModificationTransactionV1 transaction = (MultisigAccountModificationTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getModifications(), notNullValue());

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MultisigAccountModificationTransactionV2Descriptor with distinct sample required arguments. */
	private static MultisigAccountModificationTransactionV2Descriptor sweepNewMultisigAccountModificationTransactionV2Descriptor() {
		return new MultisigAccountModificationTransactionV2Descriptor(2);
	}

	@Test
	void multisigAccountModificationTransactionV2Descriptor() {
		// Arrange:
		final MultisigAccountModificationTransactionV2Descriptor descriptor = sweepNewMultisigAccountModificationTransactionV2Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("multisig_account_modification_transaction_v2"));
		assertThat(built.get("minApprovalDelta"), equalTo(2));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: modifications
		assertThat(built.containsKey("modifications"), equalTo(false));
		assertThat(
				sweepNewMultisigAccountModificationTransactionV2Descriptor()
						.modifications((List<SizePrefixedMultisigAccountModificationDescriptor>) null).toMap().containsKey("modifications"),
				equalTo(false));
		final MultisigAccountModificationTransactionV2Descriptor withModifications = sweepNewMultisigAccountModificationTransactionV2Descriptor();
		assertThat(withModifications.modifications(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor())),
				sameInstance(withModifications));
		assertThat(withModifications.toMap().get("modifications"),
				equalTo(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor().toMap())));
		assertThat(
				sweepNewMultisigAccountModificationTransactionV2Descriptor()
						.modifications(sweepNewSizePrefixedMultisigAccountModificationDescriptor()).toMap().get("modifications"),
				equalTo(withModifications.toMap().get("modifications")));
	}

	@Test
	void multisigAccountModificationTransactionV2DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewMultisigAccountModificationTransactionV2Descriptor()
				.modifications(List.of(sweepNewSizePrefixedMultisigAccountModificationDescriptor())));

		// Act:
		final MultisigAccountModificationTransactionV2 transaction = (MultisigAccountModificationTransactionV2) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMinApprovalDelta(), equalTo(2));
		assertThat(transaction.getModifications(), notNullValue());

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a CosignatureV1BodyDescriptor with distinct sample required arguments. */
	private static CosignatureV1BodyDescriptor sweepNewCosignatureV1BodyDescriptor() {
		return new CosignatureV1BodyDescriptor(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"));
	}

	@Test
	void cosignatureV1BodyDescriptor() {
		// Arrange:
		final CosignatureV1BodyDescriptor descriptor = sweepNewCosignatureV1BodyDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("otherTransactionHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("multisigAccountAddress"),
				equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.size(), equalTo(2));
	}

	@Test
	void cosignatureV1BodyDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewCosignatureV1BodyDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new CosignatureV1BodyDescriptor(
				"0202020202020202020202020202020202020202020202020202020202020202", "TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("otherTransactionHash"), equalTo(built.get("otherTransactionHash")));
		assertThat(stringBuilt.get("multisigAccountAddress"), equalTo(built.get("multisigAccountAddress")));
	}

	/** Constructs a CosignatureV1Descriptor with distinct sample required arguments. */
	private static CosignatureV1Descriptor sweepNewCosignatureV1Descriptor() {
		return new CosignatureV1Descriptor(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"));
	}

	@Test
	void cosignatureV1Descriptor() {
		// Arrange:
		final CosignatureV1Descriptor descriptor = sweepNewCosignatureV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("cosignature_v1"));
		assertThat(built.get("otherTransactionHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("multisigAccountAddress"),
				equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void cosignatureV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewCosignatureV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new CosignatureV1Descriptor(
				"0202020202020202020202020202020202020202020202020202020202020202", "TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("otherTransactionHash"), equalTo(built.get("otherTransactionHash")));
		assertThat(stringBuilt.get("multisigAccountAddress"), equalTo(built.get("multisigAccountAddress")));
	}

	@Test
	void cosignatureV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewCosignatureV1Descriptor());

		// Act:
		final CosignatureV1 transaction = (CosignatureV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getOtherTransactionHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getMultisigAccountAddress(), equalTo(new org.symbol.sdk.nem.models.Address(
				(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")).toString().getBytes(StandardCharsets.UTF_8))));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a SizePrefixedCosignatureV1Descriptor with distinct sample required arguments. */
	private static SizePrefixedCosignatureV1Descriptor sweepNewSizePrefixedCosignatureV1Descriptor() {
		return new SizePrefixedCosignatureV1Descriptor(sweepNewCosignatureV1Descriptor());
	}

	@Test
	void sizePrefixedCosignatureV1Descriptor() {
		// Arrange:
		final SizePrefixedCosignatureV1Descriptor descriptor = sweepNewSizePrefixedCosignatureV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("cosignature"), equalTo(sweepNewCosignatureV1Descriptor().toMap()));
		assertThat(built.size(), equalTo(1));
	}

	/** Constructs a MultisigTransactionV1Descriptor with distinct sample required arguments. */
	private static MultisigTransactionV1Descriptor sweepNewMultisigTransactionV1Descriptor() {
		return new MultisigTransactionV1Descriptor(new NonVerifiableAccountKeyLinkTransactionV1());
	}

	@Test
	void multisigTransactionV1Descriptor() {
		// Arrange:
		final MultisigTransactionV1Descriptor descriptor = sweepNewMultisigTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("multisig_transaction_v1"));
		assertThat(built.get("innerTransaction"), notNullValue());
		assertThat(built.size(), equalTo(2));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: cosignatures
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(sweepNewMultisigTransactionV1Descriptor().cosignatures((List<SizePrefixedCosignatureV1Descriptor>) null).toMap()
				.containsKey("cosignatures"), equalTo(false));
		final MultisigTransactionV1Descriptor withCosignatures = sweepNewMultisigTransactionV1Descriptor();
		assertThat(withCosignatures.cosignatures(List.of(sweepNewSizePrefixedCosignatureV1Descriptor())), sameInstance(withCosignatures));
		assertThat(withCosignatures.toMap().get("cosignatures"), equalTo(List.of(sweepNewSizePrefixedCosignatureV1Descriptor().toMap())));
		assertThat(sweepNewMultisigTransactionV1Descriptor().cosignatures(sweepNewSizePrefixedCosignatureV1Descriptor()).toMap()
				.get("cosignatures"), equalTo(withCosignatures.toMap().get("cosignatures")));
	}

	@Test
	void multisigTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				sweepNewMultisigTransactionV1Descriptor().cosignatures(List.of(sweepNewSizePrefixedCosignatureV1Descriptor())));

		// Act:
		final MultisigTransactionV1 transaction = (MultisigTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getInnerTransaction(), notNullValue());
		assertThat(transaction.getCosignatures(), notNullValue());

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a NamespaceRegistrationTransactionV1Descriptor with distinct sample required arguments. */
	private static NamespaceRegistrationTransactionV1Descriptor sweepNewNamespaceRegistrationTransactionV1Descriptor() {
		return new NamespaceRegistrationTransactionV1Descriptor(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"),
				Amount.parse("2"));
	}

	@Test
	void namespaceRegistrationTransactionV1Descriptor() {
		// Arrange:
		final NamespaceRegistrationTransactionV1Descriptor descriptor = sweepNewNamespaceRegistrationTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("namespace_registration_transaction_v1"));
		assertThat(built.get("rentalFeeSink"), equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.get("rentalFee"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(3));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: name
		assertThat(built.containsKey("name"), equalTo(false));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().name((byte[]) null).toMap().containsKey("name"), equalTo(false));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().name((String) null).toMap().containsKey("name"), equalTo(false));
		final NamespaceRegistrationTransactionV1Descriptor withName = sweepNewNamespaceRegistrationTransactionV1Descriptor();
		assertThat(withName.name("name".getBytes(StandardCharsets.UTF_8)), sameInstance(withName));
		assertThat(withName.toMap().get("name"), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().name("name").toMap().get("name"),
				equalTo(withName.toMap().get("name")));

		// optional field: parentName
		assertThat(built.containsKey("parentName"), equalTo(false));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().parentName((byte[]) null).toMap().containsKey("parentName"),
				equalTo(false));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().parentName((String) null).toMap().containsKey("parentName"),
				equalTo(false));
		final NamespaceRegistrationTransactionV1Descriptor withParentName = sweepNewNamespaceRegistrationTransactionV1Descriptor();
		assertThat(withParentName.parentName("parentName".getBytes(StandardCharsets.UTF_8)), sameInstance(withParentName));
		assertThat(withParentName.toMap().get("parentName"), equalTo("parentName".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewNamespaceRegistrationTransactionV1Descriptor().parentName("parentName").toMap().get("parentName"),
				equalTo(withParentName.toMap().get("parentName")));
	}

	@Test
	void namespaceRegistrationTransactionV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewNamespaceRegistrationTransactionV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new NamespaceRegistrationTransactionV1Descriptor("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C",
				"2").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("rentalFeeSink"), equalTo(built.get("rentalFeeSink")));
		assertThat(stringBuilt.get("rentalFee"), equalTo(built.get("rentalFee")));
	}

	@Test
	void namespaceRegistrationTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewNamespaceRegistrationTransactionV1Descriptor()
				.name("name".getBytes(StandardCharsets.UTF_8)).parentName("parentName".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final NamespaceRegistrationTransactionV1 transaction = (NamespaceRegistrationTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRentalFeeSink(), equalTo(new org.symbol.sdk.nem.models.Address(
				(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")).toString().getBytes(StandardCharsets.UTF_8))));
		assertThat(transaction.getRentalFee(), equalTo(Amount.parse("2")));
		assertThat(transaction.getName(), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(transaction.getParentName(), equalTo("parentName".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MessageDescriptor with distinct sample required arguments. */
	private static MessageDescriptor sweepNewMessageDescriptor() {
		return new MessageDescriptor(MessageType.parse("plain"));
	}

	@Test
	void messageDescriptor() {
		// Arrange:
		final MessageDescriptor descriptor = sweepNewMessageDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("messageType"), equalTo(MessageType.parse("plain")));
		assertThat(built.size(), equalTo(1));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: message
		assertThat(built.containsKey("message"), equalTo(false));
		assertThat(sweepNewMessageDescriptor().message((byte[]) null).toMap().containsKey("message"), equalTo(false));
		assertThat(sweepNewMessageDescriptor().message((String) null).toMap().containsKey("message"), equalTo(false));
		final MessageDescriptor withMessage = sweepNewMessageDescriptor();
		assertThat(withMessage.message("message".getBytes(StandardCharsets.UTF_8)), sameInstance(withMessage));
		assertThat(withMessage.toMap().get("message"), equalTo("message".getBytes(StandardCharsets.UTF_8)));
		assertThat(sweepNewMessageDescriptor().message("message").toMap().get("message"), equalTo(withMessage.toMap().get("message")));
	}

	@Test
	void messageDescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewMessageDescriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new MessageDescriptor("plain").toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("messageType"), equalTo(built.get("messageType")));
	}

	/** Constructs a TransferTransactionV1Descriptor with distinct sample required arguments. */
	private static TransferTransactionV1Descriptor sweepNewTransferTransactionV1Descriptor() {
		return new TransferTransactionV1Descriptor(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"),
				Amount.parse("2"));
	}

	@Test
	void transferTransactionV1Descriptor() {
		// Arrange:
		final TransferTransactionV1Descriptor descriptor = sweepNewTransferTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("transfer_transaction_v1"));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.get("amount"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(3));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: message
		assertThat(built.containsKey("message"), equalTo(false));
		assertThat(sweepNewTransferTransactionV1Descriptor().message((MessageDescriptor) null).toMap().containsKey("message"),
				equalTo(false));
		final TransferTransactionV1Descriptor withMessage = sweepNewTransferTransactionV1Descriptor();
		assertThat(withMessage.message(sweepNewMessageDescriptor()), sameInstance(withMessage));
		assertThat(withMessage.toMap().get("message"), equalTo(sweepNewMessageDescriptor().toMap()));
	}

	@Test
	void transferTransactionV1DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewTransferTransactionV1Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new TransferTransactionV1Descriptor("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C", "2")
				.toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("recipientAddress"), equalTo(built.get("recipientAddress")));
		assertThat(stringBuilt.get("amount"), equalTo(built.get("amount")));
	}

	@Test
	void transferTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				sweepNewTransferTransactionV1Descriptor().message(sweepNewMessageDescriptor()));

		// Act:
		final TransferTransactionV1 transaction = (TransferTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRecipientAddress(), equalTo(new org.symbol.sdk.nem.models.Address(
				(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")).toString().getBytes(StandardCharsets.UTF_8))));
		assertThat(transaction.getAmount(), equalTo(Amount.parse("2")));
		assertThat(transaction.getMessage().isPresent(), equalTo(true));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a TransferTransactionV2Descriptor with distinct sample required arguments. */
	private static TransferTransactionV2Descriptor sweepNewTransferTransactionV2Descriptor() {
		return new TransferTransactionV2Descriptor(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C"),
				Amount.parse("2"));
	}

	@Test
	void transferTransactionV2Descriptor() {
		// Arrange:
		final TransferTransactionV2Descriptor descriptor = sweepNewTransferTransactionV2Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("transfer_transaction_v2"));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")));
		assertThat(built.get("amount"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(3));

		// Act + Assert: each optional fluent setter (typed form, chaining, stored value, overload)

		// optional field: message
		assertThat(built.containsKey("message"), equalTo(false));
		assertThat(sweepNewTransferTransactionV2Descriptor().message((MessageDescriptor) null).toMap().containsKey("message"),
				equalTo(false));
		final TransferTransactionV2Descriptor withMessage = sweepNewTransferTransactionV2Descriptor();
		assertThat(withMessage.message(sweepNewMessageDescriptor()), sameInstance(withMessage));
		assertThat(withMessage.toMap().get("message"), equalTo(sweepNewMessageDescriptor().toMap()));

		// optional field: mosaics
		assertThat(built.containsKey("mosaics"), equalTo(false));
		assertThat(
				sweepNewTransferTransactionV2Descriptor().mosaics((List<SizePrefixedMosaicDescriptor>) null).toMap().containsKey("mosaics"),
				equalTo(false));
		final TransferTransactionV2Descriptor withMosaics = sweepNewTransferTransactionV2Descriptor();
		assertThat(withMosaics.mosaics(List.of(sweepNewSizePrefixedMosaicDescriptor())), sameInstance(withMosaics));
		assertThat(withMosaics.toMap().get("mosaics"), equalTo(List.of(sweepNewSizePrefixedMosaicDescriptor().toMap())));
		assertThat(sweepNewTransferTransactionV2Descriptor().mosaics(sweepNewSizePrefixedMosaicDescriptor()).toMap().get("mosaics"),
				equalTo(withMosaics.toMap().get("mosaics")));
	}

	@Test
	void transferTransactionV2DescriptorStringFormConstructor() {
		// Arrange:
		final Map<String, Object> built = sweepNewTransferTransactionV2Descriptor().toMap();

		// Act:
		final Map<String, Object> stringBuilt = new TransferTransactionV2Descriptor("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C", "2")
				.toMap();

		// Assert: the string-form constructor parses into the same typed values (and no extra/missing keys)
		assertThat(stringBuilt.size(), equalTo(built.size()));
		assertThat(stringBuilt.get("type"), equalTo(built.get("type")));
		assertThat(stringBuilt.get("recipientAddress"), equalTo(built.get("recipientAddress")));
		assertThat(stringBuilt.get("amount"), equalTo(built.get("amount")));
	}

	@Test
	void transferTransactionV2DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor, all optional fields populated via their setters, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(sweepNewTransferTransactionV2Descriptor().message(sweepNewMessageDescriptor())
				.mosaics(List.of(sweepNewSizePrefixedMosaicDescriptor())));

		// Act:
		final TransferTransactionV2 transaction = (TransferTransactionV2) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRecipientAddress(), equalTo(new org.symbol.sdk.nem.models.Address(
				(new org.symbol.sdk.nem.Address("TALICEROONSJCPHC63F52V6FY3SDMSVAEUGHMB7C")).toString().getBytes(StandardCharsets.UTF_8))));
		assertThat(transaction.getAmount(), equalTo(Amount.parse("2")));
		assertThat(transaction.getMessage().isPresent(), equalTo(true));
		assertThat(transaction.getMosaics(), notNullValue());

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(NemTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}
}
