// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import java.nio.charset.StandardCharsets;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Type safe descriptor used to generate a descriptor map for MosaicIdDescriptor.
 *
 * binary layout for a mosaic id
 */
public final class MosaicIdDescriptor implements NemTypedDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MosaicId.
	 *
	 * @param namespaceId namespace id
	 */
	public MosaicIdDescriptor(final NamespaceIdDescriptor namespaceId) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("namespaceId", namespaceId.toMap());
	}

	/**
	 * Sets the name field.
	 *
	 * @param name name
	 * @return This descriptor for chaining.
	 */
	public MosaicIdDescriptor name(final byte[] name) {
		if (null != name)
			rawDescriptor.put("name", name);

		return this;
	}

	/**
	 * Sets the name field.
	 *
	 * @param name name
	 * @return This descriptor for chaining.
	 */
	public MosaicIdDescriptor name(final String name) {
		return name(null == name ? null : name.getBytes(StandardCharsets.UTF_8));
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
