// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.CryptoTypes;

/**
 * Type safe descriptor used to generate a descriptor map for MosaicDefinitionDescriptor.
 *
 * binary layout for a mosaic definition
 */
public final class MosaicDefinitionDescriptor implements NemTypedDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MosaicDefinition.
	 *
	 * @param ownerPublicKey owner public key
	 * @param id mosaic id referenced by this definition
	 * @param description description (field is omitted when null)
	 * @param properties properties (field is omitted when null)
	 * @param levy optional levy that is applied to transfers of this mosaic (field is omitted when null)
	 */
	public MosaicDefinitionDescriptor(final CryptoTypes.PublicKey ownerPublicKey, final MosaicIdDescriptor id, final byte[] description,
			final List<SizePrefixedMosaicPropertyDescriptor> properties, final MosaicLevyDescriptor levy) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("ownerPublicKey", ownerPublicKey);
		rawDescriptor.put("id", id.toMap());

		if (null != description)
			rawDescriptor.put("description", description);

		if (null != properties)
			rawDescriptor.put("properties",
					properties.stream().map(SizePrefixedMosaicPropertyDescriptor::toMap).collect(Collectors.toList()));

		if (null != levy)
			rawDescriptor.put("levy", levy.toMap());
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
