// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CryptoTypes;
import org.symbol.sdk.nem.models.MultisigAccountModificationType;

/**
 * Type safe descriptor used to generate a descriptor map for MultisigAccountModificationDescriptor.
 *
 * binary layout for a multisig account modification
 */
public final class MultisigAccountModificationDescriptor implements NemTypedDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MultisigAccountModification.
	 *
	 * @param modificationType modification type
	 * @param cosignatoryPublicKey cosignatory public key
	 */
	public MultisigAccountModificationDescriptor(final MultisigAccountModificationType modificationType,
			final CryptoTypes.PublicKey cosignatoryPublicKey) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("modificationType", modificationType);
		rawDescriptor.put("cosignatoryPublicKey", cosignatoryPublicKey);
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
