// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Type safe descriptor used to generate a descriptor map for MultisigAccountModificationTransactionV1Descriptor.
 *
 * binary layout for a multisig account modification transaction (V1)
 */
public final class MultisigAccountModificationTransactionV1Descriptor implements NemTransactionDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MultisigAccountModificationTransactionV1.
	 *
	 * @param modifications multisig account modifications (field is omitted when null)
	 */
	public MultisigAccountModificationTransactionV1Descriptor(final List<SizePrefixedMultisigAccountModificationDescriptor> modifications) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("type", "multisig_account_modification_transaction_v1");

		if (null != modifications)
			rawDescriptor.put("modifications",
					modifications.stream().map(SizePrefixedMultisigAccountModificationDescriptor::toMap).collect(Collectors.toList()));
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
