// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

/**
 * Sealed sub-family of {@link NemTypedDescriptor} implemented only by top-level transaction descriptors — the type accepted by the facade
 * typed-descriptor factory methods.
 */
public sealed interface NemTransactionDescriptor extends NemTypedDescriptor
		permits AccountKeyLinkTransactionV1Descriptor, CosignatureV1Descriptor, MosaicDefinitionTransactionV1Descriptor,
		MosaicSupplyChangeTransactionV1Descriptor, MultisigAccountModificationTransactionV1Descriptor,
		MultisigAccountModificationTransactionV2Descriptor, MultisigTransactionV1Descriptor, NamespaceRegistrationTransactionV1Descriptor,
		TransferTransactionV1Descriptor, TransferTransactionV2Descriptor {
}
