// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import org.symbol.sdk.TypedDescriptor;

/**
 * Sealed nem typed-descriptor family implemented by every generated {@code XxxDescriptor} in this package; extends the cross-blockchain
 * {@link org.symbol.sdk.TypedDescriptor} contract.
 */
public sealed interface NemTypedDescriptor extends TypedDescriptor permits CosignatureV1BodyDescriptor, MessageDescriptor,
		MosaicDefinitionDescriptor, MosaicDescriptor, MosaicIdDescriptor, MosaicLevyDescriptor, MosaicPropertyDescriptor,
		MultisigAccountModificationDescriptor, NamespaceIdDescriptor, NemTransactionDescriptor, SizePrefixedCosignatureV1Descriptor,
		SizePrefixedMosaicDescriptor, SizePrefixedMosaicPropertyDescriptor, SizePrefixedMultisigAccountModificationDescriptor {
}
