// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.nem.descriptors;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Type safe descriptor used to generate a descriptor map for SizePrefixedMosaicDescriptor.
 *
 * binary layout for a mosaic with a size prefixed size
 */
public final class SizePrefixedMosaicDescriptor implements NemTypedDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for SizePrefixedMosaic.
	 *
	 * @param mosaic mosaic
	 */
	public SizePrefixedMosaicDescriptor(final MosaicDescriptor mosaic) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("mosaic", mosaic.toMap());
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
