version: '2.1'
services:
  bench:
    image: {{IMAGE_NAME}}
    user: {{USER}}
    working_dir: /catapult-data/workdir
    cap_add:
      - SYS_PTRACE
    command: python3 /catapult-src/scripts/build/runDockerTestsInnerBench.py --exe-path /usr/catapult/bin  --out-dir /catapult-data/logs
    environment:
      - LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps
    volumes:
      - ./catapult-data:/catapult-data
      - ./catapult-src:/catapult-src
