version: '2.1'
services:
  lint:
    image: {{IMAGE_NAME}}
    user: {{USER}}
    working_dir: /catapult-src/client/catapult
    cap_add:
      - SYS_PTRACE
    command: python3 /scripts/runDockerTestsInnerLint.py --out-dir /catapult-data/logs
    volumes:
      - ./catapult-data:/catapult-data
      - '{{CATAPULT_SRC}}:/catapult-src'
      - '{{SCRIPT_PATH}}:/scripts'
      - '{{LINTER_PATH}}:/linters'
