version: '2.4'
services:
  db:
    image: mongo:7.0
    user: {{USER}}
    networks:
      test_net:
        ipv6_address: 2001:3200:{{NETWORK_IP}}::25
    command: mongod --bind_ip_all --dbpath=/mongo --logpath /mongo/mongod.log
    stop_signal: SIGINT
    healthcheck:
      test: /usr/bin/mongosh --eval 'printjson(db.version())'
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 5s
    volumes:
      - ./mongo/{{BUILD_NUMBER}}:/mongo:rw

  test:
    image: {{IMAGE_NAME}}
    user: {{USER}}
    networks:
      test_net:
        ipv6_address: 2001:3200:{{NETWORK_IP}}::20
    environment:
      - GTESTFILTER={{GTESTFILTER}}
      - STRESSCOUNT={{STRESSCOUNT}}
      - LD_LIBRARY_PATH=/usr/catapult/lib:/usr/catapult/deps
    working_dir: /catapult-data/workdir
    cap_add:
      - SYS_PTRACE
    ulimits:
      core: -1
    command: >-
      python3 /scripts/runDockerTestsInnerTest.py
        --compiler-configuration /{{COMPILER_CONFIGURATION}}
        --exe-path /usr/catapult/tests
        --out-dir /catapult-data
        --source-path /catapult-src/client/catapult
        --verbosity {{VERBOSITY}}
    volumes:
      - ./catapult-data:/catapult-data
      - '{{CATAPULT_SRC}}:/catapult-src'
      - '{{SCRIPT_PATH}}:/scripts'
    depends_on:
      db:
        condition: service_healthy

networks:
  test_net:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:{{NETWORK_IP}}::/64
          gateway: 2001:3200:{{NETWORK_IP}}::1
