// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import org.symbol.sdk.Serializer;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public final class AccountRestrictionFlags implements Serializer {
	public static final AccountRestrictionFlags ADDRESS = new AccountRestrictionFlags(1);
	public static final AccountRestrictionFlags MOSAIC_ID = new AccountRestrictionFlags(2);
	public static final AccountRestrictionFlags TRANSACTION_TYPE = new AccountRestrictionFlags(4);
	public static final AccountRestrictionFlags OUTGOING = new AccountRestrictionFlags(16384);
	public static final AccountRestrictionFlags BLOCK = new AccountRestrictionFlags(32768);

	public final int value;

	/**
	 * Creates a new AccountRestrictionFlags.
	 *
	 * @param value Value.
	 */
	public AccountRestrictionFlags(final int value) {
		this.value = value;
	}

	/**
	 * Gets the value field.
	 *
	 * @return The value field.
	 */
	public int getValue() {
		return this.value;
	}

	/**
	 * Creates an instance from its underlying numeric value.
	 *
	 * @param value Value.
	 * @return Instance corresponding to the numeric value.
	 */
	public static AccountRestrictionFlags fromValue(final int value) {
		return new AccountRestrictionFlags(value);
	}

	/**
	 * Parses a raw value into an instance.
	 *
	 * @param rawValue Raw value to parse.
	 * @return Parsed instance.
	 */
	public static AccountRestrictionFlags parse(final Object rawValue) {
		if (rawValue instanceof AccountRestrictionFlags typed)
			return typed;

		if (rawValue instanceof String names) {
			int combined = 0;
			for (final String name : names.split(" "))
				combined |= fromName(name).value;

			return new AccountRestrictionFlags(combined);
		}

		if (rawValue instanceof Number number)
			return new AccountRestrictionFlags(Converter.toInt(number));

		throw new IllegalArgumentException("cannot parse " + rawValue.getClass().getName() + " into AccountRestrictionFlags");
	}

	private static AccountRestrictionFlags fromName(final String name) {
		return switch (name.toLowerCase(Locale.ROOT)) {
			case "address" -> ADDRESS;
			case "mosaic_id" -> MOSAIC_ID;
			case "transaction_type" -> TRANSACTION_TYPE;
			case "outgoing" -> OUTGOING;
			case "block" -> BLOCK;
			default -> throw new IllegalArgumentException("unknown value " + name + " for type AccountRestrictionFlags");
		};
	}

	/**
	 * Checks whether a flag is set.
	 *
	 * @param flag Flag bit(s) to test.
	 * @return true if the flag is set, false otherwise.
	 */
	public boolean has(final int flag) {
		return 0 != (this.value & flag);
	}

	/**
	 * Compares this object with another for equality.
	 *
	 * @param other Object to compare against.
	 * @return true if the objects are equal, false otherwise.
	 */
	@Override
	public boolean equals(final Object other) {
		if (this == other)
			return true;

		if (!(other instanceof AccountRestrictionFlags))
			return false;

		return this.value == ((AccountRestrictionFlags) other).value;
	}

	/**
	 * Computes the hash code of this object.
	 *
	 * @return Hash code of this object.
	 */
	@Override
	public int hashCode() {
		return Integer.hashCode(this.value);
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		return 2;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static AccountRestrictionFlags deserialize(final ByteBuffer buffer) {
		final int value = (int) (new BufferView(buffer).peekInt(2, false));
		return new AccountRestrictionFlags(value);
	}

	/**
	 * Serializes this object to bytes.
	 *
	 * @return Serialized bytes.
	 */
	@Override
	public byte[] serialize() {
		return Converter.intToBytes(this.value, 2);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final int[] values = {
				1, 2, 4, 16384, 32768
		};
		final String[] names = {
				"AccountRestrictionFlags.ADDRESS", "AccountRestrictionFlags.MOSAIC_ID", "AccountRestrictionFlags.TRANSACTION_TYPE",
				"AccountRestrictionFlags.OUTGOING", "AccountRestrictionFlags.BLOCK"
		};
		final List<String> parts = new ArrayList<>();
		for (int i = 0; i < values.length; ++i) {
			if (values[i] == this.value)
				return names[i];

			if (this.has(values[i]))
				parts.add(names[i]);
		}

		return String.join("|", parts);
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	public int toJson() {
		return this.value;
	}
}
