// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class AddressResolutionStatement extends CatbufferType {
	private UnresolvedAddress unresolved;
	private List<AddressResolutionEntry> resolutionEntries;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("unresolved", "pod:UnresolvedAddress"),
			Map.entry("resolutionEntries", "array[AddressResolutionEntry]"));

	/**
	 * Creates a AddressResolutionStatement.
	 */
	public AddressResolutionStatement() {
		this.unresolved = new UnresolvedAddress();
		this.resolutionEntries = new ArrayList<>();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "unresolved" -> this.unresolved = asByteArray(value, UnresolvedAddress.class, UnresolvedAddress::new);
			case "resolutionEntries" -> this.resolutionEntries = asList(value, AddressResolutionEntry.class);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "unresolved" -> this.unresolved;
			case "resolutionEntries" -> this.resolutionEntries;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the unresolved field.
	 *
	 * @return The unresolved field.
	 */
	public UnresolvedAddress getUnresolved() {
		return this.unresolved;
	}

	/**
	 * Sets the unresolved field.
	 *
	 * @param value New unresolved value.
	 */
	public void setUnresolved(final UnresolvedAddress value) {
		this.unresolved = value;
	}

	/**
	 * Gets the resolutionEntries field.
	 *
	 * @return The resolutionEntries field.
	 */
	public List<AddressResolutionEntry> getResolutionEntries() {
		return this.resolutionEntries;
	}

	/**
	 * Sets the resolutionEntries field.
	 *
	 * @param value New resolutionEntries value.
	 */
	public void setResolutionEntries(final List<AddressResolutionEntry> value) {
		this.resolutionEntries = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += this.unresolved.size();
		size += 4;
		size += ArrayHelpers.size(this.resolutionEntries);
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static AddressResolutionStatement deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final AddressResolutionStatement instance = new AddressResolutionStatement();

		final UnresolvedAddress unresolved = UnresolvedAddress.deserialize(cursor);
		cursor.shiftRight(unresolved.size());
		final int resolutionEntriesCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<AddressResolutionEntry> resolutionEntries = ArrayHelpers.readArrayCount(cursor, AddressResolutionEntry::deserialize,
				resolutionEntriesCount);
		cursor.shiftRight(ArrayHelpers.size(resolutionEntries));

		instance.unresolved = unresolved;
		instance.resolutionEntries = resolutionEntries;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static AddressResolutionStatement deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.write(this.unresolved.serialize());
		buffer.writeInt(this.resolutionEntries.size(), 4); // bound: resolution_entries_count
		ArrayHelpers.writeArray(buffer, this.resolutionEntries);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("unresolved: ").append(this.unresolved.toString()).append(", ");
		result.append("resolutionEntries: ")
				.append("[" + (this.resolutionEntries.stream().map(Object::toString).collect(Collectors.joining(","))) + "]").append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("unresolved", this.unresolved.toJson());
		result.put("resolutionEntries", this.resolutionEntries.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		return result;
	}

}
