// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;

import org.symbol.sdk.BaseValue;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public final class Amount extends BaseValue<Amount> {
	public static final int SIZE = 8;
	public static final boolean IS_SIGNED = false;

	/**
	 * Creates a new Amount.
	 *
	 * @param value Value.
	 */
	public Amount(final long value) {
		super(value, SIZE, IS_SIGNED);
	}

	/**
	 * Creates a new Amount.
	 */
	public Amount() {
		this(0L);
	}

	/**
	 * Parses a raw value (Amount, number, or decimal/0x-hex string) into a Amount.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static Amount parse(final Object rawValue) {
		if (rawValue instanceof Amount typed)
			return typed;

		if (rawValue instanceof String string)
			return new Amount(Converter.toLong(string));

		if (rawValue instanceof Number number)
			return new Amount(Converter.toLong(number));

		throw new IllegalArgumentException(
				"cannot convert " + (null == rawValue ? "null" : rawValue.getClass().getName()) + " to an integer value");
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static Amount deserialize(final ByteBuffer buffer) {
		return new Amount(new BufferView(buffer).peekInt(SIZE, IS_SIGNED));
	}
}
