// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;

import org.symbol.sdk.BaseValue;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public final class BlockFeeMultiplier extends BaseValue<BlockFeeMultiplier> {
	public static final int SIZE = 4;
	public static final boolean IS_SIGNED = false;

	/**
	 * Creates a new BlockFeeMultiplier.
	 *
	 * @param value Value.
	 */
	public BlockFeeMultiplier(final long value) {
		super(value, SIZE, IS_SIGNED);
	}

	/**
	 * Creates a new BlockFeeMultiplier.
	 */
	public BlockFeeMultiplier() {
		this(0L);
	}

	/**
	 * Parses a raw value (BlockFeeMultiplier, number, or decimal/0x-hex string) into a BlockFeeMultiplier.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static BlockFeeMultiplier parse(final Object rawValue) {
		if (rawValue instanceof BlockFeeMultiplier typed)
			return typed;

		if (rawValue instanceof String string)
			return new BlockFeeMultiplier(Converter.toLong(string));

		if (rawValue instanceof Number number)
			return new BlockFeeMultiplier(Converter.toLong(number));

		throw new IllegalArgumentException(
				"cannot convert " + (null == rawValue ? "null" : rawValue.getClass().getName()) + " to an integer value");
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static BlockFeeMultiplier deserialize(final ByteBuffer buffer) {
		return new BlockFeeMultiplier(new BufferView(buffer).peekInt(SIZE, IS_SIGNED));
	}
}
