// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public sealed class Block extends CatbufferType permits ImportanceBlockV1, NemesisBlockV1, NormalBlockV1 {
	protected Signature signature;
	protected PublicKey signerPublicKey;
	protected int version;
	protected NetworkType network;
	protected BlockType type;
	protected Height height;
	protected Timestamp timestamp;
	protected Difficulty difficulty;
	protected VrfProof generationHashProof;
	protected Hash256 previousBlockHash;
	protected Hash256 transactionsHash;
	protected Hash256 receiptsHash;
	protected Hash256 stateHash;
	protected Address beneficiaryAddress;
	protected BlockFeeMultiplier feeMultiplier;
	protected final long verifiableEntityHeaderReserved_1 = 0; // reserved field
	protected final long entityBodyReserved_1 = 0; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"), Map.entry("type", "enum:BlockType"),
			Map.entry("height", "pod:Height"), Map.entry("timestamp", "pod:Timestamp"), Map.entry("difficulty", "pod:Difficulty"),
			Map.entry("generationHashProof", "struct:VrfProof"), Map.entry("previousBlockHash", "pod:Hash256"),
			Map.entry("transactionsHash", "pod:Hash256"), Map.entry("receiptsHash", "pod:Hash256"), Map.entry("stateHash", "pod:Hash256"),
			Map.entry("beneficiaryAddress", "pod:Address"), Map.entry("feeMultiplier", "pod:BlockFeeMultiplier"));

	/**
	 * Creates a Block.
	 */
	public Block() {
		this.signature = new Signature();
		this.signerPublicKey = new PublicKey();
		this.version = 0;
		this.network = NetworkType.MAINNET;
		this.type = BlockType.NEMESIS;
		this.height = new Height();
		this.timestamp = new Timestamp();
		this.difficulty = new Difficulty();
		this.generationHashProof = new VrfProof();
		this.previousBlockHash = new Hash256();
		this.transactionsHash = new Hash256();
		this.receiptsHash = new Hash256();
		this.stateHash = new Hash256();
		this.beneficiaryAddress = new Address();
		this.feeMultiplier = new BlockFeeMultiplier();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "signature" -> this.signature = asByteArray(value, Signature.class, Signature::new);
			case "signerPublicKey" -> this.signerPublicKey = asByteArray(value, PublicKey.class, PublicKey::new);
			case "version" -> this.version = asInt(value);
			case "network" -> this.network = (NetworkType) value;
			case "type" -> this.type = (BlockType) value;
			case "height" -> this.height = (Height) value;
			case "timestamp" -> this.timestamp = (Timestamp) value;
			case "difficulty" -> this.difficulty = (Difficulty) value;
			case "generationHashProof" -> this.generationHashProof = (VrfProof) value;
			case "previousBlockHash" -> this.previousBlockHash = asByteArray(value, Hash256.class, Hash256::new);
			case "transactionsHash" -> this.transactionsHash = asByteArray(value, Hash256.class, Hash256::new);
			case "receiptsHash" -> this.receiptsHash = asByteArray(value, Hash256.class, Hash256::new);
			case "stateHash" -> this.stateHash = asByteArray(value, Hash256.class, Hash256::new);
			case "beneficiaryAddress" -> this.beneficiaryAddress = asByteArray(value, Address.class, Address::new);
			case "feeMultiplier" -> this.feeMultiplier = (BlockFeeMultiplier) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "signature" -> this.signature;
			case "signerPublicKey" -> this.signerPublicKey;
			case "version" -> this.version;
			case "network" -> this.network;
			case "type" -> this.type;
			case "height" -> this.height;
			case "timestamp" -> this.timestamp;
			case "difficulty" -> this.difficulty;
			case "generationHashProof" -> this.generationHashProof;
			case "previousBlockHash" -> this.previousBlockHash;
			case "transactionsHash" -> this.transactionsHash;
			case "receiptsHash" -> this.receiptsHash;
			case "stateHash" -> this.stateHash;
			case "beneficiaryAddress" -> this.beneficiaryAddress;
			case "feeMultiplier" -> this.feeMultiplier;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.generationHashProof.sort();
	}

	/**
	 * Gets the signature field.
	 *
	 * @return The signature field.
	 */
	public Signature getSignature() {
		return this.signature;
	}

	/**
	 * Sets the signature field.
	 *
	 * @param value New signature value.
	 */
	public void setSignature(final Signature value) {
		this.signature = value;
	}

	/**
	 * Gets the signerPublicKey field.
	 *
	 * @return The signerPublicKey field.
	 */
	public PublicKey getSignerPublicKey() {
		return this.signerPublicKey;
	}

	/**
	 * Sets the signerPublicKey field.
	 *
	 * @param value New signerPublicKey value.
	 */
	public void setSignerPublicKey(final PublicKey value) {
		this.signerPublicKey = value;
	}

	/**
	 * Gets the version field.
	 *
	 * @return The version field.
	 */
	public int getVersion() {
		return this.version;
	}

	/**
	 * Sets the version field.
	 *
	 * @param value New version value.
	 */
	public void setVersion(final int value) {
		this.version = value;
	}

	/**
	 * Gets the network field.
	 *
	 * @return The network field.
	 */
	public NetworkType getNetwork() {
		return this.network;
	}

	/**
	 * Sets the network field.
	 *
	 * @param value New network value.
	 */
	public void setNetwork(final NetworkType value) {
		this.network = value;
	}

	/**
	 * Gets the type field.
	 *
	 * @return The type field.
	 */
	public BlockType getType() {
		return this.type;
	}

	/**
	 * Sets the type field.
	 *
	 * @param value New type value.
	 */
	public void setType(final BlockType value) {
		this.type = value;
	}

	/**
	 * Gets the height field.
	 *
	 * @return The height field.
	 */
	public Height getHeight() {
		return this.height;
	}

	/**
	 * Sets the height field.
	 *
	 * @param value New height value.
	 */
	public void setHeight(final Height value) {
		this.height = value;
	}

	/**
	 * Gets the timestamp field.
	 *
	 * @return The timestamp field.
	 */
	public Timestamp getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the timestamp field.
	 *
	 * @param value New timestamp value.
	 */
	public void setTimestamp(final Timestamp value) {
		this.timestamp = value;
	}

	/**
	 * Gets the difficulty field.
	 *
	 * @return The difficulty field.
	 */
	public Difficulty getDifficulty() {
		return this.difficulty;
	}

	/**
	 * Sets the difficulty field.
	 *
	 * @param value New difficulty value.
	 */
	public void setDifficulty(final Difficulty value) {
		this.difficulty = value;
	}

	/**
	 * Gets the generationHashProof field.
	 *
	 * @return The generationHashProof field.
	 */
	public VrfProof getGenerationHashProof() {
		return this.generationHashProof;
	}

	/**
	 * Sets the generationHashProof field.
	 *
	 * @param value New generationHashProof value.
	 */
	public void setGenerationHashProof(final VrfProof value) {
		this.generationHashProof = value;
	}

	/**
	 * Gets the previousBlockHash field.
	 *
	 * @return The previousBlockHash field.
	 */
	public Hash256 getPreviousBlockHash() {
		return this.previousBlockHash;
	}

	/**
	 * Sets the previousBlockHash field.
	 *
	 * @param value New previousBlockHash value.
	 */
	public void setPreviousBlockHash(final Hash256 value) {
		this.previousBlockHash = value;
	}

	/**
	 * Gets the transactionsHash field.
	 *
	 * @return The transactionsHash field.
	 */
	public Hash256 getTransactionsHash() {
		return this.transactionsHash;
	}

	/**
	 * Sets the transactionsHash field.
	 *
	 * @param value New transactionsHash value.
	 */
	public void setTransactionsHash(final Hash256 value) {
		this.transactionsHash = value;
	}

	/**
	 * Gets the receiptsHash field.
	 *
	 * @return The receiptsHash field.
	 */
	public Hash256 getReceiptsHash() {
		return this.receiptsHash;
	}

	/**
	 * Sets the receiptsHash field.
	 *
	 * @param value New receiptsHash value.
	 */
	public void setReceiptsHash(final Hash256 value) {
		this.receiptsHash = value;
	}

	/**
	 * Gets the stateHash field.
	 *
	 * @return The stateHash field.
	 */
	public Hash256 getStateHash() {
		return this.stateHash;
	}

	/**
	 * Sets the stateHash field.
	 *
	 * @param value New stateHash value.
	 */
	public void setStateHash(final Hash256 value) {
		this.stateHash = value;
	}

	/**
	 * Gets the beneficiaryAddress field.
	 *
	 * @return The beneficiaryAddress field.
	 */
	public Address getBeneficiaryAddress() {
		return this.beneficiaryAddress;
	}

	/**
	 * Sets the beneficiaryAddress field.
	 *
	 * @param value New beneficiaryAddress value.
	 */
	public void setBeneficiaryAddress(final Address value) {
		this.beneficiaryAddress = value;
	}

	/**
	 * Gets the feeMultiplier field.
	 *
	 * @return The feeMultiplier field.
	 */
	public BlockFeeMultiplier getFeeMultiplier() {
		return this.feeMultiplier;
	}

	/**
	 * Sets the feeMultiplier field.
	 *
	 * @param value New feeMultiplier value.
	 */
	public void setFeeMultiplier(final BlockFeeMultiplier value) {
		this.feeMultiplier = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += 4;
		size += this.signature.size();
		size += this.signerPublicKey.size();
		size += 4;
		size += 1;
		size += this.network.size();
		size += this.type.size();
		size += this.height.size();
		size += this.timestamp.size();
		size += this.difficulty.size();
		size += this.generationHashProof.size();
		size += this.previousBlockHash.size();
		size += this.transactionsHash.size();
		size += this.receiptsHash.size();
		size += this.stateHash.size();
		size += this.beneficiaryAddress.size();
		size += this.feeMultiplier.size();
		return size;
	}

	/**
	 * Deserializes this object into an existing instance from a buffer view.
	 *
	 * @param cursor Buffer view walking-cursor; advanced past the fields read into the instance.
	 * @param instance Destination instance to populate.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	static void deserializeInto(final BufferView cursor, final Block instance) {
		final long size = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		cursor.shrink((int) (size - (4)));
		final long verifiableEntityHeaderReserved_1 = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (0 != verifiableEntityHeaderReserved_1)
			throw new IllegalArgumentException("Invalid value of reserved field (" + verifiableEntityHeaderReserved_1 + ")");

		final Signature signature = Signature.deserialize(cursor);
		cursor.shiftRight(signature.size());
		final PublicKey signerPublicKey = PublicKey.deserialize(cursor);
		cursor.shiftRight(signerPublicKey.size());
		final long entityBodyReserved_1 = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (0 != entityBodyReserved_1)
			throw new IllegalArgumentException("Invalid value of reserved field (" + entityBodyReserved_1 + ")");

		final int version = (int) (cursor.peekInt(1, false));
		cursor.shiftRight(1);
		final NetworkType network = NetworkType.deserialize(cursor);
		cursor.shiftRight(network.size());
		final BlockType type = BlockType.deserialize(cursor);
		cursor.shiftRight(type.size());
		final Height height = Height.deserialize(cursor);
		cursor.shiftRight(height.size());
		final Timestamp timestamp = Timestamp.deserialize(cursor);
		cursor.shiftRight(timestamp.size());
		final Difficulty difficulty = Difficulty.deserialize(cursor);
		cursor.shiftRight(difficulty.size());
		final VrfProof generationHashProof = VrfProof.deserialize(cursor);
		cursor.shiftRight(generationHashProof.size());
		final Hash256 previousBlockHash = Hash256.deserialize(cursor);
		cursor.shiftRight(previousBlockHash.size());
		final Hash256 transactionsHash = Hash256.deserialize(cursor);
		cursor.shiftRight(transactionsHash.size());
		final Hash256 receiptsHash = Hash256.deserialize(cursor);
		cursor.shiftRight(receiptsHash.size());
		final Hash256 stateHash = Hash256.deserialize(cursor);
		cursor.shiftRight(stateHash.size());
		final Address beneficiaryAddress = Address.deserialize(cursor);
		cursor.shiftRight(beneficiaryAddress.size());
		final BlockFeeMultiplier feeMultiplier = BlockFeeMultiplier.deserialize(cursor);
		cursor.shiftRight(feeMultiplier.size());

		instance.signature = signature;
		instance.signerPublicKey = signerPublicKey;
		instance.version = version;
		instance.network = network;
		instance.type = type;
		instance.height = height;
		instance.timestamp = timestamp;
		instance.difficulty = difficulty;
		instance.generationHashProof = generationHashProof;
		instance.previousBlockHash = previousBlockHash;
		instance.transactionsHash = transactionsHash;
		instance.receiptsHash = receiptsHash;
		instance.stateHash = stateHash;
		instance.beneficiaryAddress = beneficiaryAddress;
		instance.feeMultiplier = feeMultiplier;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt((long) this.size(), 4);
		buffer.writeInt(this.verifiableEntityHeaderReserved_1, 4);
		buffer.write(this.signature.serialize());
		buffer.write(this.signerPublicKey.serialize());
		buffer.writeInt(this.entityBodyReserved_1, 4);
		buffer.writeInt(this.version, 1);
		buffer.write(this.network.serialize());
		buffer.write(this.type.serialize());
		buffer.write(this.height.serialize());
		buffer.write(this.timestamp.serialize());
		buffer.write(this.difficulty.serialize());
		buffer.write(this.generationHashProof.serialize());
		buffer.write(this.previousBlockHash.serialize());
		buffer.write(this.transactionsHash.serialize());
		buffer.write(this.receiptsHash.serialize());
		buffer.write(this.stateHash.serialize());
		buffer.write(this.beneficiaryAddress.serialize());
		buffer.write(this.feeMultiplier.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("signature: ").append(this.signature.toString()).append(", ");
		result.append("signerPublicKey: ").append(this.signerPublicKey.toString()).append(", ");
		result.append("version: ").append("0x" + Integer.toHexString(this.version & 0xFF).toUpperCase()).append(", ");
		result.append("network: ").append(this.network.toString()).append(", ");
		result.append("type: ").append(this.type.toString()).append(", ");
		result.append("height: ").append(this.height.toString()).append(", ");
		result.append("timestamp: ").append(this.timestamp.toString()).append(", ");
		result.append("difficulty: ").append(this.difficulty.toString()).append(", ");
		result.append("generationHashProof: ").append(this.generationHashProof.toString()).append(", ");
		result.append("previousBlockHash: ").append(this.previousBlockHash.toString()).append(", ");
		result.append("transactionsHash: ").append(this.transactionsHash.toString()).append(", ");
		result.append("receiptsHash: ").append(this.receiptsHash.toString()).append(", ");
		result.append("stateHash: ").append(this.stateHash.toString()).append(", ");
		result.append("beneficiaryAddress: ").append(this.beneficiaryAddress.toString()).append(", ");
		result.append("feeMultiplier: ").append(this.feeMultiplier.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("signature", this.signature.toJson());
		result.put("signerPublicKey", this.signerPublicKey.toJson());
		result.put("version", this.version);
		result.put("network", this.network.toJson());
		result.put("type", this.type.toJson());
		result.put("height", this.height.toJson());
		result.put("timestamp", this.timestamp.toJson());
		result.put("difficulty", this.difficulty.toJson());
		result.put("generationHashProof", this.generationHashProof.toJson());
		result.put("previousBlockHash", this.previousBlockHash.toJson());
		result.put("transactionsHash", this.transactionsHash.toJson());
		result.put("receiptsHash", this.receiptsHash.toJson());
		result.put("stateHash", this.stateHash.toJson());
		result.put("beneficiaryAddress", this.beneficiaryAddress.toJson());
		result.put("feeMultiplier", this.feeMultiplier.toJson());
		return result;
	}

}
