// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class BlockStatement extends CatbufferType {
	private List<TransactionStatement> transactionStatements;
	private List<AddressResolutionStatement> addressResolutionStatements;
	private List<MosaicResolutionStatement> mosaicResolutionStatements;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("transactionStatements", "array[TransactionStatement]"),
			Map.entry("addressResolutionStatements", "array[AddressResolutionStatement]"),
			Map.entry("mosaicResolutionStatements", "array[MosaicResolutionStatement]"));

	/**
	 * Creates a BlockStatement.
	 */
	public BlockStatement() {
		this.transactionStatements = new ArrayList<>();
		this.addressResolutionStatements = new ArrayList<>();
		this.mosaicResolutionStatements = new ArrayList<>();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "transactionStatements" -> this.transactionStatements = asList(value, TransactionStatement.class);
			case "addressResolutionStatements" -> this.addressResolutionStatements = asList(value, AddressResolutionStatement.class);
			case "mosaicResolutionStatements" -> this.mosaicResolutionStatements = asList(value, MosaicResolutionStatement.class);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "transactionStatements" -> this.transactionStatements;
			case "addressResolutionStatements" -> this.addressResolutionStatements;
			case "mosaicResolutionStatements" -> this.mosaicResolutionStatements;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the transactionStatements field.
	 *
	 * @return The transactionStatements field.
	 */
	public List<TransactionStatement> getTransactionStatements() {
		return this.transactionStatements;
	}

	/**
	 * Sets the transactionStatements field.
	 *
	 * @param value New transactionStatements value.
	 */
	public void setTransactionStatements(final List<TransactionStatement> value) {
		this.transactionStatements = value;
	}

	/**
	 * Gets the addressResolutionStatements field.
	 *
	 * @return The addressResolutionStatements field.
	 */
	public List<AddressResolutionStatement> getAddressResolutionStatements() {
		return this.addressResolutionStatements;
	}

	/**
	 * Sets the addressResolutionStatements field.
	 *
	 * @param value New addressResolutionStatements value.
	 */
	public void setAddressResolutionStatements(final List<AddressResolutionStatement> value) {
		this.addressResolutionStatements = value;
	}

	/**
	 * Gets the mosaicResolutionStatements field.
	 *
	 * @return The mosaicResolutionStatements field.
	 */
	public List<MosaicResolutionStatement> getMosaicResolutionStatements() {
		return this.mosaicResolutionStatements;
	}

	/**
	 * Sets the mosaicResolutionStatements field.
	 *
	 * @param value New mosaicResolutionStatements value.
	 */
	public void setMosaicResolutionStatements(final List<MosaicResolutionStatement> value) {
		this.mosaicResolutionStatements = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += ArrayHelpers.size(this.transactionStatements);
		size += 4;
		size += ArrayHelpers.size(this.addressResolutionStatements);
		size += 4;
		size += ArrayHelpers.size(this.mosaicResolutionStatements);
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static BlockStatement deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final BlockStatement instance = new BlockStatement();

		final int transactionStatementCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<TransactionStatement> transactionStatements = ArrayHelpers.readArrayCount(cursor, TransactionStatement::deserialize,
				transactionStatementCount);
		cursor.shiftRight(ArrayHelpers.size(transactionStatements));
		final int addressResolutionStatementCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<AddressResolutionStatement> addressResolutionStatements = ArrayHelpers.readArrayCount(cursor,
				AddressResolutionStatement::deserialize, addressResolutionStatementCount);
		cursor.shiftRight(ArrayHelpers.size(addressResolutionStatements));
		final int mosaicResolutionStatementCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<MosaicResolutionStatement> mosaicResolutionStatements = ArrayHelpers.readArrayCount(cursor,
				MosaicResolutionStatement::deserialize, mosaicResolutionStatementCount);
		cursor.shiftRight(ArrayHelpers.size(mosaicResolutionStatements));

		instance.transactionStatements = transactionStatements;
		instance.addressResolutionStatements = addressResolutionStatements;
		instance.mosaicResolutionStatements = mosaicResolutionStatements;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static BlockStatement deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.transactionStatements.size(), 4); // bound: transaction_statement_count
		ArrayHelpers.writeArray(buffer, this.transactionStatements);
		buffer.writeInt(this.addressResolutionStatements.size(), 4); // bound: address_resolution_statement_count
		ArrayHelpers.writeArray(buffer, this.addressResolutionStatements);
		buffer.writeInt(this.mosaicResolutionStatements.size(), 4); // bound: mosaic_resolution_statement_count
		ArrayHelpers.writeArray(buffer, this.mosaicResolutionStatements);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("transactionStatements: ")
				.append("[" + (this.transactionStatements.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append("addressResolutionStatements: ")
				.append("[" + (this.addressResolutionStatements.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append("mosaicResolutionStatements: ")
				.append("[" + (this.mosaicResolutionStatements.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("transactionStatements", this.transactionStatements.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		result.put("addressResolutionStatements",
				this.addressResolutionStatements.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		result.put("mosaicResolutionStatements",
				this.mosaicResolutionStatements.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		return result;
	}

}
