// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;
import org.symbol.sdk.utils.Writer;

public final class EmbeddedTransferTransactionV1 extends EmbeddedTransaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.TRANSFER;
	private UnresolvedAddress recipientAddress;
	private List<UnresolvedMosaic> mosaics;
	private byte[] message;
	private final int transferTransactionBodyReserved_1 = 0; // reserved field
	private final long transferTransactionBodyReserved_2 = 0; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signerPublicKey", "pod:PublicKey"),
			Map.entry("network", "enum:NetworkType"), Map.entry("type", "enum:TransactionType"),
			Map.entry("recipientAddress", "pod:UnresolvedAddress"), Map.entry("mosaics", "array[UnresolvedMosaic]"),
			Map.entry("message", "bytes_array"));

	/**
	 * Creates a EmbeddedTransferTransactionV1.
	 */
	public EmbeddedTransferTransactionV1() {
		super();
		this.version = EmbeddedTransferTransactionV1.TRANSACTION_VERSION;
		this.type = EmbeddedTransferTransactionV1.TRANSACTION_TYPE;
		this.recipientAddress = new UnresolvedAddress();
		this.mosaics = new ArrayList<>();
		this.message = new byte[0];
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "recipientAddress" -> this.recipientAddress = asByteArray(value, UnresolvedAddress.class, UnresolvedAddress::new);
			case "mosaics" -> this.mosaics = asList(value, UnresolvedMosaic.class);
			case "message" -> this.message = asBytes(value);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "recipientAddress" -> this.recipientAddress;
			case "mosaics" -> this.mosaics;
			case "message" -> this.message;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.mosaics.sort(Comparator.comparing(UnresolvedMosaic::getMosaicId));
	}

	/**
	 * Gets the recipientAddress field.
	 *
	 * @return The recipientAddress field.
	 */
	public UnresolvedAddress getRecipientAddress() {
		return this.recipientAddress;
	}

	/**
	 * Sets the recipientAddress field.
	 *
	 * @param value New recipientAddress value.
	 */
	public void setRecipientAddress(final UnresolvedAddress value) {
		this.recipientAddress = value;
	}

	/**
	 * Gets the mosaics field.
	 *
	 * @return The mosaics field.
	 */
	public List<UnresolvedMosaic> getMosaics() {
		return this.mosaics;
	}

	/**
	 * Sets the mosaics field.
	 *
	 * @param value New mosaics value.
	 */
	public void setMosaics(final List<UnresolvedMosaic> value) {
		this.mosaics = value;
	}

	/**
	 * Gets the message field.
	 *
	 * @return The message field.
	 */
	public byte[] getMessage() {
		return this.message == null ? null : this.message.clone();
	}

	/**
	 * Sets the message field.
	 *
	 * @param value New message value.
	 */
	public void setMessage(final byte[] value) {
		this.message = value == null ? null : value.clone();
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.recipientAddress.size();
		size += 2;
		size += 1;
		size += 1;
		size += 4;
		size += ArrayHelpers.size(this.mosaics);
		size += this.message.length;
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static EmbeddedTransferTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final EmbeddedTransferTransactionV1 instance = new EmbeddedTransferTransactionV1();

		EmbeddedTransaction.deserializeInto(cursor, instance);
		final UnresolvedAddress recipientAddress = UnresolvedAddress.deserialize(cursor);
		cursor.shiftRight(recipientAddress.size());
		final int messageSize = (int) (cursor.peekInt(2, false));
		cursor.shiftRight(2);
		final int mosaicsCount = (int) (cursor.peekInt(1, false));
		cursor.shiftRight(1);
		final int transferTransactionBodyReserved_1 = (int) (cursor.peekInt(1, false));
		cursor.shiftRight(1);
		if (0 != transferTransactionBodyReserved_1)
			throw new IllegalArgumentException("Invalid value of reserved field (" + transferTransactionBodyReserved_1 + ")");

		final long transferTransactionBodyReserved_2 = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (0 != transferTransactionBodyReserved_2)
			throw new IllegalArgumentException("Invalid value of reserved field (" + transferTransactionBodyReserved_2 + ")");

		final List<UnresolvedMosaic> mosaics = ArrayHelpers.readArrayCount(cursor, UnresolvedMosaic::deserialize, mosaicsCount,
				Comparator.comparing(UnresolvedMosaic::getMosaicId));
		cursor.shiftRight(ArrayHelpers.size(mosaics));
		final byte[] message = cursor.peekBytes(messageSize);
		cursor.shiftRight(messageSize);

		instance.recipientAddress = recipientAddress;
		instance.mosaics = mosaics;
		instance.message = message;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static EmbeddedTransferTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.recipientAddress.serialize());
		buffer.writeInt(this.message.length, 2); // bound: message_size
		buffer.writeInt(this.mosaics.size(), 1); // bound: mosaics_count
		buffer.writeInt(this.transferTransactionBodyReserved_1, 1);
		buffer.writeInt(this.transferTransactionBodyReserved_2, 4);
		ArrayHelpers.writeArray(buffer, this.mosaics, Comparator.comparing(UnresolvedMosaic::getMosaicId));
		buffer.write(this.message);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("recipientAddress: ").append(this.recipientAddress.toString()).append(", ");
		result.append("mosaics: ").append("[" + (this.mosaics.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append("message: ").append("hex(" + (Converter.uint8ToHex(this.message)) + ")").append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("recipientAddress", this.recipientAddress.toJson());
		result.put("mosaics", this.mosaics.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		result.put("message", Converter.uint8ToHex(this.message));
		return result;
	}

}
