// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class EmbeddedAccountOperationRestrictionTransactionV1 extends EmbeddedTransaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.ACCOUNT_OPERATION_RESTRICTION;
	private AccountRestrictionFlags restrictionFlags;
	private List<TransactionType> restrictionAdditions;
	private List<TransactionType> restrictionDeletions;
	private final long accountRestrictionTransactionBodyReserved_1 = 0; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signerPublicKey", "pod:PublicKey"),
			Map.entry("network", "enum:NetworkType"), Map.entry("type", "enum:TransactionType"),
			Map.entry("restrictionFlags", "enum:AccountRestrictionFlags"), Map.entry("restrictionAdditions", "array[TransactionType]"),
			Map.entry("restrictionDeletions", "array[TransactionType]"));

	/**
	 * Creates a EmbeddedAccountOperationRestrictionTransactionV1.
	 */
	public EmbeddedAccountOperationRestrictionTransactionV1() {
		super();
		this.version = EmbeddedAccountOperationRestrictionTransactionV1.TRANSACTION_VERSION;
		this.type = EmbeddedAccountOperationRestrictionTransactionV1.TRANSACTION_TYPE;
		this.restrictionFlags = AccountRestrictionFlags.ADDRESS;
		this.restrictionAdditions = new ArrayList<>();
		this.restrictionDeletions = new ArrayList<>();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "restrictionFlags" -> this.restrictionFlags = (AccountRestrictionFlags) value;
			case "restrictionAdditions" -> this.restrictionAdditions = asList(value, TransactionType.class);
			case "restrictionDeletions" -> this.restrictionDeletions = asList(value, TransactionType.class);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "restrictionFlags" -> this.restrictionFlags;
			case "restrictionAdditions" -> this.restrictionAdditions;
			case "restrictionDeletions" -> this.restrictionDeletions;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the restrictionFlags field.
	 *
	 * @return The restrictionFlags field.
	 */
	public AccountRestrictionFlags getRestrictionFlags() {
		return this.restrictionFlags;
	}

	/**
	 * Sets the restrictionFlags field.
	 *
	 * @param value New restrictionFlags value.
	 */
	public void setRestrictionFlags(final AccountRestrictionFlags value) {
		this.restrictionFlags = value;
	}

	/**
	 * Gets the restrictionAdditions field.
	 *
	 * @return The restrictionAdditions field.
	 */
	public List<TransactionType> getRestrictionAdditions() {
		return this.restrictionAdditions;
	}

	/**
	 * Sets the restrictionAdditions field.
	 *
	 * @param value New restrictionAdditions value.
	 */
	public void setRestrictionAdditions(final List<TransactionType> value) {
		this.restrictionAdditions = value;
	}

	/**
	 * Gets the restrictionDeletions field.
	 *
	 * @return The restrictionDeletions field.
	 */
	public List<TransactionType> getRestrictionDeletions() {
		return this.restrictionDeletions;
	}

	/**
	 * Sets the restrictionDeletions field.
	 *
	 * @param value New restrictionDeletions value.
	 */
	public void setRestrictionDeletions(final List<TransactionType> value) {
		this.restrictionDeletions = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.restrictionFlags.size();
		size += 1;
		size += 1;
		size += 4;
		size += ArrayHelpers.size(this.restrictionAdditions);
		size += ArrayHelpers.size(this.restrictionDeletions);
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static EmbeddedAccountOperationRestrictionTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final EmbeddedAccountOperationRestrictionTransactionV1 instance = new EmbeddedAccountOperationRestrictionTransactionV1();

		EmbeddedTransaction.deserializeInto(cursor, instance);
		final AccountRestrictionFlags restrictionFlags = AccountRestrictionFlags.deserialize(cursor);
		cursor.shiftRight(restrictionFlags.size());
		final int restrictionAdditionsCount = (int) (cursor.peekInt(1, false));
		cursor.shiftRight(1);
		final int restrictionDeletionsCount = (int) (cursor.peekInt(1, false));
		cursor.shiftRight(1);
		final long accountRestrictionTransactionBodyReserved_1 = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (0 != accountRestrictionTransactionBodyReserved_1)
			throw new IllegalArgumentException("Invalid value of reserved field (" + accountRestrictionTransactionBodyReserved_1 + ")");

		final List<TransactionType> restrictionAdditions = ArrayHelpers.readArrayCount(cursor, TransactionType::deserialize,
				restrictionAdditionsCount);
		cursor.shiftRight(ArrayHelpers.size(restrictionAdditions));
		final List<TransactionType> restrictionDeletions = ArrayHelpers.readArrayCount(cursor, TransactionType::deserialize,
				restrictionDeletionsCount);
		cursor.shiftRight(ArrayHelpers.size(restrictionDeletions));

		instance.restrictionFlags = restrictionFlags;
		instance.restrictionAdditions = restrictionAdditions;
		instance.restrictionDeletions = restrictionDeletions;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static EmbeddedAccountOperationRestrictionTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.restrictionFlags.serialize());
		buffer.writeInt(this.restrictionAdditions.size(), 1); // bound: restriction_additions_count
		buffer.writeInt(this.restrictionDeletions.size(), 1); // bound: restriction_deletions_count
		buffer.writeInt(this.accountRestrictionTransactionBodyReserved_1, 4);
		ArrayHelpers.writeArray(buffer, this.restrictionAdditions);
		ArrayHelpers.writeArray(buffer, this.restrictionDeletions);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("restrictionFlags: ").append(this.restrictionFlags.toString()).append(", ");
		result.append("restrictionAdditions: ")
				.append("[" + (this.restrictionAdditions.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append("restrictionDeletions: ")
				.append("[" + (this.restrictionDeletions.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("restrictionFlags", this.restrictionFlags.toJson());
		result.put("restrictionAdditions", this.restrictionAdditions.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		result.put("restrictionDeletions", this.restrictionDeletions.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		return result;
	}

}
