// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import org.symbol.sdk.BaseValue;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public final class FinalizationPoint extends BaseValue<FinalizationPoint> {
	public static final int SIZE = 4;
	public static final boolean IS_SIGNED = false;

	/**
	 * Creates a FinalizationPoint.
	 *
	 * @param value Value.
	 */
	public FinalizationPoint(final long value) {
		super(value, SIZE, IS_SIGNED);
	}

	/**
	 * Creates a FinalizationPoint.
	 */
	public FinalizationPoint() {
		this(0L);
	}

	/**
	 * Parses a raw value (FinalizationPoint, number, or decimal/0x-hex string) into a FinalizationPoint.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static FinalizationPoint parse(final Object rawValue) {
		if (rawValue instanceof FinalizationPoint typed)
			return typed;

		if (rawValue instanceof String string)
			return new FinalizationPoint(Converter.toLong(string));

		if (rawValue instanceof Number number)
			return new FinalizationPoint(Converter.toLong(number));

		throw new IllegalArgumentException(
				"cannot convert " + (null == rawValue ? "null" : rawValue.getClass().getName()) + " to an integer value");
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static FinalizationPoint deserialize(final BufferView view) {
		return new FinalizationPoint(view.peekInt(SIZE, IS_SIGNED));
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static FinalizationPoint deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

}
