// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;

import org.symbol.sdk.BaseValue;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public final class ImportanceHeight extends BaseValue<ImportanceHeight> {
	public static final int SIZE = 8;
	public static final boolean IS_SIGNED = false;

	/**
	 * Creates a new ImportanceHeight.
	 *
	 * @param value Value.
	 */
	public ImportanceHeight(final long value) {
		super(value, SIZE, IS_SIGNED);
	}

	/**
	 * Creates a new ImportanceHeight.
	 */
	public ImportanceHeight() {
		this(0L);
	}

	/**
	 * Parses a raw value (ImportanceHeight, number, or decimal/0x-hex string) into a ImportanceHeight.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static ImportanceHeight parse(final Object rawValue) {
		if (rawValue instanceof ImportanceHeight typed)
			return typed;

		if (rawValue instanceof String string)
			return new ImportanceHeight(Converter.toLong(string));

		if (rawValue instanceof Number number)
			return new ImportanceHeight(Converter.toLong(number));

		throw new IllegalArgumentException(
				"cannot convert " + (null == rawValue ? "null" : rawValue.getClass().getName()) + " to an integer value");
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static ImportanceHeight deserialize(final ByteBuffer buffer) {
		return new ImportanceHeight(new BufferView(buffer).peekInt(SIZE, IS_SIGNED));
	}
}
