// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class InflationReceipt extends Receipt {
	public static final ReceiptType RECEIPT_TYPE = ReceiptType.INFLATION;
	private Mosaic mosaic;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("type", "enum:ReceiptType"),
			Map.entry("mosaic", "struct:Mosaic"));

	/**
	 * Creates a new InflationReceipt.
	 */
	public InflationReceipt() {
		super();
		this.type = InflationReceipt.RECEIPT_TYPE;
		this.mosaic = new Mosaic();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "mosaic" -> this.mosaic = (Mosaic) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "mosaic" -> this.mosaic;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.mosaic.sort();
	}

	/**
	 * Gets the mosaic field.
	 *
	 * @return The mosaic field.
	 */
	public Mosaic getMosaic() {
		return this.mosaic;
	}

	/**
	 * Sets the mosaic field.
	 *
	 * @param value New mosaic value.
	 */
	public void setMosaic(final Mosaic value) {
		this.mosaic = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.mosaic.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static InflationReceipt deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final InflationReceipt instance = new InflationReceipt();

		Receipt.deserializeInto(cursor, instance);
		final Mosaic mosaic = Mosaic.deserialize(cursor.buffer());
		cursor.shiftRight(mosaic.size());

		instance.mosaic = mosaic;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.mosaic.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("mosaic: ").append(this.mosaic.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("mosaic", this.mosaic.toJson());
		return result;
	}
}
