// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Function;

/**
 * Module manifest: every top-level type generated for this blockchain. {@code POD_FACTORIES} maps each pod/enum/flags type name to its
 * generated {@code parse} factory.
 */
public final class Models {
	private Models() {
	}

	/** Maps every generated type name to its {@link Class}. */
	public static final Map<String, Class<?>> MODULE;

	/** Maps every generated pod/enum/flags type name to its {@code parse} descriptor-value factory. */
	public static final Map<String, Function<Object, Object>> POD_FACTORIES;

	static {
		final Map<String, Class<?>> module = new LinkedHashMap<>();
		module.put("AccountAddressRestrictionTransactionV1", AccountAddressRestrictionTransactionV1.class);
		module.put("AccountKeyLinkTransactionV1", AccountKeyLinkTransactionV1.class);
		module.put("AccountMetadataTransactionV1", AccountMetadataTransactionV1.class);
		module.put("AccountMosaicRestrictionTransactionV1", AccountMosaicRestrictionTransactionV1.class);
		module.put("AccountOperationRestrictionTransactionV1", AccountOperationRestrictionTransactionV1.class);
		module.put("AccountRestrictionFlags", AccountRestrictionFlags.class);
		module.put("Address", Address.class);
		module.put("AddressAliasTransactionV1", AddressAliasTransactionV1.class);
		module.put("AddressResolutionEntry", AddressResolutionEntry.class);
		module.put("AddressResolutionStatement", AddressResolutionStatement.class);
		module.put("AggregateBondedTransactionV1", AggregateBondedTransactionV1.class);
		module.put("AggregateBondedTransactionV2", AggregateBondedTransactionV2.class);
		module.put("AggregateBondedTransactionV3", AggregateBondedTransactionV3.class);
		module.put("AggregateCompleteTransactionV1", AggregateCompleteTransactionV1.class);
		module.put("AggregateCompleteTransactionV2", AggregateCompleteTransactionV2.class);
		module.put("AggregateCompleteTransactionV3", AggregateCompleteTransactionV3.class);
		module.put("AliasAction", AliasAction.class);
		module.put("Amount", Amount.class);
		module.put("Block", Block.class);
		module.put("BlockDuration", BlockDuration.class);
		module.put("BlockFactory", BlockFactory.class);
		module.put("BlockFeeMultiplier", BlockFeeMultiplier.class);
		module.put("BlockStatement", BlockStatement.class);
		module.put("BlockType", BlockType.class);
		module.put("Cosignature", Cosignature.class);
		module.put("DetachedCosignature", DetachedCosignature.class);
		module.put("Difficulty", Difficulty.class);
		module.put("EmbeddedAccountAddressRestrictionTransactionV1", EmbeddedAccountAddressRestrictionTransactionV1.class);
		module.put("EmbeddedAccountKeyLinkTransactionV1", EmbeddedAccountKeyLinkTransactionV1.class);
		module.put("EmbeddedAccountMetadataTransactionV1", EmbeddedAccountMetadataTransactionV1.class);
		module.put("EmbeddedAccountMosaicRestrictionTransactionV1", EmbeddedAccountMosaicRestrictionTransactionV1.class);
		module.put("EmbeddedAccountOperationRestrictionTransactionV1", EmbeddedAccountOperationRestrictionTransactionV1.class);
		module.put("EmbeddedAddressAliasTransactionV1", EmbeddedAddressAliasTransactionV1.class);
		module.put("EmbeddedHashLockTransactionV1", EmbeddedHashLockTransactionV1.class);
		module.put("EmbeddedMosaicAddressRestrictionTransactionV1", EmbeddedMosaicAddressRestrictionTransactionV1.class);
		module.put("EmbeddedMosaicAliasTransactionV1", EmbeddedMosaicAliasTransactionV1.class);
		module.put("EmbeddedMosaicDefinitionTransactionV1", EmbeddedMosaicDefinitionTransactionV1.class);
		module.put("EmbeddedMosaicGlobalRestrictionTransactionV1", EmbeddedMosaicGlobalRestrictionTransactionV1.class);
		module.put("EmbeddedMosaicMetadataTransactionV1", EmbeddedMosaicMetadataTransactionV1.class);
		module.put("EmbeddedMosaicSupplyChangeTransactionV1", EmbeddedMosaicSupplyChangeTransactionV1.class);
		module.put("EmbeddedMosaicSupplyRevocationTransactionV1", EmbeddedMosaicSupplyRevocationTransactionV1.class);
		module.put("EmbeddedMultisigAccountModificationTransactionV1", EmbeddedMultisigAccountModificationTransactionV1.class);
		module.put("EmbeddedNamespaceMetadataTransactionV1", EmbeddedNamespaceMetadataTransactionV1.class);
		module.put("EmbeddedNamespaceRegistrationTransactionV1", EmbeddedNamespaceRegistrationTransactionV1.class);
		module.put("EmbeddedNodeKeyLinkTransactionV1", EmbeddedNodeKeyLinkTransactionV1.class);
		module.put("EmbeddedSecretLockTransactionV1", EmbeddedSecretLockTransactionV1.class);
		module.put("EmbeddedSecretProofTransactionV1", EmbeddedSecretProofTransactionV1.class);
		module.put("EmbeddedTransaction", EmbeddedTransaction.class);
		module.put("EmbeddedTransactionFactory", EmbeddedTransactionFactory.class);
		module.put("EmbeddedTransferTransactionV1", EmbeddedTransferTransactionV1.class);
		module.put("EmbeddedVotingKeyLinkTransactionV1", EmbeddedVotingKeyLinkTransactionV1.class);
		module.put("EmbeddedVrfKeyLinkTransactionV1", EmbeddedVrfKeyLinkTransactionV1.class);
		module.put("FinalizationEpoch", FinalizationEpoch.class);
		module.put("FinalizationPoint", FinalizationPoint.class);
		module.put("FinalizationRound", FinalizationRound.class);
		module.put("FinalizedBlockHeader", FinalizedBlockHeader.class);
		module.put("HarvestFeeReceipt", HarvestFeeReceipt.class);
		module.put("Hash256", Hash256.class);
		module.put("Hash512", Hash512.class);
		module.put("HashLockTransactionV1", HashLockTransactionV1.class);
		module.put("Height", Height.class);
		module.put("Importance", Importance.class);
		module.put("ImportanceBlockV1", ImportanceBlockV1.class);
		module.put("ImportanceHeight", ImportanceHeight.class);
		module.put("InflationReceipt", InflationReceipt.class);
		module.put("LinkAction", LinkAction.class);
		module.put("LockHashAlgorithm", LockHashAlgorithm.class);
		module.put("LockHashCompletedFeeReceipt", LockHashCompletedFeeReceipt.class);
		module.put("LockHashCreatedFeeReceipt", LockHashCreatedFeeReceipt.class);
		module.put("LockHashExpiredFeeReceipt", LockHashExpiredFeeReceipt.class);
		module.put("LockSecretCompletedFeeReceipt", LockSecretCompletedFeeReceipt.class);
		module.put("LockSecretCreatedFeeReceipt", LockSecretCreatedFeeReceipt.class);
		module.put("LockSecretExpiredFeeReceipt", LockSecretExpiredFeeReceipt.class);
		module.put("Mosaic", Mosaic.class);
		module.put("MosaicAddressRestrictionTransactionV1", MosaicAddressRestrictionTransactionV1.class);
		module.put("MosaicAliasTransactionV1", MosaicAliasTransactionV1.class);
		module.put("MosaicDefinitionTransactionV1", MosaicDefinitionTransactionV1.class);
		module.put("MosaicExpiredReceipt", MosaicExpiredReceipt.class);
		module.put("MosaicFlags", MosaicFlags.class);
		module.put("MosaicGlobalRestrictionTransactionV1", MosaicGlobalRestrictionTransactionV1.class);
		module.put("MosaicId", MosaicId.class);
		module.put("MosaicMetadataTransactionV1", MosaicMetadataTransactionV1.class);
		module.put("MosaicNonce", MosaicNonce.class);
		module.put("MosaicRentalFeeReceipt", MosaicRentalFeeReceipt.class);
		module.put("MosaicResolutionEntry", MosaicResolutionEntry.class);
		module.put("MosaicResolutionStatement", MosaicResolutionStatement.class);
		module.put("MosaicRestrictionKey", MosaicRestrictionKey.class);
		module.put("MosaicRestrictionType", MosaicRestrictionType.class);
		module.put("MosaicSupplyChangeAction", MosaicSupplyChangeAction.class);
		module.put("MosaicSupplyChangeTransactionV1", MosaicSupplyChangeTransactionV1.class);
		module.put("MosaicSupplyRevocationTransactionV1", MosaicSupplyRevocationTransactionV1.class);
		module.put("MultisigAccountModificationTransactionV1", MultisigAccountModificationTransactionV1.class);
		module.put("NamespaceDeletedReceipt", NamespaceDeletedReceipt.class);
		module.put("NamespaceExpiredReceipt", NamespaceExpiredReceipt.class);
		module.put("NamespaceId", NamespaceId.class);
		module.put("NamespaceMetadataTransactionV1", NamespaceMetadataTransactionV1.class);
		module.put("NamespaceRegistrationTransactionV1", NamespaceRegistrationTransactionV1.class);
		module.put("NamespaceRegistrationType", NamespaceRegistrationType.class);
		module.put("NamespaceRentalFeeReceipt", NamespaceRentalFeeReceipt.class);
		module.put("NemesisBlockV1", NemesisBlockV1.class);
		module.put("NetworkType", NetworkType.class);
		module.put("NodeKeyLinkTransactionV1", NodeKeyLinkTransactionV1.class);
		module.put("NormalBlockV1", NormalBlockV1.class);
		module.put("ProofGamma", ProofGamma.class);
		module.put("ProofScalar", ProofScalar.class);
		module.put("ProofVerificationHash", ProofVerificationHash.class);
		module.put("PublicKey", PublicKey.class);
		module.put("Receipt", Receipt.class);
		module.put("ReceiptFactory", ReceiptFactory.class);
		module.put("ReceiptSource", ReceiptSource.class);
		module.put("ReceiptType", ReceiptType.class);
		module.put("SecretLockTransactionV1", SecretLockTransactionV1.class);
		module.put("SecretProofTransactionV1", SecretProofTransactionV1.class);
		module.put("Signature", Signature.class);
		module.put("Timestamp", Timestamp.class);
		module.put("Transaction", Transaction.class);
		module.put("TransactionFactory", TransactionFactory.class);
		module.put("TransactionStatement", TransactionStatement.class);
		module.put("TransactionType", TransactionType.class);
		module.put("TransferTransactionV1", TransferTransactionV1.class);
		module.put("UnresolvedAddress", UnresolvedAddress.class);
		module.put("UnresolvedMosaic", UnresolvedMosaic.class);
		module.put("UnresolvedMosaicId", UnresolvedMosaicId.class);
		module.put("VotingKeyLinkTransactionV1", VotingKeyLinkTransactionV1.class);
		module.put("VotingPublicKey", VotingPublicKey.class);
		module.put("VrfKeyLinkTransactionV1", VrfKeyLinkTransactionV1.class);
		module.put("VrfProof", VrfProof.class);
		MODULE = Collections.unmodifiableMap(module);

		final Map<String, Function<Object, Object>> factories = new LinkedHashMap<>();
		factories.put("AccountRestrictionFlags", AccountRestrictionFlags::parse);
		factories.put("Address", Address::parse);
		factories.put("AliasAction", AliasAction::parse);
		factories.put("Amount", Amount::parse);
		factories.put("BlockDuration", BlockDuration::parse);
		factories.put("BlockFeeMultiplier", BlockFeeMultiplier::parse);
		factories.put("BlockType", BlockType::parse);
		factories.put("Difficulty", Difficulty::parse);
		factories.put("FinalizationEpoch", FinalizationEpoch::parse);
		factories.put("FinalizationPoint", FinalizationPoint::parse);
		factories.put("Hash256", Hash256::parse);
		factories.put("Hash512", Hash512::parse);
		factories.put("Height", Height::parse);
		factories.put("Importance", Importance::parse);
		factories.put("ImportanceHeight", ImportanceHeight::parse);
		factories.put("LinkAction", LinkAction::parse);
		factories.put("LockHashAlgorithm", LockHashAlgorithm::parse);
		factories.put("MosaicFlags", MosaicFlags::parse);
		factories.put("MosaicId", MosaicId::parse);
		factories.put("MosaicNonce", MosaicNonce::parse);
		factories.put("MosaicRestrictionKey", MosaicRestrictionKey::parse);
		factories.put("MosaicRestrictionType", MosaicRestrictionType::parse);
		factories.put("MosaicSupplyChangeAction", MosaicSupplyChangeAction::parse);
		factories.put("NamespaceId", NamespaceId::parse);
		factories.put("NamespaceRegistrationType", NamespaceRegistrationType::parse);
		factories.put("NetworkType", NetworkType::parse);
		factories.put("ProofGamma", ProofGamma::parse);
		factories.put("ProofScalar", ProofScalar::parse);
		factories.put("ProofVerificationHash", ProofVerificationHash::parse);
		factories.put("PublicKey", PublicKey::parse);
		factories.put("ReceiptType", ReceiptType::parse);
		factories.put("Signature", Signature::parse);
		factories.put("Timestamp", Timestamp::parse);
		factories.put("TransactionType", TransactionType::parse);
		factories.put("UnresolvedAddress", UnresolvedAddress::parse);
		factories.put("UnresolvedMosaicId", UnresolvedMosaicId::parse);
		factories.put("VotingPublicKey", VotingPublicKey::parse);
		POD_FACTORIES = Collections.unmodifiableMap(factories);
	}
}
