// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class MosaicResolutionEntry extends CatbufferType {
	private ReceiptSource source;
	private MosaicId resolvedValue;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("source", "struct:ReceiptSource"),
			Map.entry("resolvedValue", "pod:MosaicId"));

	/**
	 * Creates a new MosaicResolutionEntry.
	 */
	public MosaicResolutionEntry() {
		this.source = new ReceiptSource();
		this.resolvedValue = new MosaicId();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "source" -> this.source = (ReceiptSource) value;
			case "resolvedValue" -> this.resolvedValue = (MosaicId) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "source" -> this.source;
			case "resolvedValue" -> this.resolvedValue;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.source.sort();
	}

	/**
	 * Gets the source field.
	 *
	 * @return The source field.
	 */
	public ReceiptSource getSource() {
		return this.source;
	}

	/**
	 * Sets the source field.
	 *
	 * @param value New source value.
	 */
	public void setSource(final ReceiptSource value) {
		this.source = value;
	}

	/**
	 * Gets the resolvedValue field.
	 *
	 * @return The resolvedValue field.
	 */
	public MosaicId getResolvedValue() {
		return this.resolvedValue;
	}

	/**
	 * Sets the resolvedValue field.
	 *
	 * @param value New resolvedValue value.
	 */
	public void setResolvedValue(final MosaicId value) {
		this.resolvedValue = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += this.source.size();
		size += this.resolvedValue.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicResolutionEntry deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final MosaicResolutionEntry instance = new MosaicResolutionEntry();

		final ReceiptSource source = ReceiptSource.deserialize(cursor.buffer());
		cursor.shiftRight(source.size());
		final MosaicId resolvedValue = MosaicId.deserialize(cursor.buffer());
		cursor.shiftRight(resolvedValue.size());

		instance.source = source;
		instance.resolvedValue = resolvedValue;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.write(this.source.serialize());
		buffer.write(this.resolvedValue.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("source: ").append(this.source.toString()).append(", ");
		result.append("resolvedValue: ").append(this.resolvedValue.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("source", this.source.toJson());
		result.put("resolvedValue", this.resolvedValue.toJson());
		return result;
	}
}
