// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class MosaicSupplyChangeTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_SUPPLY_CHANGE;
	private UnresolvedMosaicId mosaicId;
	private Amount delta;
	private MosaicSupplyChangeAction action;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"),
			Map.entry("type", "enum:TransactionType"), Map.entry("fee", "pod:Amount"), Map.entry("deadline", "pod:Timestamp"),
			Map.entry("mosaicId", "pod:UnresolvedMosaicId"), Map.entry("delta", "pod:Amount"),
			Map.entry("action", "enum:MosaicSupplyChangeAction"));

	/**
	 * Creates a new MosaicSupplyChangeTransactionV1.
	 */
	public MosaicSupplyChangeTransactionV1() {
		super();
		this.version = MosaicSupplyChangeTransactionV1.TRANSACTION_VERSION;
		this.type = MosaicSupplyChangeTransactionV1.TRANSACTION_TYPE;
		this.mosaicId = new UnresolvedMosaicId();
		this.delta = new Amount();
		this.action = MosaicSupplyChangeAction.DECREASE;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "mosaicId" -> this.mosaicId = (UnresolvedMosaicId) value;
			case "delta" -> this.delta = (Amount) value;
			case "action" -> this.action = (MosaicSupplyChangeAction) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "mosaicId" -> this.mosaicId;
			case "delta" -> this.delta;
			case "action" -> this.action;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the mosaicId field.
	 *
	 * @return The mosaicId field.
	 */
	public UnresolvedMosaicId getMosaicId() {
		return this.mosaicId;
	}

	/**
	 * Sets the mosaicId field.
	 *
	 * @param value New mosaicId value.
	 */
	public void setMosaicId(final UnresolvedMosaicId value) {
		this.mosaicId = value;
	}

	/**
	 * Gets the delta field.
	 *
	 * @return The delta field.
	 */
	public Amount getDelta() {
		return this.delta;
	}

	/**
	 * Sets the delta field.
	 *
	 * @param value New delta value.
	 */
	public void setDelta(final Amount value) {
		this.delta = value;
	}

	/**
	 * Gets the action field.
	 *
	 * @return The action field.
	 */
	public MosaicSupplyChangeAction getAction() {
		return this.action;
	}

	/**
	 * Sets the action field.
	 *
	 * @param value New action value.
	 */
	public void setAction(final MosaicSupplyChangeAction value) {
		this.action = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.mosaicId.size();
		size += this.delta.size();
		size += this.action.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicSupplyChangeTransactionV1 deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final MosaicSupplyChangeTransactionV1 instance = new MosaicSupplyChangeTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final UnresolvedMosaicId mosaicId = UnresolvedMosaicId.deserialize(cursor.buffer());
		cursor.shiftRight(mosaicId.size());
		final Amount delta = Amount.deserialize(cursor.buffer());
		cursor.shiftRight(delta.size());
		final MosaicSupplyChangeAction action = MosaicSupplyChangeAction.deserialize(cursor.buffer());
		cursor.shiftRight(action.size());

		instance.mosaicId = mosaicId;
		instance.delta = delta;
		instance.action = action;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.mosaicId.serialize());
		buffer.write(this.delta.serialize());
		buffer.write(this.action.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("mosaicId: ").append(this.mosaicId.toString()).append(", ");
		result.append("delta: ").append(this.delta.toString()).append(", ");
		result.append("action: ").append(this.action.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("mosaicId", this.mosaicId.toJson());
		result.put("delta", this.delta.toJson());
		result.put("action", this.action.toJson());
		return result;
	}
}
