// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class MosaicAddressRestrictionTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_ADDRESS_RESTRICTION;
	private UnresolvedMosaicId mosaicId;
	private long restrictionKey;
	private long previousRestrictionValue;
	private long newRestrictionValue;
	private UnresolvedAddress targetAddress;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"),
			Map.entry("type", "enum:TransactionType"), Map.entry("fee", "pod:Amount"), Map.entry("deadline", "pod:Timestamp"),
			Map.entry("mosaicId", "pod:UnresolvedMosaicId"), Map.entry("targetAddress", "pod:UnresolvedAddress"));

	/**
	 * Creates a MosaicAddressRestrictionTransactionV1.
	 */
	public MosaicAddressRestrictionTransactionV1() {
		super();
		this.version = MosaicAddressRestrictionTransactionV1.TRANSACTION_VERSION;
		this.type = MosaicAddressRestrictionTransactionV1.TRANSACTION_TYPE;
		this.mosaicId = new UnresolvedMosaicId();
		this.restrictionKey = 0L;
		this.previousRestrictionValue = 0L;
		this.newRestrictionValue = 0L;
		this.targetAddress = new UnresolvedAddress();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "mosaicId" -> this.mosaicId = (UnresolvedMosaicId) value;
			case "restrictionKey" -> this.restrictionKey = asLong(value);
			case "previousRestrictionValue" -> this.previousRestrictionValue = asLong(value);
			case "newRestrictionValue" -> this.newRestrictionValue = asLong(value);
			case "targetAddress" -> this.targetAddress = asByteArray(value, UnresolvedAddress.class, UnresolvedAddress::new);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "mosaicId" -> this.mosaicId;
			case "restrictionKey" -> this.restrictionKey;
			case "previousRestrictionValue" -> this.previousRestrictionValue;
			case "newRestrictionValue" -> this.newRestrictionValue;
			case "targetAddress" -> this.targetAddress;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the mosaicId field.
	 *
	 * @return The mosaicId field.
	 */
	public UnresolvedMosaicId getMosaicId() {
		return this.mosaicId;
	}

	/**
	 * Sets the mosaicId field.
	 *
	 * @param value New mosaicId value.
	 */
	public void setMosaicId(final UnresolvedMosaicId value) {
		this.mosaicId = value;
	}

	/**
	 * Gets the restrictionKey field.
	 *
	 * @return The restrictionKey field.
	 */
	public long getRestrictionKey() {
		return this.restrictionKey;
	}

	/**
	 * Sets the restrictionKey field.
	 *
	 * @param value New restrictionKey value.
	 */
	public void setRestrictionKey(final long value) {
		this.restrictionKey = value;
	}

	/**
	 * Gets the previousRestrictionValue field.
	 *
	 * @return The previousRestrictionValue field.
	 */
	public long getPreviousRestrictionValue() {
		return this.previousRestrictionValue;
	}

	/**
	 * Sets the previousRestrictionValue field.
	 *
	 * @param value New previousRestrictionValue value.
	 */
	public void setPreviousRestrictionValue(final long value) {
		this.previousRestrictionValue = value;
	}

	/**
	 * Gets the newRestrictionValue field.
	 *
	 * @return The newRestrictionValue field.
	 */
	public long getNewRestrictionValue() {
		return this.newRestrictionValue;
	}

	/**
	 * Sets the newRestrictionValue field.
	 *
	 * @param value New newRestrictionValue value.
	 */
	public void setNewRestrictionValue(final long value) {
		this.newRestrictionValue = value;
	}

	/**
	 * Gets the targetAddress field.
	 *
	 * @return The targetAddress field.
	 */
	public UnresolvedAddress getTargetAddress() {
		return this.targetAddress;
	}

	/**
	 * Sets the targetAddress field.
	 *
	 * @param value New targetAddress value.
	 */
	public void setTargetAddress(final UnresolvedAddress value) {
		this.targetAddress = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.mosaicId.size();
		size += 8;
		size += 8;
		size += 8;
		size += this.targetAddress.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicAddressRestrictionTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final MosaicAddressRestrictionTransactionV1 instance = new MosaicAddressRestrictionTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final UnresolvedMosaicId mosaicId = UnresolvedMosaicId.deserialize(cursor);
		cursor.shiftRight(mosaicId.size());
		final long restrictionKey = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final long previousRestrictionValue = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final long newRestrictionValue = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final UnresolvedAddress targetAddress = UnresolvedAddress.deserialize(cursor);
		cursor.shiftRight(targetAddress.size());

		instance.mosaicId = mosaicId;
		instance.restrictionKey = restrictionKey;
		instance.previousRestrictionValue = previousRestrictionValue;
		instance.newRestrictionValue = newRestrictionValue;
		instance.targetAddress = targetAddress;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicAddressRestrictionTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.mosaicId.serialize());
		buffer.writeInt(this.restrictionKey, 8);
		buffer.writeInt(this.previousRestrictionValue, 8);
		buffer.writeInt(this.newRestrictionValue, 8);
		buffer.write(this.targetAddress.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("mosaicId: ").append(this.mosaicId.toString()).append(", ");
		result.append("restrictionKey: ").append("0x" + Long.toHexString(this.restrictionKey).toUpperCase()).append(", ");
		result.append("previousRestrictionValue: ").append("0x" + Long.toHexString(this.previousRestrictionValue).toUpperCase())
				.append(", ");
		result.append("newRestrictionValue: ").append("0x" + Long.toHexString(this.newRestrictionValue).toUpperCase()).append(", ");
		result.append("targetAddress: ").append(this.targetAddress.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("mosaicId", this.mosaicId.toJson());
		result.put("restrictionKey", Long.toUnsignedString(this.restrictionKey));
		result.put("previousRestrictionValue", Long.toUnsignedString(this.previousRestrictionValue));
		result.put("newRestrictionValue", Long.toUnsignedString(this.newRestrictionValue));
		result.put("targetAddress", this.targetAddress.toJson());
		return result;
	}

}
