// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class MosaicGlobalRestrictionTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.MOSAIC_GLOBAL_RESTRICTION;
	private UnresolvedMosaicId mosaicId;
	private UnresolvedMosaicId referenceMosaicId;
	private long restrictionKey;
	private long previousRestrictionValue;
	private long newRestrictionValue;
	private MosaicRestrictionType previousRestrictionType;
	private MosaicRestrictionType newRestrictionType;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"),
			Map.entry("type", "enum:TransactionType"), Map.entry("fee", "pod:Amount"), Map.entry("deadline", "pod:Timestamp"),
			Map.entry("mosaicId", "pod:UnresolvedMosaicId"), Map.entry("referenceMosaicId", "pod:UnresolvedMosaicId"),
			Map.entry("previousRestrictionType", "enum:MosaicRestrictionType"),
			Map.entry("newRestrictionType", "enum:MosaicRestrictionType"));

	/**
	 * Creates a MosaicGlobalRestrictionTransactionV1.
	 */
	public MosaicGlobalRestrictionTransactionV1() {
		super();
		this.version = MosaicGlobalRestrictionTransactionV1.TRANSACTION_VERSION;
		this.type = MosaicGlobalRestrictionTransactionV1.TRANSACTION_TYPE;
		this.mosaicId = new UnresolvedMosaicId();
		this.referenceMosaicId = new UnresolvedMosaicId();
		this.restrictionKey = 0L;
		this.previousRestrictionValue = 0L;
		this.newRestrictionValue = 0L;
		this.previousRestrictionType = MosaicRestrictionType.NONE;
		this.newRestrictionType = MosaicRestrictionType.NONE;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "mosaicId" -> this.mosaicId = (UnresolvedMosaicId) value;
			case "referenceMosaicId" -> this.referenceMosaicId = (UnresolvedMosaicId) value;
			case "restrictionKey" -> this.restrictionKey = asLong(value);
			case "previousRestrictionValue" -> this.previousRestrictionValue = asLong(value);
			case "newRestrictionValue" -> this.newRestrictionValue = asLong(value);
			case "previousRestrictionType" -> this.previousRestrictionType = (MosaicRestrictionType) value;
			case "newRestrictionType" -> this.newRestrictionType = (MosaicRestrictionType) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "mosaicId" -> this.mosaicId;
			case "referenceMosaicId" -> this.referenceMosaicId;
			case "restrictionKey" -> this.restrictionKey;
			case "previousRestrictionValue" -> this.previousRestrictionValue;
			case "newRestrictionValue" -> this.newRestrictionValue;
			case "previousRestrictionType" -> this.previousRestrictionType;
			case "newRestrictionType" -> this.newRestrictionType;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the mosaicId field.
	 *
	 * @return The mosaicId field.
	 */
	public UnresolvedMosaicId getMosaicId() {
		return this.mosaicId;
	}

	/**
	 * Sets the mosaicId field.
	 *
	 * @param value New mosaicId value.
	 */
	public void setMosaicId(final UnresolvedMosaicId value) {
		this.mosaicId = value;
	}

	/**
	 * Gets the referenceMosaicId field.
	 *
	 * @return The referenceMosaicId field.
	 */
	public UnresolvedMosaicId getReferenceMosaicId() {
		return this.referenceMosaicId;
	}

	/**
	 * Sets the referenceMosaicId field.
	 *
	 * @param value New referenceMosaicId value.
	 */
	public void setReferenceMosaicId(final UnresolvedMosaicId value) {
		this.referenceMosaicId = value;
	}

	/**
	 * Gets the restrictionKey field.
	 *
	 * @return The restrictionKey field.
	 */
	public long getRestrictionKey() {
		return this.restrictionKey;
	}

	/**
	 * Sets the restrictionKey field.
	 *
	 * @param value New restrictionKey value.
	 */
	public void setRestrictionKey(final long value) {
		this.restrictionKey = value;
	}

	/**
	 * Gets the previousRestrictionValue field.
	 *
	 * @return The previousRestrictionValue field.
	 */
	public long getPreviousRestrictionValue() {
		return this.previousRestrictionValue;
	}

	/**
	 * Sets the previousRestrictionValue field.
	 *
	 * @param value New previousRestrictionValue value.
	 */
	public void setPreviousRestrictionValue(final long value) {
		this.previousRestrictionValue = value;
	}

	/**
	 * Gets the newRestrictionValue field.
	 *
	 * @return The newRestrictionValue field.
	 */
	public long getNewRestrictionValue() {
		return this.newRestrictionValue;
	}

	/**
	 * Sets the newRestrictionValue field.
	 *
	 * @param value New newRestrictionValue value.
	 */
	public void setNewRestrictionValue(final long value) {
		this.newRestrictionValue = value;
	}

	/**
	 * Gets the previousRestrictionType field.
	 *
	 * @return The previousRestrictionType field.
	 */
	public MosaicRestrictionType getPreviousRestrictionType() {
		return this.previousRestrictionType;
	}

	/**
	 * Sets the previousRestrictionType field.
	 *
	 * @param value New previousRestrictionType value.
	 */
	public void setPreviousRestrictionType(final MosaicRestrictionType value) {
		this.previousRestrictionType = value;
	}

	/**
	 * Gets the newRestrictionType field.
	 *
	 * @return The newRestrictionType field.
	 */
	public MosaicRestrictionType getNewRestrictionType() {
		return this.newRestrictionType;
	}

	/**
	 * Sets the newRestrictionType field.
	 *
	 * @param value New newRestrictionType value.
	 */
	public void setNewRestrictionType(final MosaicRestrictionType value) {
		this.newRestrictionType = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.mosaicId.size();
		size += this.referenceMosaicId.size();
		size += 8;
		size += 8;
		size += 8;
		size += this.previousRestrictionType.size();
		size += this.newRestrictionType.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicGlobalRestrictionTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final MosaicGlobalRestrictionTransactionV1 instance = new MosaicGlobalRestrictionTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final UnresolvedMosaicId mosaicId = UnresolvedMosaicId.deserialize(cursor);
		cursor.shiftRight(mosaicId.size());
		final UnresolvedMosaicId referenceMosaicId = UnresolvedMosaicId.deserialize(cursor);
		cursor.shiftRight(referenceMosaicId.size());
		final long restrictionKey = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final long previousRestrictionValue = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final long newRestrictionValue = cursor.peekInt(8, false);
		cursor.shiftRight(8);
		final MosaicRestrictionType previousRestrictionType = MosaicRestrictionType.deserialize(cursor);
		cursor.shiftRight(previousRestrictionType.size());
		final MosaicRestrictionType newRestrictionType = MosaicRestrictionType.deserialize(cursor);
		cursor.shiftRight(newRestrictionType.size());

		instance.mosaicId = mosaicId;
		instance.referenceMosaicId = referenceMosaicId;
		instance.restrictionKey = restrictionKey;
		instance.previousRestrictionValue = previousRestrictionValue;
		instance.newRestrictionValue = newRestrictionValue;
		instance.previousRestrictionType = previousRestrictionType;
		instance.newRestrictionType = newRestrictionType;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicGlobalRestrictionTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.mosaicId.serialize());
		buffer.write(this.referenceMosaicId.serialize());
		buffer.writeInt(this.restrictionKey, 8);
		buffer.writeInt(this.previousRestrictionValue, 8);
		buffer.writeInt(this.newRestrictionValue, 8);
		buffer.write(this.previousRestrictionType.serialize());
		buffer.write(this.newRestrictionType.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("mosaicId: ").append(this.mosaicId.toString()).append(", ");
		result.append("referenceMosaicId: ").append(this.referenceMosaicId.toString()).append(", ");
		result.append("restrictionKey: ").append("0x" + Long.toHexString(this.restrictionKey).toUpperCase()).append(", ");
		result.append("previousRestrictionValue: ").append("0x" + Long.toHexString(this.previousRestrictionValue).toUpperCase())
				.append(", ");
		result.append("newRestrictionValue: ").append("0x" + Long.toHexString(this.newRestrictionValue).toUpperCase()).append(", ");
		result.append("previousRestrictionType: ").append(this.previousRestrictionType.toString()).append(", ");
		result.append("newRestrictionType: ").append(this.newRestrictionType.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("mosaicId", this.mosaicId.toJson());
		result.put("referenceMosaicId", this.referenceMosaicId.toJson());
		result.put("restrictionKey", Long.toUnsignedString(this.restrictionKey));
		result.put("previousRestrictionValue", Long.toUnsignedString(this.previousRestrictionValue));
		result.put("newRestrictionValue", Long.toUnsignedString(this.newRestrictionValue));
		result.put("previousRestrictionType", this.previousRestrictionType.toJson());
		result.put("newRestrictionType", this.newRestrictionType.toJson());
		return result;
	}

}
