// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.Collections;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import org.symbol.sdk.Serializer;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public enum ReceiptType implements Serializer {
	MOSAIC_RENTAL_FEE(4685), NAMESPACE_RENTAL_FEE(4942), HARVEST_FEE(8515), LOCK_HASH_COMPLETED(8776), LOCK_HASH_EXPIRED(
			9032), LOCK_SECRET_COMPLETED(8786), LOCK_SECRET_EXPIRED(9042), LOCK_HASH_CREATED(12616), LOCK_SECRET_CREATED(
					12626), MOSAIC_EXPIRED(16717), NAMESPACE_EXPIRED(16718), NAMESPACE_DELETED(16974), INFLATION(
							20803), TRANSACTION_GROUP(57667), ADDRESS_ALIAS_RESOLUTION(61763), MOSAIC_ALIAS_RESOLUTION(62019);

	private final int value;

	private static final Map<Integer, ReceiptType> VALUE_MAP;
	static {
		final Map<Integer, ReceiptType> map = new HashMap<>();
		for (ReceiptType candidate : values())
			map.put(candidate.value, candidate);
		VALUE_MAP = Collections.unmodifiableMap(map);
	}

	private ReceiptType(final int value) {
		this.value = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		return 2;
	}

	/**
	 * Serializes this object to bytes.
	 *
	 * @return Serialized bytes.
	 */
	@Override
	public byte[] serialize() {
		return Converter.intToBytes(this.value, 2);
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static ReceiptType deserialize(final BufferView view) {
		final int value = (int) (view.peekInt(2, false));
		return fromValue(value);
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static ReceiptType deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Gets the value field.
	 *
	 * @return The value field.
	 */
	public int getValue() {
		return this.value;
	}

	/**
	 * Creates an instance from its underlying numeric value.
	 *
	 * @param value Value.
	 * @return Instance corresponding to the numeric value.
	 */
	public static ReceiptType fromValue(final int value) {
		final ReceiptType result = VALUE_MAP.get(value);
		if (result == null)
			throw new IllegalArgumentException("invalid enum value " + value);

		return result;
	}

	/**
	 * Invokes parse.
	 *
	 * @param rawValue RawValue.
	 * @return Result of the operation.
	 */
	public static ReceiptType parse(final Object rawValue) {
		if (rawValue instanceof ReceiptType typed)
			return typed;

		if (rawValue instanceof String name) {
			try {
				return valueOf(name.toUpperCase(Locale.ROOT));
			} catch (final IllegalArgumentException ex) {
				throw new IllegalArgumentException("unknown value " + name + " for type ReceiptType", ex);
			}
		}

		if (rawValue instanceof Number number)
			return fromValue(Converter.toInt(number));

		throw new IllegalArgumentException("cannot parse " + rawValue.getClass().getName() + " into ReceiptType");
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		return "ReceiptType." + name();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	public int toJson() {
		return this.value;
	}

}
