// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class ReceiptSource extends CatbufferType {
	private long primaryId;
	private long secondaryId;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries();

	/**
	 * Creates a ReceiptSource.
	 */
	public ReceiptSource() {
		this.primaryId = 0L;
		this.secondaryId = 0L;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "primaryId" -> this.primaryId = asLong(value);
			case "secondaryId" -> this.secondaryId = asLong(value);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "primaryId" -> this.primaryId;
			case "secondaryId" -> this.secondaryId;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the primaryId field.
	 *
	 * @return The primaryId field.
	 */
	public long getPrimaryId() {
		return this.primaryId;
	}

	/**
	 * Sets the primaryId field.
	 *
	 * @param value New primaryId value.
	 */
	public void setPrimaryId(final long value) {
		this.primaryId = value;
	}

	/**
	 * Gets the secondaryId field.
	 *
	 * @return The secondaryId field.
	 */
	public long getSecondaryId() {
		return this.secondaryId;
	}

	/**
	 * Sets the secondaryId field.
	 *
	 * @param value New secondaryId value.
	 */
	public void setSecondaryId(final long value) {
		this.secondaryId = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += 4;
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static ReceiptSource deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final ReceiptSource instance = new ReceiptSource();

		final long primaryId = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		final long secondaryId = cursor.peekInt(4, false);
		cursor.shiftRight(4);

		instance.primaryId = primaryId;
		instance.secondaryId = secondaryId;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static ReceiptSource deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.primaryId, 4);
		buffer.writeInt(this.secondaryId, 4);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("primaryId: ").append("0x" + Long.toHexString(this.primaryId).toUpperCase()).append(", ");
		result.append("secondaryId: ").append("0x" + Long.toHexString(this.secondaryId).toUpperCase()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("primaryId", this.primaryId);
		result.put("secondaryId", this.secondaryId);
		return result;
	}

}
