// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class SecretLockTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.SECRET_LOCK;
	private UnresolvedAddress recipientAddress;
	private Hash256 secret;
	private UnresolvedMosaic mosaic;
	private BlockDuration duration;
	private LockHashAlgorithm hashAlgorithm;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"),
			Map.entry("type", "enum:TransactionType"), Map.entry("fee", "pod:Amount"), Map.entry("deadline", "pod:Timestamp"),
			Map.entry("recipientAddress", "pod:UnresolvedAddress"), Map.entry("secret", "pod:Hash256"),
			Map.entry("mosaic", "struct:UnresolvedMosaic"), Map.entry("duration", "pod:BlockDuration"),
			Map.entry("hashAlgorithm", "enum:LockHashAlgorithm"));

	/**
	 * Creates a SecretLockTransactionV1.
	 */
	public SecretLockTransactionV1() {
		super();
		this.version = SecretLockTransactionV1.TRANSACTION_VERSION;
		this.type = SecretLockTransactionV1.TRANSACTION_TYPE;
		this.recipientAddress = new UnresolvedAddress();
		this.secret = new Hash256();
		this.mosaic = new UnresolvedMosaic();
		this.duration = new BlockDuration();
		this.hashAlgorithm = LockHashAlgorithm.SHA3_256;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "recipientAddress" -> this.recipientAddress = asByteArray(value, UnresolvedAddress.class, UnresolvedAddress::new);
			case "secret" -> this.secret = asByteArray(value, Hash256.class, Hash256::new);
			case "mosaic" -> this.mosaic = (UnresolvedMosaic) value;
			case "duration" -> this.duration = (BlockDuration) value;
			case "hashAlgorithm" -> this.hashAlgorithm = (LockHashAlgorithm) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "recipientAddress" -> this.recipientAddress;
			case "secret" -> this.secret;
			case "mosaic" -> this.mosaic;
			case "duration" -> this.duration;
			case "hashAlgorithm" -> this.hashAlgorithm;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.mosaic.sort();
	}

	/**
	 * Gets the recipientAddress field.
	 *
	 * @return The recipientAddress field.
	 */
	public UnresolvedAddress getRecipientAddress() {
		return this.recipientAddress;
	}

	/**
	 * Sets the recipientAddress field.
	 *
	 * @param value New recipientAddress value.
	 */
	public void setRecipientAddress(final UnresolvedAddress value) {
		this.recipientAddress = value;
	}

	/**
	 * Gets the secret field.
	 *
	 * @return The secret field.
	 */
	public Hash256 getSecret() {
		return this.secret;
	}

	/**
	 * Sets the secret field.
	 *
	 * @param value New secret value.
	 */
	public void setSecret(final Hash256 value) {
		this.secret = value;
	}

	/**
	 * Gets the mosaic field.
	 *
	 * @return The mosaic field.
	 */
	public UnresolvedMosaic getMosaic() {
		return this.mosaic;
	}

	/**
	 * Sets the mosaic field.
	 *
	 * @param value New mosaic value.
	 */
	public void setMosaic(final UnresolvedMosaic value) {
		this.mosaic = value;
	}

	/**
	 * Gets the duration field.
	 *
	 * @return The duration field.
	 */
	public BlockDuration getDuration() {
		return this.duration;
	}

	/**
	 * Sets the duration field.
	 *
	 * @param value New duration value.
	 */
	public void setDuration(final BlockDuration value) {
		this.duration = value;
	}

	/**
	 * Gets the hashAlgorithm field.
	 *
	 * @return The hashAlgorithm field.
	 */
	public LockHashAlgorithm getHashAlgorithm() {
		return this.hashAlgorithm;
	}

	/**
	 * Sets the hashAlgorithm field.
	 *
	 * @param value New hashAlgorithm value.
	 */
	public void setHashAlgorithm(final LockHashAlgorithm value) {
		this.hashAlgorithm = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.recipientAddress.size();
		size += this.secret.size();
		size += this.mosaic.size();
		size += this.duration.size();
		size += this.hashAlgorithm.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SecretLockTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final SecretLockTransactionV1 instance = new SecretLockTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final UnresolvedAddress recipientAddress = UnresolvedAddress.deserialize(cursor);
		cursor.shiftRight(recipientAddress.size());
		final Hash256 secret = Hash256.deserialize(cursor);
		cursor.shiftRight(secret.size());
		final UnresolvedMosaic mosaic = UnresolvedMosaic.deserialize(cursor);
		cursor.shiftRight(mosaic.size());
		final BlockDuration duration = BlockDuration.deserialize(cursor);
		cursor.shiftRight(duration.size());
		final LockHashAlgorithm hashAlgorithm = LockHashAlgorithm.deserialize(cursor);
		cursor.shiftRight(hashAlgorithm.size());

		instance.recipientAddress = recipientAddress;
		instance.secret = secret;
		instance.mosaic = mosaic;
		instance.duration = duration;
		instance.hashAlgorithm = hashAlgorithm;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SecretLockTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.recipientAddress.serialize());
		buffer.write(this.secret.serialize());
		buffer.write(this.mosaic.serialize());
		buffer.write(this.duration.serialize());
		buffer.write(this.hashAlgorithm.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("recipientAddress: ").append(this.recipientAddress.toString()).append(", ");
		result.append("secret: ").append(this.secret.toString()).append(", ");
		result.append("mosaic: ").append(this.mosaic.toString()).append(", ");
		result.append("duration: ").append(this.duration.toString()).append(", ");
		result.append("hashAlgorithm: ").append(this.hashAlgorithm.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("recipientAddress", this.recipientAddress.toJson());
		result.put("secret", this.secret.toJson());
		result.put("mosaic", this.mosaic.toJson());
		result.put("duration", this.duration.toJson());
		result.put("hashAlgorithm", this.hashAlgorithm.toJson());
		return result;
	}

}
