// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.nio.ByteBuffer;

import org.symbol.sdk.ByteArray;
import org.symbol.sdk.utils.BufferView;

public final class Signature extends ByteArray {
	public static final int SIZE = 64;

	/**
	 * Creates a new Signature.
	 *
	 * @param bytes Bytes.
	 */
	public Signature(final byte[] bytes) {
		super(bytes, SIZE);
	}

	/**
	 * Creates a new Signature.
	 */
	public Signature() {
		this(new byte[64]);
	}

	/**
	 * Parses a raw value (Signature, hex string, byte array, or SDK ByteArray) into a Signature.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static Signature parse(final Object rawValue) {
		if (rawValue instanceof Signature typed)
			return typed;

		return new Signature(ByteArray.toBytes(rawValue));
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static Signature deserialize(final ByteBuffer buffer) {
		return new Signature(new BufferView(buffer).peekBytes(SIZE));
	}
}
