// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.symbol.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class VrfKeyLinkTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.VRF_KEY_LINK;
	private PublicKey linkedPublicKey;
	private LinkAction linkAction;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("signature", "pod:Signature"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("network", "enum:NetworkType"),
			Map.entry("type", "enum:TransactionType"), Map.entry("fee", "pod:Amount"), Map.entry("deadline", "pod:Timestamp"),
			Map.entry("linkedPublicKey", "pod:PublicKey"), Map.entry("linkAction", "enum:LinkAction"));

	/**
	 * Creates a VrfKeyLinkTransactionV1.
	 */
	public VrfKeyLinkTransactionV1() {
		super();
		this.version = VrfKeyLinkTransactionV1.TRANSACTION_VERSION;
		this.type = VrfKeyLinkTransactionV1.TRANSACTION_TYPE;
		this.linkedPublicKey = new PublicKey();
		this.linkAction = LinkAction.UNLINK;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "linkedPublicKey" -> this.linkedPublicKey = asByteArray(value, PublicKey.class, PublicKey::new);
			case "linkAction" -> this.linkAction = (LinkAction) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "linkedPublicKey" -> this.linkedPublicKey;
			case "linkAction" -> this.linkAction;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the linkedPublicKey field.
	 *
	 * @return The linkedPublicKey field.
	 */
	public PublicKey getLinkedPublicKey() {
		return this.linkedPublicKey;
	}

	/**
	 * Sets the linkedPublicKey field.
	 *
	 * @param value New linkedPublicKey value.
	 */
	public void setLinkedPublicKey(final PublicKey value) {
		this.linkedPublicKey = value;
	}

	/**
	 * Gets the linkAction field.
	 *
	 * @return The linkAction field.
	 */
	public LinkAction getLinkAction() {
		return this.linkAction;
	}

	/**
	 * Sets the linkAction field.
	 *
	 * @param value New linkAction value.
	 */
	public void setLinkAction(final LinkAction value) {
		this.linkAction = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += this.linkedPublicKey.size();
		size += this.linkAction.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static VrfKeyLinkTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final VrfKeyLinkTransactionV1 instance = new VrfKeyLinkTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final PublicKey linkedPublicKey = PublicKey.deserialize(cursor);
		cursor.shiftRight(linkedPublicKey.size());
		final LinkAction linkAction = LinkAction.deserialize(cursor);
		cursor.shiftRight(linkAction.size());

		instance.linkedPublicKey = linkedPublicKey;
		instance.linkAction = linkAction;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static VrfKeyLinkTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.write(this.linkedPublicKey.serialize());
		buffer.write(this.linkAction.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("linkedPublicKey: ").append(this.linkedPublicKey.toString()).append(", ");
		result.append("linkAction: ").append(this.linkAction.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("linkedPublicKey", this.linkedPublicKey.toJson());
		result.put("linkAction", this.linkAction.toJson());
		return result;
	}

}
