// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import org.symbol.sdk.ByteArray;
import org.symbol.sdk.utils.BufferView;

public final class Address extends ByteArray {
	public static final int SIZE = 40;

	/**
	 * Creates a Address.
	 *
	 * @param bytes Bytes.
	 */
	public Address(final byte[] bytes) {
		super(bytes, SIZE);
	}

	/**
	 * Creates a Address.
	 */
	public Address() {
		this(new byte[40]);
	}

	/**
	 * Parses a raw value (Address, hex string, byte array, or SDK ByteArray) into a Address.
	 *
	 * @param rawValue Raw value.
	 * @return Parsed value.
	 */
	public static Address parse(final Object rawValue) {
		if (rawValue instanceof Address typed)
			return typed;

		return new Address(ByteArray.toBytes(rawValue));
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static Address deserialize(final BufferView view) {
		return new Address(view.peekBytes(SIZE));
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static Address deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

}
