// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class CosignatureV1Body extends CatbufferType {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.MULTISIG_COSIGNATURE;
	private Hash256 otherTransactionHash;
	private Address multisigAccountAddress;
	private final long otherTransactionHashOuterSize = 36; // reserved field
	private final long otherTransactionHashSize = 32; // reserved field
	private final long multisigAccountAddressSize = 40; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("otherTransactionHash", "pod:Hash256"),
			Map.entry("multisigAccountAddress", "pod:Address"));

	/**
	 * Creates a new CosignatureV1Body.
	 */
	public CosignatureV1Body() {
		this.otherTransactionHash = new Hash256();
		this.multisigAccountAddress = new Address();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "otherTransactionHash" -> this.otherTransactionHash = asByteArray(value, Hash256.class, Hash256::new);
			case "multisigAccountAddress" -> this.multisigAccountAddress = asByteArray(value, Address.class, Address::new);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "otherTransactionHash" -> this.otherTransactionHash;
			case "multisigAccountAddress" -> this.multisigAccountAddress;
			default -> super.getField(name);
		};
	}

	/**
	 * Gets the otherTransactionHash field.
	 *
	 * @return The otherTransactionHash field.
	 */
	public Hash256 getOtherTransactionHash() {
		return this.otherTransactionHash;
	}

	/**
	 * Sets the otherTransactionHash field.
	 *
	 * @param value New otherTransactionHash value.
	 */
	public void setOtherTransactionHash(final Hash256 value) {
		this.otherTransactionHash = value;
	}

	/**
	 * Gets the multisigAccountAddress field.
	 *
	 * @return The multisigAccountAddress field.
	 */
	public Address getMultisigAccountAddress() {
		return this.multisigAccountAddress;
	}

	/**
	 * Sets the multisigAccountAddress field.
	 *
	 * @param value New multisigAccountAddress value.
	 */
	public void setMultisigAccountAddress(final Address value) {
		this.multisigAccountAddress = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += 4;
		size += this.otherTransactionHash.size();
		size += 4;
		size += this.multisigAccountAddress.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static CosignatureV1Body deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final CosignatureV1Body instance = new CosignatureV1Body();

		final long otherTransactionHashOuterSize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (36 != otherTransactionHashOuterSize)
			throw new IllegalArgumentException("Invalid value of reserved field (" + otherTransactionHashOuterSize + ")");

		final long otherTransactionHashSize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (32 != otherTransactionHashSize)
			throw new IllegalArgumentException("Invalid value of reserved field (" + otherTransactionHashSize + ")");

		final Hash256 otherTransactionHash = Hash256.deserialize(cursor.buffer());
		cursor.shiftRight(otherTransactionHash.size());
		final long multisigAccountAddressSize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (40 != multisigAccountAddressSize)
			throw new IllegalArgumentException("Invalid value of reserved field (" + multisigAccountAddressSize + ")");

		final Address multisigAccountAddress = Address.deserialize(cursor.buffer());
		cursor.shiftRight(multisigAccountAddress.size());

		instance.otherTransactionHash = otherTransactionHash;
		instance.multisigAccountAddress = multisigAccountAddress;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.otherTransactionHashOuterSize, 4);
		buffer.writeInt(this.otherTransactionHashSize, 4);
		buffer.write(this.otherTransactionHash.serialize());
		buffer.writeInt(this.multisigAccountAddressSize, 4);
		buffer.write(this.multisigAccountAddress.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("otherTransactionHash: ").append(this.otherTransactionHash.toString()).append(", ");
		result.append("multisigAccountAddress: ").append(this.multisigAccountAddress.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("otherTransactionHash", this.otherTransactionHash.toJson());
		result.put("multisigAccountAddress", this.multisigAccountAddress.toJson());
		return result;
	}
}
