// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;
import org.symbol.sdk.utils.Writer;

public final class MosaicDefinition extends CatbufferType {
	private PublicKey ownerPublicKey;
	private MosaicId id;
	private byte[] description;
	private List<SizePrefixedMosaicProperty> properties;
	private MosaicLevy levy;
	private final long ownerPublicKeySize = 32; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("ownerPublicKey", "pod:PublicKey"),
			Map.entry("id", "struct:MosaicId"), Map.entry("description", "bytes_array"),
			Map.entry("properties", "array[SizePrefixedMosaicProperty]"), Map.entry("levy", "struct:MosaicLevy"));

	/**
	 * Creates a MosaicDefinition.
	 */
	public MosaicDefinition() {
		this.ownerPublicKey = new PublicKey();
		this.id = new MosaicId();
		this.description = new byte[0];
		this.properties = new ArrayList<>();
		this.levy = null;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "ownerPublicKey" -> this.ownerPublicKey = asByteArray(value, PublicKey.class, PublicKey::new);
			case "id" -> this.id = (MosaicId) value;
			case "description" -> this.description = asBytes(value);
			case "properties" -> this.properties = asList(value, SizePrefixedMosaicProperty.class);
			case "levy" -> this.levy = (MosaicLevy) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "ownerPublicKey" -> this.ownerPublicKey;
			case "id" -> this.id;
			case "description" -> this.description;
			case "properties" -> this.properties;
			case "levy" -> this.levy;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.id.sort();
		if (0L != this.getLevySizeComputed()) {
			this.levy.sort();
		}
	}

	/**
	 * Gets the ownerPublicKey field.
	 *
	 * @return The ownerPublicKey field.
	 */
	public PublicKey getOwnerPublicKey() {
		return this.ownerPublicKey;
	}

	/**
	 * Sets the ownerPublicKey field.
	 *
	 * @param value New ownerPublicKey value.
	 */
	public void setOwnerPublicKey(final PublicKey value) {
		this.ownerPublicKey = value;
	}

	/**
	 * Gets the id field.
	 *
	 * @return The id field.
	 */
	public MosaicId getId() {
		return this.id;
	}

	/**
	 * Sets the id field.
	 *
	 * @param value New id value.
	 */
	public void setId(final MosaicId value) {
		this.id = value;
	}

	/**
	 * Gets the description field.
	 *
	 * @return The description field.
	 */
	public byte[] getDescription() {
		return this.description == null ? null : this.description.clone();
	}

	/**
	 * Sets the description field.
	 *
	 * @param value New description value.
	 */
	public void setDescription(final byte[] value) {
		this.description = value == null ? null : value.clone();
	}

	/**
	 * Gets the properties field.
	 *
	 * @return The properties field.
	 */
	public List<SizePrefixedMosaicProperty> getProperties() {
		return this.properties;
	}

	/**
	 * Sets the properties field.
	 *
	 * @param value New properties value.
	 */
	public void setProperties(final List<SizePrefixedMosaicProperty> value) {
		this.properties = value;
	}

	/**
	 * Gets the levy field.
	 *
	 * @return The levy field.
	 */
	public Optional<MosaicLevy> getLevy() {
		return Optional.ofNullable(this.levy);
	}

	/**
	 * Sets the levy field.
	 *
	 * @param value New levy value.
	 */
	public void setLevy(final MosaicLevy value) {
		this.levy = value;
	}

	/**
	 * Gets the levySize field.
	 *
	 * @return The levySize field.
	 */
	public long getLevySizeComputed() {
		return this.levy != null ? this.levy.size() + 0 : 0;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += this.ownerPublicKey.size();
		size += 4;
		size += this.id.size();
		size += 4;
		size += this.description.length;
		size += 4;
		size += ArrayHelpers.size(this.properties);
		size += 4;
		if (0L != this.getLevySizeComputed()) {
			size += this.levy.size();
		}

		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicDefinition deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final MosaicDefinition instance = new MosaicDefinition();

		final long ownerPublicKeySize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (32 != ownerPublicKeySize)
			throw new IllegalArgumentException("Invalid value of reserved field (" + ownerPublicKeySize + ")");

		final PublicKey ownerPublicKey = PublicKey.deserialize(cursor);
		cursor.shiftRight(ownerPublicKey.size());
		final int idSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final MosaicId id = MosaicId.deserialize(cursor.window(idSize));
		cursor.shiftRight(id.size());
		final int descriptionSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final byte[] description = cursor.peekBytes(descriptionSize);
		cursor.shiftRight(descriptionSize);
		final int propertiesCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<SizePrefixedMosaicProperty> properties = ArrayHelpers.readArrayCount(cursor, SizePrefixedMosaicProperty::deserialize,
				propertiesCount);
		cursor.shiftRight(ArrayHelpers.size(properties));
		final long levySize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		MosaicLevy levy = null;
		if (0L != levySize) {
			levy = MosaicLevy.deserialize(cursor);
			cursor.shiftRight(levy.size());
		}

		instance.ownerPublicKey = ownerPublicKey;
		instance.id = id;
		instance.description = description;
		instance.properties = properties;
		instance.levy = levy;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MosaicDefinition deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.ownerPublicKeySize, 4);
		buffer.write(this.ownerPublicKey.serialize());
		buffer.writeInt(this.id.size(), 4); // bound: id_size
		buffer.write(this.id.serialize());
		buffer.writeInt(this.description.length, 4); // bound: description_size
		buffer.write(this.description);
		buffer.writeInt(this.properties.size(), 4); // bound: properties_count
		ArrayHelpers.writeArray(buffer, this.properties);
		buffer.writeInt(this.getLevySizeComputed(), 4);
		if (0L != this.getLevySizeComputed()) {
			buffer.write(this.levy.serialize());
		}
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("ownerPublicKey: ").append(this.ownerPublicKey.toString()).append(", ");
		result.append("id: ").append(this.id.toString()).append(", ");
		result.append("description: ").append("hex(" + (Converter.uint8ToHex(this.description)) + ")").append(", ");
		result.append("properties: ").append("[" + (this.properties.stream().map(Object::toString).collect(Collectors.joining(","))) + "]")
				.append(", ");
		if (0L != this.getLevySizeComputed()) {
			result.append("levy: ").append(this.levy.toString()).append(", ");
		}

		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("ownerPublicKey", this.ownerPublicKey.toJson());
		result.put("id", this.id.toJson());
		result.put("description", Converter.uint8ToHex(this.description));
		result.put("properties", this.properties.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		if (0L != this.getLevySizeComputed()) {
			result.put("levy", this.levy.toJson());
		}

		return result;
	}

}
