// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.utils.ArrayHelpers;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class MultisigTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.MULTISIG;
	private NonVerifiableTransaction innerTransaction;
	private List<SizePrefixedCosignatureV1> cosignatures;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("type", "enum:TransactionType"),
			Map.entry("network", "enum:NetworkType"), Map.entry("timestamp", "pod:Timestamp"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("signature", "pod:Signature"), Map.entry("fee", "pod:Amount"),
			Map.entry("deadline", "pod:Timestamp"), Map.entry("innerTransaction", "struct:NonVerifiableTransaction"),
			Map.entry("cosignatures", "array[SizePrefixedCosignatureV1]"));

	/**
	 * Creates a MultisigTransactionV1.
	 */
	public MultisigTransactionV1() {
		super();
		this.type = MultisigTransactionV1.TRANSACTION_TYPE;
		this.version = MultisigTransactionV1.TRANSACTION_VERSION;
		this.innerTransaction = new NonVerifiableTransaction();
		this.cosignatures = new ArrayList<>();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "innerTransaction" -> this.innerTransaction = (NonVerifiableTransaction) value;
			case "cosignatures" -> this.cosignatures = asList(value, SizePrefixedCosignatureV1.class);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "innerTransaction" -> this.innerTransaction;
			case "cosignatures" -> this.cosignatures;
			default -> super.getField(name);
		};
	}

	/**
	 * Returns the non-verifiable form of this transaction.
	 *
	 * @return Non-verifiable transaction.
	 */
	@Override
	public NonVerifiableMultisigTransactionV1 toNonVerifiable() {
		final NonVerifiableMultisigTransactionV1 result = new NonVerifiableMultisigTransactionV1();
		result.setField("type", this.type);
		result.setField("version", this.version);
		result.setField("network", this.network);
		result.setField("timestamp", this.timestamp);
		result.setField("signerPublicKey", this.signerPublicKey);
		result.setField("fee", this.fee);
		result.setField("deadline", this.deadline);
		result.setField("innerTransaction", this.innerTransaction);
		return result;
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.innerTransaction.sort();
	}

	/**
	 * Gets the innerTransaction field.
	 *
	 * @return The innerTransaction field.
	 */
	public NonVerifiableTransaction getInnerTransaction() {
		return this.innerTransaction;
	}

	/**
	 * Sets the innerTransaction field.
	 *
	 * @param value New innerTransaction value.
	 */
	public void setInnerTransaction(final NonVerifiableTransaction value) {
		this.innerTransaction = value;
	}

	/**
	 * Gets the cosignatures field.
	 *
	 * @return The cosignatures field.
	 */
	public List<SizePrefixedCosignatureV1> getCosignatures() {
		return this.cosignatures;
	}

	/**
	 * Sets the cosignatures field.
	 *
	 * @param value New cosignatures value.
	 */
	public void setCosignatures(final List<SizePrefixedCosignatureV1> value) {
		this.cosignatures = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += 4;
		size += this.innerTransaction.size();
		size += 4;
		size += ArrayHelpers.size(this.cosignatures);
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MultisigTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final MultisigTransactionV1 instance = new MultisigTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final int innerTransactionSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final NonVerifiableTransaction innerTransaction = NonVerifiableTransactionFactory.deserialize(cursor.window(innerTransactionSize));
		cursor.shiftRight(innerTransaction.size());
		final int cosignaturesCount = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final List<SizePrefixedCosignatureV1> cosignatures = ArrayHelpers.readArrayCount(cursor, SizePrefixedCosignatureV1::deserialize,
				cosignaturesCount);
		cursor.shiftRight(ArrayHelpers.size(cosignatures));

		instance.innerTransaction = innerTransaction;
		instance.cosignatures = cosignatures;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static MultisigTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.writeInt(this.innerTransaction.size(), 4); // bound: inner_transaction_size
		buffer.write(this.innerTransaction.serialize());
		buffer.writeInt(this.cosignatures.size(), 4); // bound: cosignatures_count
		ArrayHelpers.writeArray(buffer, this.cosignatures);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("innerTransaction: ").append(this.innerTransaction.toString()).append(", ");
		result.append("cosignatures: ")
				.append("[" + (this.cosignatures.stream().map(Object::toString).collect(Collectors.joining(","))) + "]").append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("innerTransaction", this.innerTransaction.toJson());
		result.put("cosignatures", this.cosignatures.stream().map(e -> (Object) e.toJson()).collect(Collectors.toList()));
		return result;
	}

}
