// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;
import org.symbol.sdk.utils.Writer;

public final class NamespaceRegistrationTransactionV1 extends Transaction {
	public static final int TRANSACTION_VERSION = 1;
	public static final TransactionType TRANSACTION_TYPE = TransactionType.NAMESPACE_REGISTRATION;
	private Address rentalFeeSink;
	private Amount rentalFee;
	private byte[] name;
	private byte[] parentName;
	private final long rentalFeeSinkSize = 40; // reserved field
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("type", "enum:TransactionType"),
			Map.entry("network", "enum:NetworkType"), Map.entry("timestamp", "pod:Timestamp"),
			Map.entry("signerPublicKey", "pod:PublicKey"), Map.entry("signature", "pod:Signature"), Map.entry("fee", "pod:Amount"),
			Map.entry("deadline", "pod:Timestamp"), Map.entry("rentalFeeSink", "pod:Address"), Map.entry("rentalFee", "pod:Amount"),
			Map.entry("name", "bytes_array"), Map.entry("parentName", "bytes_array"));

	/**
	 * Creates a NamespaceRegistrationTransactionV1.
	 */
	public NamespaceRegistrationTransactionV1() {
		super();
		this.type = NamespaceRegistrationTransactionV1.TRANSACTION_TYPE;
		this.version = NamespaceRegistrationTransactionV1.TRANSACTION_VERSION;
		this.rentalFeeSink = new Address();
		this.rentalFee = new Amount();
		this.name = new byte[0];
		this.parentName = null;
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "rentalFeeSink" -> this.rentalFeeSink = asByteArray(value, Address.class, Address::new);
			case "rentalFee" -> this.rentalFee = (Amount) value;
			case "name" -> this.name = asBytes(value);
			case "parentName" -> this.parentName = asBytes(value);
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "rentalFeeSink" -> this.rentalFeeSink;
			case "rentalFee" -> this.rentalFee;
			case "name" -> this.name;
			case "parentName" -> this.parentName;
			default -> super.getField(name);
		};
	}

	/**
	 * Returns the non-verifiable form of this transaction.
	 *
	 * @return Non-verifiable transaction.
	 */
	@Override
	public NonVerifiableNamespaceRegistrationTransactionV1 toNonVerifiable() {
		final NonVerifiableNamespaceRegistrationTransactionV1 result = new NonVerifiableNamespaceRegistrationTransactionV1();
		result.setField("type", this.type);
		result.setField("version", this.version);
		result.setField("network", this.network);
		result.setField("timestamp", this.timestamp);
		result.setField("signerPublicKey", this.signerPublicKey);
		result.setField("fee", this.fee);
		result.setField("deadline", this.deadline);
		result.setField("rentalFeeSink", this.rentalFeeSink);
		result.setField("rentalFee", this.rentalFee);
		result.setField("name", this.name);
		result.setField("parentName", this.parentName);
		return result;
	}

	/**
	 * Gets the rentalFeeSink field.
	 *
	 * @return The rentalFeeSink field.
	 */
	public Address getRentalFeeSink() {
		return this.rentalFeeSink;
	}

	/**
	 * Sets the rentalFeeSink field.
	 *
	 * @param value New rentalFeeSink value.
	 */
	public void setRentalFeeSink(final Address value) {
		this.rentalFeeSink = value;
	}

	/**
	 * Gets the rentalFee field.
	 *
	 * @return The rentalFee field.
	 */
	public Amount getRentalFee() {
		return this.rentalFee;
	}

	/**
	 * Sets the rentalFee field.
	 *
	 * @param value New rentalFee value.
	 */
	public void setRentalFee(final Amount value) {
		this.rentalFee = value;
	}

	/**
	 * Gets the name field.
	 *
	 * @return The name field.
	 */
	public byte[] getName() {
		return this.name == null ? null : this.name.clone();
	}

	/**
	 * Sets the name field.
	 *
	 * @param value New name value.
	 */
	public void setName(final byte[] value) {
		this.name = value == null ? null : value.clone();
	}

	/**
	 * Gets the parentName field.
	 *
	 * @return The parentName field.
	 */
	public byte[] getParentName() {
		return this.parentName == null ? null : this.parentName.clone();
	}

	/**
	 * Sets the parentName field.
	 *
	 * @param value New parentName value.
	 */
	public void setParentName(final byte[] value) {
		this.parentName = value == null ? null : value.clone();
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += super.size();
		size += 4;
		size += this.rentalFeeSink.size();
		size += this.rentalFee.size();
		size += 4;
		size += this.name.length;
		size += 4;
		if (this.parentName != null) {
			size += this.parentName.length;
		}

		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static NamespaceRegistrationTransactionV1 deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final NamespaceRegistrationTransactionV1 instance = new NamespaceRegistrationTransactionV1();

		Transaction.deserializeInto(cursor, instance);
		final long rentalFeeSinkSize = cursor.peekInt(4, false);
		cursor.shiftRight(4);
		if (40 != rentalFeeSinkSize)
			throw new IllegalArgumentException("Invalid value of reserved field (" + rentalFeeSinkSize + ")");

		final Address rentalFeeSink = Address.deserialize(cursor);
		cursor.shiftRight(rentalFeeSink.size());
		final Amount rentalFee = Amount.deserialize(cursor);
		cursor.shiftRight(rentalFee.size());
		final int nameSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final byte[] name = cursor.peekBytes(nameSize);
		cursor.shiftRight(nameSize);
		final int parentNameSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		byte[] parentName = null;
		if (-1 != parentNameSize) {
			parentName = cursor.peekBytes(parentNameSize);
			cursor.shiftRight(parentNameSize);
		}

		instance.rentalFeeSink = rentalFeeSink;
		instance.rentalFee = rentalFee;
		instance.name = name;
		instance.parentName = parentName;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static NamespaceRegistrationTransactionV1 deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		super.serializeInto(buffer);
		buffer.writeInt(this.rentalFeeSinkSize, 4);
		buffer.write(this.rentalFeeSink.serialize());
		buffer.write(this.rentalFee.serialize());
		buffer.writeInt(this.name.length, 4); // bound: name_size
		buffer.write(this.name);
		buffer.writeInt((this.parentName != null ? this.parentName.length : -1), 4); // bound: parent_name_size
		if (this.parentName != null) {
			buffer.write(this.parentName);
		}
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append(super.toString());
		result.append("rentalFeeSink: ").append(this.rentalFeeSink.toString()).append(", ");
		result.append("rentalFee: ").append(this.rentalFee.toString()).append(", ");
		result.append("name: ").append("hex(" + (Converter.uint8ToHex(this.name)) + ")").append(", ");
		if (this.parentName != null) {
			result.append("parentName: ").append("hex(" + (Converter.uint8ToHex(this.parentName)) + ")").append(", ");
		}

		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.putAll(super.toJson());
		result.put("rentalFeeSink", this.rentalFeeSink.toJson());
		result.put("rentalFee", this.rentalFee.toJson());
		result.put("name", Converter.uint8ToHex(this.name));
		if (this.parentName != null) {
			result.put("parentName", Converter.uint8ToHex(this.parentName));
		}

		return result;
	}

}
