// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.nio.ByteBuffer;
import java.util.Collections;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;

import org.symbol.sdk.Serializer;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Converter;

public enum NetworkType implements Serializer {
	MAINNET(104), TESTNET(152);

	private final int value;

	private static final Map<Integer, NetworkType> VALUE_MAP;
	static {
		final Map<Integer, NetworkType> map = new HashMap<>();
		for (NetworkType candidate : values())
			map.put(candidate.value, candidate);
		VALUE_MAP = Collections.unmodifiableMap(map);
	}

	private NetworkType(final int value) {
		this.value = value;
	}

	/**
	 * Gets the value field.
	 *
	 * @return The value field.
	 */
	public int getValue() {
		return this.value;
	}

	/**
	 * Creates an instance from its underlying numeric value.
	 *
	 * @param value Value.
	 * @return Instance corresponding to the numeric value.
	 */
	public static NetworkType fromValue(final int value) {
		final NetworkType result = VALUE_MAP.get(value);
		if (null == result)
			throw new IllegalArgumentException("invalid enum value " + value);

		return result;
	}

	/**
	 * Parses a raw value into an instance.
	 *
	 * @param rawValue Raw value to parse.
	 * @return Parsed instance.
	 */
	public static NetworkType parse(final Object rawValue) {
		if (rawValue instanceof NetworkType typed)
			return typed;

		if (rawValue instanceof String name) {
			try {
				return valueOf(name.toUpperCase(Locale.ROOT));
			} catch (final IllegalArgumentException ex) {
				throw new IllegalArgumentException("unknown value " + name + " for type NetworkType", ex);
			}
		}

		if (rawValue instanceof Number number)
			return fromValue(Converter.toInt(number));

		throw new IllegalArgumentException("cannot parse " + rawValue.getClass().getName() + " into NetworkType");
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		return 1;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static NetworkType deserialize(final ByteBuffer buffer) {
		final int value = (int) (new BufferView(buffer).peekInt(1, false));
		return fromValue(value);
	}

	/**
	 * Serializes this object to bytes.
	 *
	 * @return Serialized bytes.
	 */
	@Override
	public byte[] serialize() {
		return Converter.intToBytes(this.value, 1);
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		return "NetworkType." + name();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	public int toJson() {
		return this.value;
	}
}
