// Auto-generated by sdk/java/generator. Do not edit directly.
// Run sdk/java/scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class SizePrefixedMosaicProperty extends CatbufferType {
	private MosaicProperty property;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("property", "struct:MosaicProperty"));

	/**
	 * Creates a new SizePrefixedMosaicProperty.
	 */
	public SizePrefixedMosaicProperty() {
		this.property = new MosaicProperty();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "property" -> this.property = (MosaicProperty) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "property" -> this.property;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.property.sort();
	}

	/**
	 * Gets the property field.
	 *
	 * @return The property field.
	 */
	public MosaicProperty getProperty() {
		return this.property;
	}

	/**
	 * Sets the property field.
	 *
	 * @param value New property value.
	 */
	public void setProperty(final MosaicProperty value) {
		this.property = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += this.property.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SizePrefixedMosaicProperty deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final SizePrefixedMosaicProperty instance = new SizePrefixedMosaicProperty();

		final int propertySize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final MosaicProperty property = MosaicProperty.deserialize(cursor.window(propertySize).buffer());
		cursor.shiftRight(property.size());

		instance.property = property;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.property.size(), 4); // bound: property_size
		buffer.write(this.property.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("property: ").append(this.property.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("property", this.property.toJson());
		return result;
	}
}
