// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.nio.ByteBuffer;
import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class SizePrefixedCosignatureV1 extends CatbufferType {
	private CosignatureV1 cosignature;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("cosignature", "struct:CosignatureV1"));

	/**
	 * Creates a new SizePrefixedCosignatureV1.
	 */
	public SizePrefixedCosignatureV1() {
		this.cosignature = new CosignatureV1();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "cosignature" -> this.cosignature = (CosignatureV1) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "cosignature" -> this.cosignature;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.cosignature.sort();
	}

	/**
	 * Gets the cosignature field.
	 *
	 * @return The cosignature field.
	 */
	public CosignatureV1 getCosignature() {
		return this.cosignature;
	}

	/**
	 * Sets the cosignature field.
	 *
	 * @param value New cosignature value.
	 */
	public void setCosignature(final CosignatureV1 value) {
		this.cosignature = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += this.cosignature.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param buffer Output writer.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SizePrefixedCosignatureV1 deserialize(final ByteBuffer buffer) {
		final BufferView cursor = new BufferView(buffer);
		final SizePrefixedCosignatureV1 instance = new SizePrefixedCosignatureV1();

		final int cosignatureSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final CosignatureV1 cosignature = CosignatureV1.deserialize(cursor.window(cosignatureSize).buffer());
		cursor.shiftRight(cosignature.size());

		instance.cosignature = cosignature;
		return instance;
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.cosignature.size(), 4); // bound: cosignature_size
		buffer.write(this.cosignature.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("cosignature: ").append(this.cosignature.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("cosignature", this.cosignature.toJson());
		return result;
	}
}
