// Auto-generated by sdk/java/generator. Do not edit directly.
// Run scripts/run_catbuffer_generator.sh to regenerate.

package org.symbol.sdk.nem.models;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.CatbufferType;
import org.symbol.sdk.utils.BufferView;
import org.symbol.sdk.utils.Writer;

public final class SizePrefixedMultisigAccountModification extends CatbufferType {
	private MultisigAccountModification modification;
	public static final Map<String, String> TYPE_HINTS = Map.ofEntries(Map.entry("modification", "struct:MultisigAccountModification"));

	/**
	 * Creates a SizePrefixedMultisigAccountModification.
	 */
	public SizePrefixedMultisigAccountModification() {
		this.modification = new MultisigAccountModification();
	}

	/**
	 * Returns the type-hint map driving the rule-based descriptor pipeline.
	 *
	 * @return Field-name → rule-key map.
	 */
	@Override
	public Map<String, String> typeHints() {
		return TYPE_HINTS;
	}

	/**
	 * Sets a named field. Used by the rule-based descriptor pipeline.
	 *
	 * @param name Field name (descriptor key).
	 * @param value Value to assign.
	 */
	@Override
	public void setField(final String name, final Object value) {
		switch (name) {
			case "modification" -> this.modification = (MultisigAccountModification) value;
			default -> super.setField(name, value);
		}
	}

	/**
	 * Reads a named field. Used by the facade-level entity inspection helpers.
	 *
	 * @param name Field name.
	 * @return Field value.
	 */
	@Override
	public Object getField(final String name) {
		return switch (name) {
			case "modification" -> this.modification;
			default -> super.getField(name);
		};
	}

	/**
	 * Sorts the collections of this object so that it can be serialized canonically.
	 */
	@Override
	public void sort() {
		this.modification.sort();
	}

	/**
	 * Gets the modification field.
	 *
	 * @return The modification field.
	 */
	public MultisigAccountModification getModification() {
		return this.modification;
	}

	/**
	 * Sets the modification field.
	 *
	 * @param value New modification value.
	 */
	public void setModification(final MultisigAccountModification value) {
		this.modification = value;
	}

	/**
	 * Calculates the size of the object.
	 *
	 * @return Size of this object in bytes.
	 */
	@Override
	public int size() {
		int size = 0;
		size += 4;
		size += this.modification.size();
		return size;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param view Buffer view to read from; not advanced (the caller moves its cursor by the returned object's size()).
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SizePrefixedMultisigAccountModification deserialize(final BufferView view) {
		final BufferView cursor = view.snapshot();
		final SizePrefixedMultisigAccountModification instance = new SizePrefixedMultisigAccountModification();

		final int modificationSize = (int) (cursor.peekInt(4, false));
		cursor.shiftRight(4);
		final MultisigAccountModification modification = MultisigAccountModification.deserialize(cursor.window(modificationSize));
		cursor.shiftRight(modification.size());

		instance.modification = modification;
		return instance;
	}

	/**
	 * Deserializes an instance of this object from a byte payload.
	 *
	 * @param payload Byte payload to deserialize.
	 * @return Deserialized object.
	 * @throws IndexOutOfBoundsException if the buffer is truncated or a declared length overruns it
	 * @throws IllegalArgumentException if a field carries an invalid value (e.g. a reserved field or unknown discriminator)
	 */
	public static SizePrefixedMultisigAccountModification deserialize(final byte[] payload) {
		return deserialize(new BufferView(payload));
	}

	/**
	 * Writes this object's fields into the supplied buffer.
	 *
	 * @param buffer Output writer.
	 */
	@Override
	protected void serializeInto(final Writer buffer) {
		buffer.writeInt(this.modification.size(), 4); // bound: modification_size
		buffer.write(this.modification.serialize());
	}

	/**
	 * Returns a string representation of this object.
	 *
	 * @return String representation of this object.
	 */
	@Override
	public String toString() {
		final StringBuilder result = new StringBuilder("(");
		result.append("modification: ").append(this.modification.toString()).append(", ");
		result.append(")");
		return result.toString();
	}

	/**
	 * Converts this object to a JSON-serializable representation.
	 *
	 * @return JSON-serializable representation of this object.
	 */
	@Override
	public Map<String, Object> toJson() {
		final Map<String, Object> result = new LinkedHashMap<>();
		result.put("modification", this.modification.toJson());
		return result;
	}

}
