defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'client-rest'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/symbol-rest'

	codeCoverageTool = 'nyc'
	minimumCodeCoverage = 90
}
