/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';
import Amount from './Amount.js';

/**
 * The ConstructionMetadataResponse model module.
 * @module model/ConstructionMetadataResponse
 * @version 1.4.13
 */
class ConstructionMetadataResponse {
	/**
	 * Constructs a new <code>ConstructionMetadataResponse</code>.
	 * The ConstructionMetadataResponse returns network-specific metadata used for transaction construction. Optionally, the implementer can return the suggested fee associated with the transaction being constructed. The caller may use this info to adjust the intent of the transaction or to create a transaction with a different account that can pay the suggested fee. Suggested fee is an array in case fee payment must occur in multiple currencies.
	 * @alias module:model/ConstructionMetadataResponse
	 * @param metadata {Object}
	 */
	constructor(metadata) {

		ConstructionMetadataResponse.initialize(this, metadata);
	}

	/**
	 * Initializes the fields of this object.
	 * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
	 * Only for internal use.
	 */
	static initialize(obj, metadata) {
		obj['metadata'] = metadata;
	}

	/**
	 * Constructs a <code>ConstructionMetadataResponse</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/ConstructionMetadataResponse} obj Optional instance to populate.
	 * @return {module:model/ConstructionMetadataResponse} The populated <code>ConstructionMetadataResponse</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new ConstructionMetadataResponse();

			if (data.hasOwnProperty('metadata')) {
				obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
			}
			if (data.hasOwnProperty('suggested_fee')) {
				obj['suggested_fee'] = ApiClient.convertToType(data['suggested_fee'], [Amount]);
			}
		}
		return obj;
	}

	/**
	 * Validates the JSON data with respect to <code>ConstructionMetadataResponse</code>.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConstructionMetadataResponse</code>.
	 */
	static validateJSON(data) {
		// check to make sure all required properties are present in the JSON string
		for (const property of ConstructionMetadataResponse.RequiredProperties) {
			if (!data.hasOwnProperty(property)) {
				throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
			}
		}
		if (data['suggested_fee']) { // data not null
			// ensure the json data is an array
			if (!Array.isArray(data['suggested_fee'])) {
				throw new Error("Expected the field `suggested_fee` to be an array in the JSON data but got " + data['suggested_fee']);
			}
			// validate the optional field `suggested_fee` (array)
			for (const item of data['suggested_fee']) {
				Amount.validateJSON(item);
			};
		}

		return true;
	}


}

ConstructionMetadataResponse.RequiredProperties = ["metadata"];

/**
 * @member {Object} metadata
 */
ConstructionMetadataResponse.prototype['metadata'] = undefined;

/**
 * @member {Array.<module:model/Amount>} suggested_fee
 */
ConstructionMetadataResponse.prototype['suggested_fee'] = undefined;






export default ConstructionMetadataResponse;

