/**
 * Rosetta
 * Build Once. Integrate Your Blockchain Everywhere.
 *
 * The version of the OpenAPI document: 1.4.13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient.js';

/**
 * The OperationIdentifier model module.
 * @module model/OperationIdentifier
 * @version 1.4.13
 */
class OperationIdentifier {
	/**
	 * Constructs a new <code>OperationIdentifier</code>.
	 * The operation_identifier uniquely identifies an operation within a transaction.
	 * @alias module:model/OperationIdentifier
	 * @param index {Number} The operation index is used to ensure each operation has a unique identifier within a transaction. This index is only relative to the transaction and NOT GLOBAL. The operations in each transaction should start from index 0. To clarify, there may not be any notion of an operation index in the blockchain being described.
	 */
	constructor(index) {

		OperationIdentifier.initialize(this, index);
	}

	/**
	 * Initializes the fields of this object.
	 * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
	 * Only for internal use.
	 */
	static initialize(obj, index) {
		obj['index'] = index;
	}

	/**
	 * Constructs a <code>OperationIdentifier</code> from a plain JavaScript object, optionally creating a new instance.
	 * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @param {module:model/OperationIdentifier} obj Optional instance to populate.
	 * @return {module:model/OperationIdentifier} The populated <code>OperationIdentifier</code> instance.
	 */
	static constructFromObject(data, obj) {
		if (data) {
			obj = obj || new OperationIdentifier();

			if (data.hasOwnProperty('index')) {
				obj['index'] = ApiClient.convertToType(data['index'], 'Number');
			}
			if (data.hasOwnProperty('network_index')) {
				obj['network_index'] = ApiClient.convertToType(data['network_index'], 'Number');
			}
		}
		return obj;
	}

	/**
	 * Validates the JSON data with respect to <code>OperationIdentifier</code>.
	 * @param {Object} data The plain JavaScript object bearing properties of interest.
	 * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OperationIdentifier</code>.
	 */
	static validateJSON(data) {
		// check to make sure all required properties are present in the JSON string
		for (const property of OperationIdentifier.RequiredProperties) {
			if (!data.hasOwnProperty(property)) {
				throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
			}
		}

		return true;
	}


}

OperationIdentifier.RequiredProperties = ["index"];

/**
 * The operation index is used to ensure each operation has a unique identifier within a transaction. This index is only relative to the transaction and NOT GLOBAL. The operations in each transaction should start from index 0. To clarify, there may not be any notion of an operation index in the blockchain being described.
 * @member {Number} index
 */
OperationIdentifier.prototype['index'] = undefined;

/**
 * Some blockchains specify an operation index that is essential for client use. For example, Bitcoin uses a network_index to identify which UTXO was used in a transaction. network_index should not be populated if there is no notion of an operation index in a blockchain (typically most account-based blockchains).
 * @member {Number} network_index
 */
OperationIdentifier.prototype['network_index'] = undefined;






export default OperationIdentifier;

