// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.notNullValue;
import static org.hamcrest.Matchers.sameInstance;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Test;

import org.symbol.sdk.CryptoTypes;
import org.symbol.sdk.symbol.Network;
import org.symbol.sdk.symbol.SymbolTransactionFactory;
import org.symbol.sdk.symbol.models.AccountAddressRestrictionTransactionV1;
import org.symbol.sdk.symbol.models.AccountKeyLinkTransactionV1;
import org.symbol.sdk.symbol.models.AccountMetadataTransactionV1;
import org.symbol.sdk.symbol.models.AccountMosaicRestrictionTransactionV1;
import org.symbol.sdk.symbol.models.AccountOperationRestrictionTransactionV1;
import org.symbol.sdk.symbol.models.AccountRestrictionFlags;
import org.symbol.sdk.symbol.models.AddressAliasTransactionV1;
import org.symbol.sdk.symbol.models.AggregateBondedTransactionV1;
import org.symbol.sdk.symbol.models.AggregateBondedTransactionV2;
import org.symbol.sdk.symbol.models.AggregateBondedTransactionV3;
import org.symbol.sdk.symbol.models.AggregateCompleteTransactionV1;
import org.symbol.sdk.symbol.models.AggregateCompleteTransactionV2;
import org.symbol.sdk.symbol.models.AggregateCompleteTransactionV3;
import org.symbol.sdk.symbol.models.AliasAction;
import org.symbol.sdk.symbol.models.Amount;
import org.symbol.sdk.symbol.models.BlockDuration;
import org.symbol.sdk.symbol.models.Cosignature;
import org.symbol.sdk.symbol.models.EmbeddedAccountKeyLinkTransactionV1;
import org.symbol.sdk.symbol.models.FinalizationEpoch;
import org.symbol.sdk.symbol.models.Hash256;
import org.symbol.sdk.symbol.models.HashLockTransactionV1;
import org.symbol.sdk.symbol.models.LinkAction;
import org.symbol.sdk.symbol.models.LockHashAlgorithm;
import org.symbol.sdk.symbol.models.MosaicAddressRestrictionTransactionV1;
import org.symbol.sdk.symbol.models.MosaicAliasTransactionV1;
import org.symbol.sdk.symbol.models.MosaicDefinitionTransactionV1;
import org.symbol.sdk.symbol.models.MosaicFlags;
import org.symbol.sdk.symbol.models.MosaicGlobalRestrictionTransactionV1;
import org.symbol.sdk.symbol.models.MosaicId;
import org.symbol.sdk.symbol.models.MosaicMetadataTransactionV1;
import org.symbol.sdk.symbol.models.MosaicNonce;
import org.symbol.sdk.symbol.models.MosaicRestrictionType;
import org.symbol.sdk.symbol.models.MosaicSupplyChangeAction;
import org.symbol.sdk.symbol.models.MosaicSupplyChangeTransactionV1;
import org.symbol.sdk.symbol.models.MosaicSupplyRevocationTransactionV1;
import org.symbol.sdk.symbol.models.MultisigAccountModificationTransactionV1;
import org.symbol.sdk.symbol.models.NamespaceId;
import org.symbol.sdk.symbol.models.NamespaceMetadataTransactionV1;
import org.symbol.sdk.symbol.models.NamespaceRegistrationTransactionV1;
import org.symbol.sdk.symbol.models.NamespaceRegistrationType;
import org.symbol.sdk.symbol.models.NodeKeyLinkTransactionV1;
import org.symbol.sdk.symbol.models.PublicKey;
import org.symbol.sdk.symbol.models.SecretLockTransactionV1;
import org.symbol.sdk.symbol.models.SecretProofTransactionV1;
import org.symbol.sdk.symbol.models.Signature;
import org.symbol.sdk.symbol.models.TransactionType;
import org.symbol.sdk.symbol.models.TransferTransactionV1;
import org.symbol.sdk.symbol.models.UnresolvedAddress;
import org.symbol.sdk.symbol.models.UnresolvedMosaicId;
import org.symbol.sdk.symbol.models.VotingKeyLinkTransactionV1;
import org.symbol.sdk.symbol.models.VotingPublicKey;
import org.symbol.sdk.symbol.models.VrfKeyLinkTransactionV1;

/**
 * Generated per-descriptor sweep: construction with distinct sample values, exact {@code toMap()} contents (null optional arguments leave
 * their keys absent), all-args constructor storage of every field, and (for transaction descriptors) a factory round-trip verifying each
 * created-model field via {@code getField}.
 */
final class DescriptorsSweepTest {
	private static final CryptoTypes.PublicKey SWEEP_SIGNER_PUBLIC_KEY = new CryptoTypes.PublicKey(
			"364F3694A022DB4DC59558944707C6679F6FD7E1A7B99CDE8F7D16D3FF515D28");

	private static final SymbolTransactionFactory FACTORY = new SymbolTransactionFactory(Network.TESTNET);

	/**
	 * Returns the descriptor's map with the sweep signer added. No defensive copy is needed: toMap() returns the live descriptor map, and
	 * the descriptor is a throwaway sweep instance.
	 */
	private static Map<String, Object> sweepCreateMap(final SymbolTransactionDescriptor descriptor) {
		final Map<String, Object> createMap = descriptor.toMap();
		createMap.put("signerPublicKey", SWEEP_SIGNER_PUBLIC_KEY);
		return createMap;
	}

	/** Constructs a MosaicDescriptor with distinct sample required arguments. */
	private static MosaicDescriptor sweepNewMosaicDescriptor() {
		return new MosaicDescriptor(MosaicId.parse("1"), Amount.parse("2"));
	}

	@Test
	void mosaicDescriptor() {
		// Arrange:
		final MosaicDescriptor descriptor = sweepNewMosaicDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("mosaicId"), equalTo(MosaicId.parse("1")));
		assertThat(built.get("amount"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(2));
	}

	/** Constructs a UnresolvedMosaicDescriptor with distinct sample required arguments. */
	private static UnresolvedMosaicDescriptor sweepNewUnresolvedMosaicDescriptor() {
		return new UnresolvedMosaicDescriptor(UnresolvedMosaicId.parse("1"), Amount.parse("2"));
	}

	@Test
	void unresolvedMosaicDescriptor() {
		// Arrange:
		final UnresolvedMosaicDescriptor descriptor = sweepNewUnresolvedMosaicDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("mosaicId"), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(built.get("amount"), equalTo(Amount.parse("2")));
		assertThat(built.size(), equalTo(2));
	}

	/** Constructs a AccountKeyLinkTransactionV1Descriptor with distinct sample required arguments. */
	private static AccountKeyLinkTransactionV1Descriptor sweepNewAccountKeyLinkTransactionV1Descriptor() {
		return new AccountKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link"));
	}

	@Test
	void accountKeyLinkTransactionV1Descriptor() {
		// Arrange:
		final AccountKeyLinkTransactionV1Descriptor descriptor = sweepNewAccountKeyLinkTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("account_key_link_transaction_v1"));
		assertThat(built.get("linkedPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("linkAction"), equalTo(LinkAction.parse("link")));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void accountKeyLinkTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new AccountKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link")));

		// Act:
		final AccountKeyLinkTransactionV1 transaction = (AccountKeyLinkTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getLinkedPublicKey(), equalTo(
				new PublicKey((new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getLinkAction(), equalTo(LinkAction.parse("link")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a NodeKeyLinkTransactionV1Descriptor with distinct sample required arguments. */
	private static NodeKeyLinkTransactionV1Descriptor sweepNewNodeKeyLinkTransactionV1Descriptor() {
		return new NodeKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link"));
	}

	@Test
	void nodeKeyLinkTransactionV1Descriptor() {
		// Arrange:
		final NodeKeyLinkTransactionV1Descriptor descriptor = sweepNewNodeKeyLinkTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("node_key_link_transaction_v1"));
		assertThat(built.get("linkedPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("linkAction"), equalTo(LinkAction.parse("link")));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void nodeKeyLinkTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new NodeKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link")));

		// Act:
		final NodeKeyLinkTransactionV1 transaction = (NodeKeyLinkTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getLinkedPublicKey(), equalTo(
				new PublicKey((new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getLinkAction(), equalTo(LinkAction.parse("link")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a CosignatureDescriptor with distinct sample required arguments. */
	private static CosignatureDescriptor sweepNewCosignatureDescriptor() {
		return new CosignatureDescriptor(1L, new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303"),
				Signature.parse(
						"04040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404"));
	}

	@Test
	void cosignatureDescriptor() {
		// Arrange:
		final CosignatureDescriptor descriptor = sweepNewCosignatureDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("version"), equalTo(1L));
		assertThat(built.get("signerPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.get("signature"), equalTo(Signature.parse(
				"04040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404")));
		assertThat(built.size(), equalTo(3));
	}

	/** Constructs a DetachedCosignatureDescriptor with distinct sample required arguments. */
	private static DetachedCosignatureDescriptor sweepNewDetachedCosignatureDescriptor() {
		return new DetachedCosignatureDescriptor(1L,
				new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303"),
				Signature.parse(
						"04040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404"),
				new CryptoTypes.Hash256("0505050505050505050505050505050505050505050505050505050505050505"));
	}

	@Test
	void detachedCosignatureDescriptor() {
		// Arrange:
		final DetachedCosignatureDescriptor descriptor = sweepNewDetachedCosignatureDescriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("version"), equalTo(1L));
		assertThat(built.get("signerPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.get("signature"), equalTo(Signature.parse(
				"04040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404040404")));
		assertThat(built.get("parentHash"),
				equalTo(new CryptoTypes.Hash256("0505050505050505050505050505050505050505050505050505050505050505")));
		assertThat(built.size(), equalTo(4));
	}

	/** Constructs a AggregateCompleteTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateCompleteTransactionV1Descriptor sweepNewAggregateCompleteTransactionV1Descriptor() {
		return new AggregateCompleteTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateCompleteTransactionV1Descriptor() {
		// Arrange:
		final AggregateCompleteTransactionV1Descriptor descriptor = sweepNewAggregateCompleteTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_complete_transaction_v1"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateCompleteTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateCompleteTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateCompleteTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateCompleteTransactionV1 transaction = (AggregateCompleteTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AggregateCompleteTransactionV2Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateCompleteTransactionV2Descriptor sweepNewAggregateCompleteTransactionV2Descriptor() {
		return new AggregateCompleteTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateCompleteTransactionV2Descriptor() {
		// Arrange:
		final AggregateCompleteTransactionV2Descriptor descriptor = sweepNewAggregateCompleteTransactionV2Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_complete_transaction_v2"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateCompleteTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateCompleteTransactionV2DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateCompleteTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateCompleteTransactionV2 transaction = (AggregateCompleteTransactionV2) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AggregateCompleteTransactionV3Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateCompleteTransactionV3Descriptor sweepNewAggregateCompleteTransactionV3Descriptor() {
		return new AggregateCompleteTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateCompleteTransactionV3Descriptor() {
		// Arrange:
		final AggregateCompleteTransactionV3Descriptor descriptor = sweepNewAggregateCompleteTransactionV3Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_complete_transaction_v3"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateCompleteTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateCompleteTransactionV3DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateCompleteTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateCompleteTransactionV3 transaction = (AggregateCompleteTransactionV3) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AggregateBondedTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateBondedTransactionV1Descriptor sweepNewAggregateBondedTransactionV1Descriptor() {
		return new AggregateBondedTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateBondedTransactionV1Descriptor() {
		// Arrange:
		final AggregateBondedTransactionV1Descriptor descriptor = sweepNewAggregateBondedTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_bonded_transaction_v1"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateBondedTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateBondedTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateBondedTransactionV1Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateBondedTransactionV1 transaction = (AggregateBondedTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AggregateBondedTransactionV2Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateBondedTransactionV2Descriptor sweepNewAggregateBondedTransactionV2Descriptor() {
		return new AggregateBondedTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateBondedTransactionV2Descriptor() {
		// Arrange:
		final AggregateBondedTransactionV2Descriptor descriptor = sweepNewAggregateBondedTransactionV2Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_bonded_transaction_v2"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateBondedTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateBondedTransactionV2DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateBondedTransactionV2Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateBondedTransactionV2 transaction = (AggregateBondedTransactionV2) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AggregateBondedTransactionV3Descriptor with distinct sample required arguments and null optionals. */
	private static AggregateBondedTransactionV3Descriptor sweepNewAggregateBondedTransactionV3Descriptor() {
		return new AggregateBondedTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"), null, null);
	}

	@Test
	void aggregateBondedTransactionV3Descriptor() {
		// Arrange:
		final AggregateBondedTransactionV3Descriptor descriptor = sweepNewAggregateBondedTransactionV3Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("aggregate_bonded_transaction_v3"));
		assertThat(built.get("transactionsHash"),
				equalTo(new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.containsKey("transactions"), equalTo(false));
		assertThat(built.containsKey("cosignatures"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AggregateBondedTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(new EmbeddedAccountKeyLinkTransactionV1()), List.of(new Cosignature())).toMap();
		assertThat(((List<?>) fullBuilt.get("transactions")).size(), equalTo(1));
		assertThat(((List<?>) fullBuilt.get("cosignatures")).size(), equalTo(1));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void aggregateBondedTransactionV3DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final EmbeddedAccountKeyLinkTransactionV1 sweepTransactionsElement = new EmbeddedAccountKeyLinkTransactionV1();
		final Cosignature sweepCosignaturesElement = new Cosignature();
		final Map<String, Object> createMap = sweepCreateMap(new AggregateBondedTransactionV3Descriptor(
				new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202"),
				List.of(sweepTransactionsElement), List.of(sweepCosignaturesElement)));

		// Act:
		final AggregateBondedTransactionV3 transaction = (AggregateBondedTransactionV3) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTransactionsHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getTransactions().size(), equalTo(1));
		assertThat(transaction.getTransactions().get(0), sameInstance(sweepTransactionsElement));
		assertThat(transaction.getCosignatures().size(), equalTo(1));
		assertThat(transaction.getCosignatures().get(0), sameInstance(sweepCosignaturesElement));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a VotingKeyLinkTransactionV1Descriptor with distinct sample required arguments. */
	private static VotingKeyLinkTransactionV1Descriptor sweepNewVotingKeyLinkTransactionV1Descriptor() {
		return new VotingKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), FinalizationEpoch.parse("2"),
				FinalizationEpoch.parse("3"), LinkAction.parse("link"));
	}

	@Test
	void votingKeyLinkTransactionV1Descriptor() {
		// Arrange:
		final VotingKeyLinkTransactionV1Descriptor descriptor = sweepNewVotingKeyLinkTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("voting_key_link_transaction_v1"));
		assertThat(built.get("linkedPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("startEpoch"), equalTo(FinalizationEpoch.parse("2")));
		assertThat(built.get("endEpoch"), equalTo(FinalizationEpoch.parse("3")));
		assertThat(built.get("linkAction"), equalTo(LinkAction.parse("link")));
		assertThat(built.size(), equalTo(5));
	}

	@Test
	void votingKeyLinkTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new VotingKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), FinalizationEpoch.parse("2"),
				FinalizationEpoch.parse("3"), LinkAction.parse("link")));

		// Act:
		final VotingKeyLinkTransactionV1 transaction = (VotingKeyLinkTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getLinkedPublicKey(), equalTo(new VotingPublicKey(
				(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getStartEpoch(), equalTo(FinalizationEpoch.parse("2")));
		assertThat(transaction.getEndEpoch(), equalTo(FinalizationEpoch.parse("3")));
		assertThat(transaction.getLinkAction(), equalTo(LinkAction.parse("link")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a VrfKeyLinkTransactionV1Descriptor with distinct sample required arguments. */
	private static VrfKeyLinkTransactionV1Descriptor sweepNewVrfKeyLinkTransactionV1Descriptor() {
		return new VrfKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link"));
	}

	@Test
	void vrfKeyLinkTransactionV1Descriptor() {
		// Arrange:
		final VrfKeyLinkTransactionV1Descriptor descriptor = sweepNewVrfKeyLinkTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("vrf_key_link_transaction_v1"));
		assertThat(built.get("linkedPublicKey"),
				equalTo(new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")));
		assertThat(built.get("linkAction"), equalTo(LinkAction.parse("link")));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void vrfKeyLinkTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new VrfKeyLinkTransactionV1Descriptor(
				new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202"), LinkAction.parse("link")));

		// Act:
		final VrfKeyLinkTransactionV1 transaction = (VrfKeyLinkTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getLinkedPublicKey(), equalTo(
				new PublicKey((new CryptoTypes.PublicKey("0202020202020202020202020202020202020202020202020202020202020202")).bytes())));
		assertThat(transaction.getLinkAction(), equalTo(LinkAction.parse("link")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a HashLockTransactionV1Descriptor with distinct sample required arguments. */
	private static HashLockTransactionV1Descriptor sweepNewHashLockTransactionV1Descriptor() {
		return new HashLockTransactionV1Descriptor(sweepNewUnresolvedMosaicDescriptor(), BlockDuration.parse("2"),
				new CryptoTypes.Hash256("0404040404040404040404040404040404040404040404040404040404040404"));
	}

	@Test
	void hashLockTransactionV1Descriptor() {
		// Arrange:
		final HashLockTransactionV1Descriptor descriptor = sweepNewHashLockTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("hash_lock_transaction_v1"));
		assertThat(built.get("mosaic"), equalTo(sweepNewUnresolvedMosaicDescriptor().toMap()));
		assertThat(built.get("duration"), equalTo(BlockDuration.parse("2")));
		assertThat(built.get("hash"), equalTo(new CryptoTypes.Hash256("0404040404040404040404040404040404040404040404040404040404040404")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void hashLockTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new HashLockTransactionV1Descriptor(sweepNewUnresolvedMosaicDescriptor(),
				BlockDuration.parse("2"), new CryptoTypes.Hash256("0404040404040404040404040404040404040404040404040404040404040404")));

		// Act:
		final HashLockTransactionV1 transaction = (HashLockTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaic(), notNullValue());
		assertThat(transaction.getDuration(), equalTo(BlockDuration.parse("2")));
		assertThat(transaction.getHash(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0404040404040404040404040404040404040404040404040404040404040404")).bytes())));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a SecretLockTransactionV1Descriptor with distinct sample required arguments. */
	private static SecretLockTransactionV1Descriptor sweepNewSecretLockTransactionV1Descriptor() {
		return new SecretLockTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
				new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303"),
				sweepNewUnresolvedMosaicDescriptor(), BlockDuration.parse("4"), LockHashAlgorithm.parse("hash_160"));
	}

	@Test
	void secretLockTransactionV1Descriptor() {
		// Arrange:
		final SecretLockTransactionV1Descriptor descriptor = sweepNewSecretLockTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("secret_lock_transaction_v1"));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("secret"),
				equalTo(new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.get("mosaic"), equalTo(sweepNewUnresolvedMosaicDescriptor().toMap()));
		assertThat(built.get("duration"), equalTo(BlockDuration.parse("4")));
		assertThat(built.get("hashAlgorithm"), equalTo(LockHashAlgorithm.parse("hash_160")));
		assertThat(built.size(), equalTo(6));
	}

	@Test
	void secretLockTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new SecretLockTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
						new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303"),
						sweepNewUnresolvedMosaicDescriptor(), BlockDuration.parse("4"), LockHashAlgorithm.parse("hash_160")));

		// Act:
		final SecretLockTransactionV1 transaction = (SecretLockTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRecipientAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getSecret(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303")).bytes())));
		assertThat(transaction.getMosaic(), notNullValue());
		assertThat(transaction.getDuration(), equalTo(BlockDuration.parse("4")));
		assertThat(transaction.getHashAlgorithm(), equalTo(LockHashAlgorithm.parse("hash_160")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a SecretProofTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static SecretProofTransactionV1Descriptor sweepNewSecretProofTransactionV1Descriptor() {
		return new SecretProofTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
				new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303"),
				LockHashAlgorithm.parse("hash_256"), null);
	}

	@Test
	void secretProofTransactionV1Descriptor() {
		// Arrange:
		final SecretProofTransactionV1Descriptor descriptor = sweepNewSecretProofTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("secret_proof_transaction_v1"));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("secret"),
				equalTo(new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303")));
		assertThat(built.get("hashAlgorithm"), equalTo(LockHashAlgorithm.parse("hash_256")));
		assertThat(built.containsKey("proof"), equalTo(false));
		assertThat(built.size(), equalTo(4));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new SecretProofTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
				new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303"),
				LockHashAlgorithm.parse("hash_256"), "proof".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("proof"), equalTo("proof".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(5));
	}

	@Test
	void secretProofTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new SecretProofTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
						new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303"),
						LockHashAlgorithm.parse("hash_256"), "proof".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final SecretProofTransactionV1 transaction = (SecretProofTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRecipientAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getSecret(), equalTo(
				new Hash256((new CryptoTypes.Hash256("0303030303030303030303030303030303030303030303030303030303030303")).bytes())));
		assertThat(transaction.getHashAlgorithm(), equalTo(LockHashAlgorithm.parse("hash_256")));
		assertThat(transaction.getProof(), equalTo("proof".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AccountMetadataTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AccountMetadataTransactionV1Descriptor sweepNewAccountMetadataTransactionV1Descriptor() {
		return new AccountMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L,
				3, null);
	}

	@Test
	void accountMetadataTransactionV1Descriptor() {
		// Arrange:
		final AccountMetadataTransactionV1Descriptor descriptor = sweepNewAccountMetadataTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("account_metadata_transaction_v1"));
		assertThat(built.get("targetAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("scopedMetadataKey"), equalTo(2L));
		assertThat(built.get("valueSizeDelta"), equalTo(3));
		assertThat(built.containsKey("value"), equalTo(false));
		assertThat(built.size(), equalTo(4));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AccountMetadataTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L, 3,
				"value".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("value"), equalTo("value".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(5));
	}

	@Test
	void accountMetadataTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new AccountMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L,
						3, "value".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final AccountMetadataTransactionV1 transaction = (AccountMetadataTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTargetAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getScopedMetadataKey(), equalTo(2L));
		assertThat(transaction.getValueSizeDelta(), equalTo(3));
		assertThat(transaction.getValue(), equalTo("value".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicMetadataTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static MosaicMetadataTransactionV1Descriptor sweepNewMosaicMetadataTransactionV1Descriptor() {
		return new MosaicMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L,
				UnresolvedMosaicId.parse("3"), 4, null);
	}

	@Test
	void mosaicMetadataTransactionV1Descriptor() {
		// Arrange:
		final MosaicMetadataTransactionV1Descriptor descriptor = sweepNewMosaicMetadataTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("mosaic_metadata_transaction_v1"));
		assertThat(built.get("targetAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("scopedMetadataKey"), equalTo(2L));
		assertThat(built.get("targetMosaicId"), equalTo(UnresolvedMosaicId.parse("3")));
		assertThat(built.get("valueSizeDelta"), equalTo(4));
		assertThat(built.containsKey("value"), equalTo(false));
		assertThat(built.size(), equalTo(5));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new MosaicMetadataTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L, UnresolvedMosaicId.parse("3"), 4,
				"value".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("value"), equalTo("value".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(6));
	}

	@Test
	void mosaicMetadataTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new MosaicMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L,
						UnresolvedMosaicId.parse("3"), 4, "value".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final MosaicMetadataTransactionV1 transaction = (MosaicMetadataTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTargetAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getScopedMetadataKey(), equalTo(2L));
		assertThat(transaction.getTargetMosaicId(), equalTo(UnresolvedMosaicId.parse("3")));
		assertThat(transaction.getValueSizeDelta(), equalTo(4));
		assertThat(transaction.getValue(), equalTo("value".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a NamespaceMetadataTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static NamespaceMetadataTransactionV1Descriptor sweepNewNamespaceMetadataTransactionV1Descriptor() {
		return new NamespaceMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
				2L, NamespaceId.parse("3"), 4, null);
	}

	@Test
	void namespaceMetadataTransactionV1Descriptor() {
		// Arrange:
		final NamespaceMetadataTransactionV1Descriptor descriptor = sweepNewNamespaceMetadataTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("namespace_metadata_transaction_v1"));
		assertThat(built.get("targetAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("scopedMetadataKey"), equalTo(2L));
		assertThat(built.get("targetNamespaceId"), equalTo(NamespaceId.parse("3")));
		assertThat(built.get("valueSizeDelta"), equalTo(4));
		assertThat(built.containsKey("value"), equalTo(false));
		assertThat(built.size(), equalTo(5));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new NamespaceMetadataTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), 2L, NamespaceId.parse("3"), 4,
				"value".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("value"), equalTo("value".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(6));
	}

	@Test
	void namespaceMetadataTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new NamespaceMetadataTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
						2L, NamespaceId.parse("3"), 4, "value".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final NamespaceMetadataTransactionV1 transaction = (NamespaceMetadataTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getTargetAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getScopedMetadataKey(), equalTo(2L));
		assertThat(transaction.getTargetNamespaceId(), equalTo(NamespaceId.parse("3")));
		assertThat(transaction.getValueSizeDelta(), equalTo(4));
		assertThat(transaction.getValue(), equalTo("value".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicDefinitionTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicDefinitionTransactionV1Descriptor sweepNewMosaicDefinitionTransactionV1Descriptor() {
		return new MosaicDefinitionTransactionV1Descriptor(MosaicId.parse("1"), BlockDuration.parse("2"), MosaicNonce.parse("3"),
				MosaicFlags.parse("restrictable"), 5);
	}

	@Test
	void mosaicDefinitionTransactionV1Descriptor() {
		// Arrange:
		final MosaicDefinitionTransactionV1Descriptor descriptor = sweepNewMosaicDefinitionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_definition_transaction_v1"));
		assertThat(built.get("id"), equalTo(MosaicId.parse("1")));
		assertThat(built.get("duration"), equalTo(BlockDuration.parse("2")));
		assertThat(built.get("nonce"), equalTo(MosaicNonce.parse("3")));
		assertThat(built.get("flags"), equalTo(MosaicFlags.parse("restrictable")));
		assertThat(built.get("divisibility"), equalTo(5));
		assertThat(built.size(), equalTo(6));
	}

	@Test
	void mosaicDefinitionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new MosaicDefinitionTransactionV1Descriptor(MosaicId.parse("1"),
				BlockDuration.parse("2"), MosaicNonce.parse("3"), MosaicFlags.parse("restrictable"), 5));

		// Act:
		final MosaicDefinitionTransactionV1 transaction = (MosaicDefinitionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getId(), notNullValue());
		assertThat(transaction.getDuration(), equalTo(BlockDuration.parse("2")));
		assertThat(transaction.getNonce(), equalTo(MosaicNonce.parse("3")));
		assertThat(transaction.getFlags(), equalTo(MosaicFlags.parse("restrictable")));
		assertThat(transaction.getDivisibility(), equalTo(5));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicSupplyChangeTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicSupplyChangeTransactionV1Descriptor sweepNewMosaicSupplyChangeTransactionV1Descriptor() {
		return new MosaicSupplyChangeTransactionV1Descriptor(UnresolvedMosaicId.parse("1"), Amount.parse("2"),
				MosaicSupplyChangeAction.parse("decrease"));
	}

	@Test
	void mosaicSupplyChangeTransactionV1Descriptor() {
		// Arrange:
		final MosaicSupplyChangeTransactionV1Descriptor descriptor = sweepNewMosaicSupplyChangeTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_supply_change_transaction_v1"));
		assertThat(built.get("mosaicId"), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(built.get("delta"), equalTo(Amount.parse("2")));
		assertThat(built.get("action"), equalTo(MosaicSupplyChangeAction.parse("decrease")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void mosaicSupplyChangeTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new MosaicSupplyChangeTransactionV1Descriptor(UnresolvedMosaicId.parse("1"),
				Amount.parse("2"), MosaicSupplyChangeAction.parse("decrease")));

		// Act:
		final MosaicSupplyChangeTransactionV1 transaction = (MosaicSupplyChangeTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaicId(), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(transaction.getDelta(), equalTo(Amount.parse("2")));
		assertThat(transaction.getAction(), equalTo(MosaicSupplyChangeAction.parse("decrease")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicSupplyRevocationTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicSupplyRevocationTransactionV1Descriptor sweepNewMosaicSupplyRevocationTransactionV1Descriptor() {
		return new MosaicSupplyRevocationTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), sweepNewUnresolvedMosaicDescriptor());
	}

	@Test
	void mosaicSupplyRevocationTransactionV1Descriptor() {
		// Arrange:
		final MosaicSupplyRevocationTransactionV1Descriptor descriptor = sweepNewMosaicSupplyRevocationTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_supply_revocation_transaction_v1"));
		assertThat(built.get("sourceAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("mosaic"), equalTo(sweepNewUnresolvedMosaicDescriptor().toMap()));
		assertThat(built.size(), equalTo(3));
	}

	@Test
	void mosaicSupplyRevocationTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new MosaicSupplyRevocationTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), sweepNewUnresolvedMosaicDescriptor()));

		// Act:
		final MosaicSupplyRevocationTransactionV1 transaction = (MosaicSupplyRevocationTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getSourceAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getMosaic(), notNullValue());

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MultisigAccountModificationTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static MultisigAccountModificationTransactionV1Descriptor sweepNewMultisigAccountModificationTransactionV1Descriptor() {
		return new MultisigAccountModificationTransactionV1Descriptor(1, 2, null, null);
	}

	@Test
	void multisigAccountModificationTransactionV1Descriptor() {
		// Arrange:
		final MultisigAccountModificationTransactionV1Descriptor descriptor = sweepNewMultisigAccountModificationTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("multisig_account_modification_transaction_v1"));
		assertThat(built.get("minRemovalDelta"), equalTo(1));
		assertThat(built.get("minApprovalDelta"), equalTo(2));
		assertThat(built.containsKey("addressAdditions"), equalTo(false));
		assertThat(built.containsKey("addressDeletions"), equalTo(false));
		assertThat(built.size(), equalTo(3));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new MultisigAccountModificationTransactionV1Descriptor(1, 2,
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")),
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))).toMap();
		assertThat(fullBuilt.get("addressAdditions"),
				equalTo(List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));
		assertThat(fullBuilt.get("addressDeletions"),
				equalTo(List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));
		assertThat(fullBuilt.size(), equalTo(5));
	}

	@Test
	void multisigAccountModificationTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new MultisigAccountModificationTransactionV1Descriptor(1, 2,
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")),
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));

		// Act:
		final MultisigAccountModificationTransactionV1 transaction = (MultisigAccountModificationTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMinRemovalDelta(), equalTo(1));
		assertThat(transaction.getMinApprovalDelta(), equalTo(2));
		assertThat(transaction.getAddressAdditions(), equalTo(
				List.of(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes()))));
		assertThat(transaction.getAddressDeletions(), equalTo(
				List.of(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes()))));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AddressAliasTransactionV1Descriptor with distinct sample required arguments. */
	private static AddressAliasTransactionV1Descriptor sweepNewAddressAliasTransactionV1Descriptor() {
		return new AddressAliasTransactionV1Descriptor(NamespaceId.parse("1"),
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), AliasAction.parse("unlink"));
	}

	@Test
	void addressAliasTransactionV1Descriptor() {
		// Arrange:
		final AddressAliasTransactionV1Descriptor descriptor = sweepNewAddressAliasTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("address_alias_transaction_v1"));
		assertThat(built.get("namespaceId"), equalTo(NamespaceId.parse("1")));
		assertThat(built.get("address"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.get("aliasAction"), equalTo(AliasAction.parse("unlink")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void addressAliasTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new AddressAliasTransactionV1Descriptor(NamespaceId.parse("1"),
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), AliasAction.parse("unlink")));

		// Act:
		final AddressAliasTransactionV1 transaction = (AddressAliasTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getNamespaceId(), equalTo(NamespaceId.parse("1")));
		assertThat(transaction.getAddress(), equalTo(new org.symbol.sdk.symbol.models.Address(
				(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getAliasAction(), equalTo(AliasAction.parse("unlink")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicAliasTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicAliasTransactionV1Descriptor sweepNewMosaicAliasTransactionV1Descriptor() {
		return new MosaicAliasTransactionV1Descriptor(NamespaceId.parse("1"), MosaicId.parse("2"), AliasAction.parse("unlink"));
	}

	@Test
	void mosaicAliasTransactionV1Descriptor() {
		// Arrange:
		final MosaicAliasTransactionV1Descriptor descriptor = sweepNewMosaicAliasTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_alias_transaction_v1"));
		assertThat(built.get("namespaceId"), equalTo(NamespaceId.parse("1")));
		assertThat(built.get("mosaicId"), equalTo(MosaicId.parse("2")));
		assertThat(built.get("aliasAction"), equalTo(AliasAction.parse("unlink")));
		assertThat(built.size(), equalTo(4));
	}

	@Test
	void mosaicAliasTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new MosaicAliasTransactionV1Descriptor(NamespaceId.parse("1"), MosaicId.parse("2"), AliasAction.parse("unlink")));

		// Act:
		final MosaicAliasTransactionV1 transaction = (MosaicAliasTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getNamespaceId(), equalTo(NamespaceId.parse("1")));
		assertThat(transaction.getMosaicId(), equalTo(MosaicId.parse("2")));
		assertThat(transaction.getAliasAction(), equalTo(AliasAction.parse("unlink")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a NamespaceRegistrationTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static NamespaceRegistrationTransactionV1Descriptor sweepNewNamespaceRegistrationTransactionV1Descriptor() {
		return new NamespaceRegistrationTransactionV1Descriptor(NamespaceId.parse("3"), NamespaceRegistrationType.parse("child"), null,
				null, null);
	}

	@Test
	void namespaceRegistrationTransactionV1Descriptor() {
		// Arrange:
		final NamespaceRegistrationTransactionV1Descriptor descriptor = sweepNewNamespaceRegistrationTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("namespace_registration_transaction_v1"));
		assertThat(built.get("id"), equalTo(NamespaceId.parse("3")));
		assertThat(built.get("registrationType"), equalTo(NamespaceRegistrationType.parse("child")));
		assertThat(built.containsKey("duration"), equalTo(false));
		assertThat(built.containsKey("parentId"), equalTo(false));
		assertThat(built.containsKey("name"), equalTo(false));
		assertThat(built.size(), equalTo(3));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new NamespaceRegistrationTransactionV1Descriptor(NamespaceId.parse("3"),
				NamespaceRegistrationType.parse("child"), BlockDuration.parse("1"), NamespaceId.parse("2"),
				"name".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("duration"), equalTo(BlockDuration.parse("1")));
		assertThat(fullBuilt.get("parentId"), equalTo(NamespaceId.parse("2")));
		assertThat(fullBuilt.get("name"), equalTo("name".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(6));
	}

	@Test
	void namespaceRegistrationTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new NamespaceRegistrationTransactionV1Descriptor(NamespaceId.parse("3"), NamespaceRegistrationType.parse("child"),
						BlockDuration.parse("1"), NamespaceId.parse("2"), "name".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final NamespaceRegistrationTransactionV1 transaction = (NamespaceRegistrationTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getId(), notNullValue());
		assertThat(transaction.getRegistrationType(), equalTo(NamespaceRegistrationType.parse("child")));
		assertThat(transaction.getDuration().get(), equalTo(BlockDuration.parse("1")));
		assertThat(transaction.getParentId().get(), equalTo(NamespaceId.parse("2")));
		assertThat(transaction.getName(), equalTo("name".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AccountAddressRestrictionTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AccountAddressRestrictionTransactionV1Descriptor sweepNewAccountAddressRestrictionTransactionV1Descriptor() {
		return new AccountAddressRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"), null, null);
	}

	@Test
	void accountAddressRestrictionTransactionV1Descriptor() {
		// Arrange:
		final AccountAddressRestrictionTransactionV1Descriptor descriptor = sweepNewAccountAddressRestrictionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("account_address_restriction_transaction_v1"));
		assertThat(built.get("restrictionFlags"), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(built.containsKey("restrictionAdditions"), equalTo(false));
		assertThat(built.containsKey("restrictionDeletions"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AccountAddressRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"),
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")),
				List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))).toMap();
		assertThat(fullBuilt.get("restrictionAdditions"),
				equalTo(List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));
		assertThat(fullBuilt.get("restrictionDeletions"),
				equalTo(List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void accountAddressRestrictionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new AccountAddressRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"),
						List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")),
						List.of(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"))));

		// Act:
		final AccountAddressRestrictionTransactionV1 transaction = (AccountAddressRestrictionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRestrictionFlags(), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(transaction.getRestrictionAdditions(), equalTo(
				List.of(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes()))));
		assertThat(transaction.getRestrictionDeletions(), equalTo(
				List.of(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes()))));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AccountMosaicRestrictionTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AccountMosaicRestrictionTransactionV1Descriptor sweepNewAccountMosaicRestrictionTransactionV1Descriptor() {
		return new AccountMosaicRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"), null, null);
	}

	@Test
	void accountMosaicRestrictionTransactionV1Descriptor() {
		// Arrange:
		final AccountMosaicRestrictionTransactionV1Descriptor descriptor = sweepNewAccountMosaicRestrictionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("account_mosaic_restriction_transaction_v1"));
		assertThat(built.get("restrictionFlags"), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(built.containsKey("restrictionAdditions"), equalTo(false));
		assertThat(built.containsKey("restrictionDeletions"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AccountMosaicRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"),
				List.of(UnresolvedMosaicId.parse("2")), List.of(UnresolvedMosaicId.parse("3"))).toMap();
		assertThat(fullBuilt.get("restrictionAdditions"), equalTo(List.of(UnresolvedMosaicId.parse("2"))));
		assertThat(fullBuilt.get("restrictionDeletions"), equalTo(List.of(UnresolvedMosaicId.parse("3"))));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void accountMosaicRestrictionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new AccountMosaicRestrictionTransactionV1Descriptor(
				AccountRestrictionFlags.parse("address"), List.of(UnresolvedMosaicId.parse("2")), List.of(UnresolvedMosaicId.parse("3"))));

		// Act:
		final AccountMosaicRestrictionTransactionV1 transaction = (AccountMosaicRestrictionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRestrictionFlags(), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(transaction.getRestrictionAdditions(), equalTo(List.of(UnresolvedMosaicId.parse("2"))));
		assertThat(transaction.getRestrictionDeletions(), equalTo(List.of(UnresolvedMosaicId.parse("3"))));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a AccountOperationRestrictionTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static AccountOperationRestrictionTransactionV1Descriptor sweepNewAccountOperationRestrictionTransactionV1Descriptor() {
		return new AccountOperationRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"), null, null);
	}

	@Test
	void accountOperationRestrictionTransactionV1Descriptor() {
		// Arrange:
		final AccountOperationRestrictionTransactionV1Descriptor descriptor = sweepNewAccountOperationRestrictionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("account_operation_restriction_transaction_v1"));
		assertThat(built.get("restrictionFlags"), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(built.containsKey("restrictionAdditions"), equalTo(false));
		assertThat(built.containsKey("restrictionDeletions"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new AccountOperationRestrictionTransactionV1Descriptor(
				AccountRestrictionFlags.parse("address"), List.of(TransactionType.parse("node_key_link")),
				List.of(TransactionType.parse("aggregate_complete"))).toMap();
		assertThat(fullBuilt.get("restrictionAdditions"), equalTo(List.of(TransactionType.parse("node_key_link"))));
		assertThat(fullBuilt.get("restrictionDeletions"), equalTo(List.of(TransactionType.parse("aggregate_complete"))));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void accountOperationRestrictionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new AccountOperationRestrictionTransactionV1Descriptor(AccountRestrictionFlags.parse("address"),
						List.of(TransactionType.parse("node_key_link")), List.of(TransactionType.parse("aggregate_complete"))));

		// Act:
		final AccountOperationRestrictionTransactionV1 transaction = (AccountOperationRestrictionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRestrictionFlags(), equalTo(AccountRestrictionFlags.parse("address")));
		assertThat(transaction.getRestrictionAdditions(), equalTo(List.of(TransactionType.parse("node_key_link"))));
		assertThat(transaction.getRestrictionDeletions(), equalTo(List.of(TransactionType.parse("aggregate_complete"))));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicAddressRestrictionTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicAddressRestrictionTransactionV1Descriptor sweepNewMosaicAddressRestrictionTransactionV1Descriptor() {
		return new MosaicAddressRestrictionTransactionV1Descriptor(UnresolvedMosaicId.parse("1"), 2L, 3L, 4L,
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"));
	}

	@Test
	void mosaicAddressRestrictionTransactionV1Descriptor() {
		// Arrange:
		final MosaicAddressRestrictionTransactionV1Descriptor descriptor = sweepNewMosaicAddressRestrictionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_address_restriction_transaction_v1"));
		assertThat(built.get("mosaicId"), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(built.get("restrictionKey"), equalTo(2L));
		assertThat(built.get("previousRestrictionValue"), equalTo(3L));
		assertThat(built.get("newRestrictionValue"), equalTo(4L));
		assertThat(built.get("targetAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.size(), equalTo(6));
	}

	@Test
	void mosaicAddressRestrictionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(new MosaicAddressRestrictionTransactionV1Descriptor(
				UnresolvedMosaicId.parse("1"), 2L, 3L, 4L, new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));

		// Act:
		final MosaicAddressRestrictionTransactionV1 transaction = (MosaicAddressRestrictionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaicId(), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(transaction.getRestrictionKey(), equalTo(2L));
		assertThat(transaction.getPreviousRestrictionValue(), equalTo(3L));
		assertThat(transaction.getNewRestrictionValue(), equalTo(4L));
		assertThat(transaction.getTargetAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a MosaicGlobalRestrictionTransactionV1Descriptor with distinct sample required arguments. */
	private static MosaicGlobalRestrictionTransactionV1Descriptor sweepNewMosaicGlobalRestrictionTransactionV1Descriptor() {
		return new MosaicGlobalRestrictionTransactionV1Descriptor(UnresolvedMosaicId.parse("1"), UnresolvedMosaicId.parse("2"), 3L, 4L, 5L,
				MosaicRestrictionType.parse("gt"), MosaicRestrictionType.parse("ge"));
	}

	@Test
	void mosaicGlobalRestrictionTransactionV1Descriptor() {
		// Arrange:
		final MosaicGlobalRestrictionTransactionV1Descriptor descriptor = sweepNewMosaicGlobalRestrictionTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents
		assertThat(built.get("type"), equalTo("mosaic_global_restriction_transaction_v1"));
		assertThat(built.get("mosaicId"), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(built.get("referenceMosaicId"), equalTo(UnresolvedMosaicId.parse("2")));
		assertThat(built.get("restrictionKey"), equalTo(3L));
		assertThat(built.get("previousRestrictionValue"), equalTo(4L));
		assertThat(built.get("newRestrictionValue"), equalTo(5L));
		assertThat(built.get("previousRestrictionType"), equalTo(MosaicRestrictionType.parse("gt")));
		assertThat(built.get("newRestrictionType"), equalTo(MosaicRestrictionType.parse("ge")));
		assertThat(built.size(), equalTo(8));
	}

	@Test
	void mosaicGlobalRestrictionTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new MosaicGlobalRestrictionTransactionV1Descriptor(UnresolvedMosaicId.parse("1"), UnresolvedMosaicId.parse("2"), 3L, 4L, 5L,
						MosaicRestrictionType.parse("gt"), MosaicRestrictionType.parse("ge")));

		// Act:
		final MosaicGlobalRestrictionTransactionV1 transaction = (MosaicGlobalRestrictionTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getMosaicId(), equalTo(UnresolvedMosaicId.parse("1")));
		assertThat(transaction.getReferenceMosaicId(), equalTo(UnresolvedMosaicId.parse("2")));
		assertThat(transaction.getRestrictionKey(), equalTo(3L));
		assertThat(transaction.getPreviousRestrictionValue(), equalTo(4L));
		assertThat(transaction.getNewRestrictionValue(), equalTo(5L));
		assertThat(transaction.getPreviousRestrictionType(), equalTo(MosaicRestrictionType.parse("gt")));
		assertThat(transaction.getNewRestrictionType(), equalTo(MosaicRestrictionType.parse("ge")));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}

	/** Constructs a TransferTransactionV1Descriptor with distinct sample required arguments and null optionals. */
	private static TransferTransactionV1Descriptor sweepNewTransferTransactionV1Descriptor() {
		return new TransferTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), null,
				null);
	}

	@Test
	void transferTransactionV1Descriptor() {
		// Arrange:
		final TransferTransactionV1Descriptor descriptor = sweepNewTransferTransactionV1Descriptor();

		// Act:
		final Map<String, Object> built = descriptor.toMap();

		// Assert: exact required contents; null optional arguments leave their keys absent
		assertThat(built.get("type"), equalTo("transfer_transaction_v1"));
		assertThat(built.get("recipientAddress"), equalTo(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")));
		assertThat(built.containsKey("mosaics"), equalTo(false));
		assertThat(built.containsKey("message"), equalTo(false));
		assertThat(built.size(), equalTo(2));

		// Act + Assert: the all-args constructor stores every optional field
		final Map<String, Object> fullBuilt = new TransferTransactionV1Descriptor(
				new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"), List.of(sweepNewUnresolvedMosaicDescriptor()),
				"message".getBytes(StandardCharsets.UTF_8)).toMap();
		assertThat(fullBuilt.get("mosaics"), equalTo(List.of(sweepNewUnresolvedMosaicDescriptor().toMap())));
		assertThat(fullBuilt.get("message"), equalTo("message".getBytes(StandardCharsets.UTF_8)));
		assertThat(fullBuilt.size(), equalTo(4));
	}

	@Test
	void transferTransactionV1DescriptorFactoryRoundTrip() {
		// Arrange: the sample descriptor with every field populated, plus the signer
		final Map<String, Object> createMap = sweepCreateMap(
				new TransferTransactionV1Descriptor(new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I"),
						List.of(sweepNewUnresolvedMosaicDescriptor()), "message".getBytes(StandardCharsets.UTF_8)));

		// Act:
		final TransferTransactionV1 transaction = (TransferTransactionV1) FACTORY.create(createMap);

		// Assert: every created-model field echoes its sample (per-network conversions applied)
		assertThat(transaction.getRecipientAddress(),
				equalTo(new UnresolvedAddress((new org.symbol.sdk.symbol.Address("TCHBDENCLKEBILBPWP3JPB2XNY64OE7PYHHE32I")).bytes())));
		assertThat(transaction.getMosaics(), notNullValue());
		assertThat(transaction.getMessage(), equalTo("message".getBytes(StandardCharsets.UTF_8)));

		// Assert: the created transaction round-trips through the wire form byte-identically
		final byte[] payload = transaction.serialize();
		assertThat(payload.length, equalTo(transaction.size()));
		assertThat(SymbolTransactionFactory.deserialize(payload).serialize(), equalTo(payload));
	}
}
