INHERIT: ./mkdocs.base.yml

site_name: Symbol Docs WIP 🚧
docs_dir: ../pages/en
site_dir: ../../docs/en
edit_uri: blob/new-docs/mkdocs/pages/en
plugins:
  search:
    lang: en
  mkdoxy: # Generate API reference docs for Java
    projects:
      JavaSDK: # name of project must be alphanumeric + numbers (without spaces)
        doxy-cfg: # standard doxygen configuration (key: value)
          OUTPUT_LANGUAGE: English
markdown_extensions:
  toc:
    permalink_title: Anchor link to this section for reference
    title: On this page
theme:
  language: en
  font:
    text: Exo 2
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
nav:
  - index.md
  - User Guide:
      - userbook/intro.md
  - Developer Guide:
      - devbook/0.introduction.md
      - devbook/1.accounts.md
      - devbook/2.namespaces.md
      - devbook/3.mosaics.md
      - devbook/4.transactions.md
      - devbook/5.nodes.md
      - devbook/6.blocks.md
      - devbook/7.xym.md
      - devbook/8.advanced.md
      - devbook/9.catapult.md
      - devbook/a.catbuffer.md
      - devbook/b.analytics.md
      - devbook/c.other.md
      - Reference Guides:
          - Python SDK: devbook/reference/py/
          - JavaScript SDK: devbook/reference/js/test.md
          - Java SDK: devbook/reference/java/
          - Symbol REST API: devbook/reference/rest/symbol.md
  - Textbook:
      - textbook/intro.md
      - textbook/glossary.md
