site_url: http://symbol.github.io/symbol
repo_url: https://github.com/symbol/symbol
repo_name: symbol
plugins:
  search: {}
  meta-manager: {}
  ezglossary: # Automatic glossary tooltips
    templates: ../templates/ezglossary
    use_default: true
    inline_refs: none
    markdown_links: true
    tooltip: full
  autorefs:
    resolve_closest: true
  mkdoxy: # Generate API reference docs for Java
    save-api: .doxy
    projects:
      JavaSDK: # name of project must be alphanumeric + numbers (without spaces)
        src-dirs: ../sdk/java/src/main # path to source code (support multiple paths separated by space) => INPUT
        template-dir: "!relative $config_dir/../templates/mkdoxy"
        full-doc: true # if you want to generate full documentation
        api-path: devbook/reference/java
        doxy-cfg: # standard doxygen configuration (key: value)
          FILE_PATTERNS: "*.java" # specify file patterns to filter out
          OPTIMIZE_OUTPUT_JAVA: true
          JAVADOC_AUTOBRIEF: true
          STRIP_FROM_PATH: !relative $config_dir/../..
          SOURCE_BROWSER: true
          SOURCE_TOOLTIPS: true
          INLINE_SOURCES: true
  gen-files: # Generate stub files for API reference docs, to be filled by mkdocstrings
    scripts:
      - ../scripts/gen_ref_pages_py.py
      - ../scripts/gen_ref_pages_java.py
  mkdocstrings: # Generate API reference docs for Python and JS
    default_handler: python
    custom_templates: ../templates/mkdocstrings
    handlers:
      python:
        paths: [../../sdk/python]
        options:
          show_source: false
          merge_init_into_class: false
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          show_root_toc_entry: false
          show_object_full_path: false
  literate-nav: # Allow navigation to be specified in the md files created by gen-files
    nav_file: links.md
  git-revision-date-localized: # git dates in page footers
    enable_creation_date: true
    exclude:
      - devbook/reference/*
  git-authors: # git authors in page footers
    exclude:
      - devbook/reference/*
hooks:
  - ../scripts/hooks.py
markdown_extensions:
  attr_list: {}
  admonition: {}
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
  pymdownx.inlinehilite: {}
  pymdownx.snippets:
    base_path: !relative $config_dir/../..
    check_paths: true
  pymdownx.superfences: {}
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.details: {}
  def_list: {}
  md_in_html: {}
  toc:
    permalink: ⚓︎
    permalink_title: Anchor link to this section for reference
    title: On this page
    toc_depth: 3
theme:
  name: material
  custom_dir: ../overrides
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/symbol-logo.svg
  features:
    - content.tooltips # Material tooltips instead of browser
    #- navigation.instant # Single-page application
    - navigation.tracking # URL follows the current section in the page
    - navigation.tabs # Top navbar
    - toc.follow # Current section in TOC is always visible
    - content.tabs.link # Linked content tabs
    - content.code.copy # Copy code button in code blocks
    - content.action.edit # Edit on GitHub button
    - content.action.view # View on GitHub button
extra:
  homepage: https://symbol.github.io/symbol
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /ja/
      lang: ja
  social:
    - icon: fontawesome/solid/house
      link: https://symbol.github.io/symbol
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/SymbolSyndicate
    - icon: fontawesome/brands/github
      link: https://github.com/symbol
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/xymcity
  symbol:
    java-sdk:
      include-prefixes: ["classorg", "interfaceorg"]
  doc_selector:
    - name: Symbol
      target: NEM
      toggle: Switch to NEM documentation
      icon: assets/images/symbol-docs.png
    - name: NEM
      target: Symbol
      toggle: Switch to Symbol documentation
      icon: assets/images/nem-docs.png
copyright: >
  Copyright &copy; 2025 The Symbol Syndicate
extra_css:
  - assets/stylesheets/extra.css
