INHERIT: ./mkdocs.base.yml

site_name: Symbolドキュメント WIP ⚠
docs_dir: ../pages/ja
site_dir: ../../docs/ja
edit_uri: blob/new-docs/mkdocs/pages/ja
plugins:
  search:
    lang: ja
  mkdoxy: # Generate API reference docs for Java
    projects:
      JavaSDK: # name of project must be alphanumeric + numbers (without spaces)
        doxy-cfg: # standard doxygen configuration (key: value)
          OUTPUT_LANGUAGE: Japanese
markdown_extensions:
  toc:
    permalink_title: 参照用にこのセクションへのアンカーリンク
    title: このページに
theme:
  language: ja
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: ライトモードに切り替える

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替える

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: システム設定に切り替える
extra:
  consent:
    title: クッキーの同意
    description: >-
      当社では、お客様の繰り返しのアクセスや好みを認識するため、
      また、当社のドキュメントの有効性やユーザーが探しているものを見つけられるかどうかを測定するために Cookie を使用しています。
      お客様の同意により、当社はドキュメントの改善に協力することになります。
  doc_selector:
    - name: Symbol
      target: NEM
      toggle: NEMドキュメントに切り替える
      icon: assets/images/symbol-docs.png
    - name: NEM
      target: Symbol
      toggle: Symbolドキュメントに切り替える
      icon: assets/images/nem-docs.png
nav:
  - index.md
  - ユーザーガイド:
      - userbook/intro.md
  - 開発者ガイド:
      - devbook/0.introduction.md
      - devbook/1.accounts.md
      - devbook/2.namespaces.md
      - devbook/3.mosaics.md
      - devbook/4.transactions.md
      - devbook/5.nodes.md
      - devbook/6.blocks.md
      - devbook/7.xym.md
      - devbook/8.advanced.md
      - devbook/9.catapult.md
      - devbook/a.catbuffer.md
      - devbook/b.analytics.md
      - devbook/c.other.md
      - SDKs:
          - Python API リファレンス: devbook/reference/py/
          - JavaScript API リファレンス: devbook/reference/js/test.md
          - Java API リファレンス: devbook/reference/java/
  - 教科書:
      - textbook/intro.md
      - textbook/glossary.md
