from pathlib import Path

import mkdocs_gen_files
import re

nav = mkdocs_gen_files.Nav()

# Include in navigation all Java files generated by Doxygen that start with configured prefixes
prefixes = tuple(mkdocs_gen_files.editor.FilesEditor.current().config["extra"]["symbol"]["java-sdk"]["include-prefixes"])
for f in mkdocs_gen_files.editor.FilesEditor.current().files:
    if f.src_uri.startswith("devbook/reference/java/"):
        if not f.name.startswith(prefixes):
            continue

        path = Path(f.src_uri.removeprefix("devbook/reference/java/"))
        module_path = path.relative_to(".").with_suffix("")
        doc_path = path

        match = re.search(r'\n# ([^\s]*) ([^\s]*)', f.content_bytes.decode("utf-8"))
        if match:
            type = match.group(1)
            title = match.group(2).replace("::", "/")
            module_path = Path(title)

        parts = tuple(module_path.parts)
        nav[parts] = doc_path.as_posix()

with mkdocs_gen_files.open("devbook/reference/java/links.md", "w") as nav_file:
    nav_file.writelines(nav.build_literate_nav())

