site_name: Symbol Docs
docs_dir: pages
site_url: http://localhost:8000
repo_url: https://github.com/symbol/symbol
repo_name: symbol
edit_uri: edit/master/docs
plugins:
  - search
  - meta-manager
  - ezglossary: # Automatic glossary tooltips
      use_default: true
      inline_refs: none
      markdown_links: true
      tooltip: full
  - git-revision-date-localized: # git dates in page footers
      enable_creation_date: true
      exclude:
        - en/devbook/reference/py/*
  - git-authors: # git authors in page footers
      exclude:
        - en/devbook/reference/py/*
  - autorefs:
      resolve_closest: true
  - mkdocstrings: # Generate API reference docs from actual source code
      default_handler: python
      handlers:
        python:
          paths: [../sdk/python]
          options:
            show_source: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: false
            show_object_full_path: true
  - gen-files: # Generate stub files for API reference docs, to be filled by mkdocstrings
      scripts:
        - scripts/gen_ref_pages_py.py
  - literate-nav: # Allow navigation to be specified in the md files created by gen-files
      nav_file: navigation.md
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative $docs_dir
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - def_list
  - md_in_html
  - toc:
      permalink: ⚓︎
      title: On this page
      toc_depth: 3
theme:
  name: material
  custom_dir: pages/assets/overrides
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/symbol-logo.svg
  features:
    - content.tooltips # Material tooltips instead of browser
    #- navigation.instant # Single-page application
    - navigation.tracking # URL follows the current section in the page
    - navigation.tabs # Top navbar
    - toc.follow # Current section in TOC is always visible
    - content.tabs.link # Linked content tabs
    - content.code.copy # Copy code button in code blocks
    - content.action.edit # Edit on GitHub button
    - content.action.view # View on GitHub button
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  homepage: http://127.0.0.1:8000/en/
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: 日本語
      link: /jp/
      lang: jp
extra_css:
  - assets/stylesheets/extra.css
nav:
  - en/index.md
  - User Guide:
      - en/userbook/intro.md
  - Developer Guide:
      - en/devbook/0.introduction.md
      - en/devbook/1.accounts.md
      - en/devbook/2.namespaces.md
      - en/devbook/3.mosaics.md
      - en/devbook/4.transactions.md
      - en/devbook/5.nodes.md
      - en/devbook/6.blocks.md
      - en/devbook/7.xym.md
      - en/devbook/8.advanced.md
      - en/devbook/9.catapult.md
      - en/devbook/a.catbuffer.md
      - en/devbook/b.analytics.md
      - en/devbook/c.other.md
      - SDKs:
          - Python API Reference: en/devbook/reference/py/
  - Textbook:
      - en/textbook/intro.md
      - en/textbook/glossary.md
