// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import org.symbol.sdk.symbol.models.AccountRestrictionFlags;
import org.symbol.sdk.symbol.models.TransactionType;

/**
 * Type safe descriptor used to generate a descriptor map for AccountOperationRestrictionTransactionV1Descriptor.
 *
 * Allow or block outgoing transactions depending on their transaction type (V1, latest).
 */
public final class AccountOperationRestrictionTransactionV1Descriptor implements SymbolTransactionDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for AccountOperationRestrictionTransactionV1.
	 *
	 * @param restrictionFlags Type of restriction being applied to the listed transaction types.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor(final AccountRestrictionFlags restrictionFlags) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("type", "account_operation_restriction_transaction_v1");
		rawDescriptor.put("restrictionFlags", restrictionFlags);
	}

	/**
	 * Creates a descriptor for AccountOperationRestrictionTransactionV1 from string-form values.
	 *
	 * @param restrictionFlags Type of restriction being applied to the listed transaction types.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor(final String restrictionFlags) {
		this(AccountRestrictionFlags.parse(restrictionFlags));
	}

	/**
	 * Sets the restrictionAdditions field.
	 *
	 * @param restrictionAdditions Array of transaction types being added to the restricted list.
	 * @return This descriptor for chaining.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor restrictionAdditions(final List<TransactionType> restrictionAdditions) {
		if (null != restrictionAdditions)
			rawDescriptor.put("restrictionAdditions", restrictionAdditions);

		return this;
	}

	/**
	 * Sets the restrictionAdditions field.
	 *
	 * @param restrictionAdditions Array of transaction types being added to the restricted list.
	 * @return This descriptor for chaining.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor restrictionAdditions(final String... restrictionAdditions) {
		return restrictionAdditions(null == restrictionAdditions
				? null
				: Arrays.stream(restrictionAdditions).map(value -> TransactionType.parse(value)).collect(Collectors.toList()));
	}

	/**
	 * Sets the restrictionDeletions field.
	 *
	 * @param restrictionDeletions Array of transaction types being rtemoved from the restricted list.
	 * @return This descriptor for chaining.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor restrictionDeletions(final List<TransactionType> restrictionDeletions) {
		if (null != restrictionDeletions)
			rawDescriptor.put("restrictionDeletions", restrictionDeletions);

		return this;
	}

	/**
	 * Sets the restrictionDeletions field.
	 *
	 * @param restrictionDeletions Array of transaction types being rtemoved from the restricted list.
	 * @return This descriptor for chaining.
	 */
	public AccountOperationRestrictionTransactionV1Descriptor restrictionDeletions(final String... restrictionDeletions) {
		return restrictionDeletions(null == restrictionDeletions
				? null
				: Arrays.stream(restrictionDeletions).map(value -> TransactionType.parse(value)).collect(Collectors.toList()));
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
