// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.symbol.sdk.CryptoTypes;
import org.symbol.sdk.symbol.models.Cosignature;
import org.symbol.sdk.symbol.models.EmbeddedTransaction;

/**
 * Type safe descriptor used to generate a descriptor map for AggregateBondedTransactionV1Descriptor.
 *
 * Propose an arrangement of transactions between different accounts (V1, deprecated). Use this transaction when not all required signatures
 * are available when the transaction is created. Missing signatures must be provided using a Cosignature or DetachedCosignature. To prevent
 * spam attacks, before trying to announce this transaction a HashLockTransaction must be successfully announced and confirmed.
 */
public final class AggregateBondedTransactionV1Descriptor implements SymbolTransactionDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for AggregateBondedTransactionV1.
	 *
	 * @param transactionsHash Hash of the aggregate's transaction.
	 * @param transactions Embedded transaction data. Transactions are variable-sized and the total payload size is in bytes. Embedded
	 *            transactions cannot be aggregates. (field is omitted when null)
	 * @param cosignatures Cosignatures data. Fills up remaining body space after transactions. (field is omitted when null)
	 */
	public AggregateBondedTransactionV1Descriptor(final CryptoTypes.Hash256 transactionsHash, final List<EmbeddedTransaction> transactions,
			final List<Cosignature> cosignatures) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("type", "aggregate_bonded_transaction_v1");
		rawDescriptor.put("transactionsHash", transactionsHash);

		if (null != transactions)
			rawDescriptor.put("transactions", transactions);

		if (null != cosignatures)
			rawDescriptor.put("cosignatures", cosignatures);
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
