// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.symbol.models.MosaicRestrictionType;
import org.symbol.sdk.symbol.models.UnresolvedMosaicId;

/**
 * Type safe descriptor used to generate a descriptor map for MosaicGlobalRestrictionTransactionV1Descriptor.
 *
 * Set global rules to transfer a restrictable mosaic (V1, latest).
 */
public final class MosaicGlobalRestrictionTransactionV1Descriptor implements SymbolTransactionDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MosaicGlobalRestrictionTransactionV1.
	 *
	 * @param mosaicId Identifier of the mosaic being restricted. The mosaic creator must be the signer of the transaction.
	 * @param referenceMosaicId Identifier of the mosaic providing the restriction key. The mosaic global restriction for the mosaic
	 *            identifier depends on global restrictions set on the reference mosaic. Set `reference_mosaic_id` to **0** if the mosaic
	 *            giving the restriction equals the `mosaic_id`.
	 * @param restrictionKey Restriction key relative to the reference mosaic identifier.
	 * @param previousRestrictionValue Previous restriction value.
	 * @param newRestrictionValue New restriction value.
	 * @param previousRestrictionType Previous restriction type.
	 * @param newRestrictionType New restriction type.
	 */
	public MosaicGlobalRestrictionTransactionV1Descriptor(final UnresolvedMosaicId mosaicId, final UnresolvedMosaicId referenceMosaicId,
			final long restrictionKey, final long previousRestrictionValue, final long newRestrictionValue,
			final MosaicRestrictionType previousRestrictionType, final MosaicRestrictionType newRestrictionType) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("type", "mosaic_global_restriction_transaction_v1");
		rawDescriptor.put("mosaicId", mosaicId);
		rawDescriptor.put("referenceMosaicId", referenceMosaicId);
		rawDescriptor.put("restrictionKey", restrictionKey);
		rawDescriptor.put("previousRestrictionValue", previousRestrictionValue);
		rawDescriptor.put("newRestrictionValue", newRestrictionValue);
		rawDescriptor.put("previousRestrictionType", previousRestrictionType);
		rawDescriptor.put("newRestrictionType", newRestrictionType);
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
