// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.symbol.models.Amount;
import org.symbol.sdk.symbol.models.MosaicId;

/**
 * Type safe descriptor used to generate a descriptor map for MosaicDescriptor.
 *
 * A quantity of a certain mosaic.
 */
public final class MosaicDescriptor implements SymbolTypedDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for Mosaic.
	 *
	 * @param mosaicId Mosaic identifier.
	 * @param amount Mosaic amount.
	 */
	public MosaicDescriptor(final MosaicId mosaicId, final Amount amount) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("mosaicId", mosaicId);
		rawDescriptor.put("amount", amount);
	}

	/**
	 * Creates a descriptor for Mosaic from string-form values.
	 *
	 * @param mosaicId Mosaic identifier.
	 * @param amount Mosaic amount.
	 */
	public MosaicDescriptor(final String mosaicId, final String amount) {
		this(MosaicId.parse(mosaicId), Amount.parse(amount));
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
