// Auto-generated by generator. Do not edit directly.
// Run scripts/run_catbuffer_descriptor_generator.sh to regenerate.

package org.symbol.sdk.symbol.descriptors;

import java.util.LinkedHashMap;
import java.util.Map;

import org.symbol.sdk.symbol.models.Amount;
import org.symbol.sdk.symbol.models.MosaicSupplyChangeAction;
import org.symbol.sdk.symbol.models.UnresolvedMosaicId;

/**
 * Type safe descriptor used to generate a descriptor map for MosaicSupplyChangeTransactionV1Descriptor.
 *
 * Change the total supply of a mosaic (V1, latest).
 */
public final class MosaicSupplyChangeTransactionV1Descriptor implements SymbolTransactionDescriptor {
	private final Map<String, Object> rawDescriptor;

	/**
	 * Creates a descriptor for MosaicSupplyChangeTransactionV1.
	 *
	 * @param mosaicId Affected mosaic identifier.
	 * @param delta Change amount. It cannot be negative, use the `action` field to indicate if this amount should be **added** or
	 *            **subtracted** from the current supply.
	 * @param action Supply change action.
	 */
	public MosaicSupplyChangeTransactionV1Descriptor(final UnresolvedMosaicId mosaicId, final Amount delta,
			final MosaicSupplyChangeAction action) {
		rawDescriptor = new LinkedHashMap<>();
		rawDescriptor.put("type", "mosaic_supply_change_transaction_v1");
		rawDescriptor.put("mosaicId", mosaicId);
		rawDescriptor.put("delta", delta);
		rawDescriptor.put("action", action);
	}

	/**
	 * Builds a representation of this descriptor that can be passed to a factory function.
	 *
	 * @return Descriptor map that can be passed to a transaction factory.
	 */
	@Override
	public Map<String, Object> toMap() {
		return rawDescriptor;
	}
}
