type: object
description: |
  Deployment tool and version used to create/maintain the node; date of last upgrade.
required:
  - deploymentTool
  - deploymentToolVersion
  - lastUpdatedDate
properties:
  deploymentTool:
    type: string
    description: The tool used to create, maintain and deploy the node.
    examples:
      - 'symbol-shoestring'
  deploymentToolVersion:
    type: string
    examples:
      - '1.0.6'
    description: The version of the tool used to create, maintain and deploy the node.
  lastUpdatedDate:
    type: string
    examples:
      - '2025-06-02'
    description: When was the node last upgraded.
