openapi: 3.0.2
info:
  "$ref": "./info.yml"
tags:
  "$ref": "./tags.yml"
paths:
  "$ref": "./routes.yml"
# No authentication required for Symbol client API; empty requirement satisfies security-defined rule.
security:
  - {}
externalDocs:
  description: Symbol Technical Documentation
  url: https://docs.symbol.dev/
servers:
  - url: https://reference.symboltest.net:3001
    description: Testnet node

